### ISSUE TITLE
Crash when clicking copy file

### ISSUE THREAD

**Issue by tuanpham-dev** [gujjwal00/avnc#10]
As the title, I was kicked out to home screen when I was trying to copy a file. I think this bug related to clipboard sync feature. I think it should only sync when clipboard is text format.

**Comment by gujjwal00** [comment]
[This](https://github.com/gujjwal00/avnc/blob/24ec0e0b416b83a03c958072be42488b1d820ebc/app/src/main/java/com/gaurav/avnc/viewmodel/BaseViewModel.kt#L59) is where we are accessing the clipboard. [`getText()`](https://developer.android.com/reference/android/content/ClipData.Item#getText()) should return `null` when clipboard content is not textual.

Can you post the debug logs from Settings? Maybe they have some clue.

**Comment by tuanpham-dev** [comment]
Actually I was trying my modified version (version 1.1.0 on FDroid works fine). The copy logs function does not work in my version so I cannot post the logs.
I am closing this issue and will reopen it if I face the problem in official version.
