### ISSUE TITLE
Não totalmente modo imersivo

### ISSUE THREAD

**Issue by zequinh4** [gujjwal00/avnc#101]
Hello my friend @gujjwal00 . How much time. In the 4.1 update of One UI (Samsung) we have this small line on the top edge to put the application in windowed mode. However, this makes it difficult to press screen features that are at the top. 
Is there a possibility of a fully immersive one? Thanks.

https://user-images.githubusercontent.com/51301335/203418206-b02a0fad-32c3-4633-84cd-bf7d402b4361.mp4

**Comment by gujjwal00** [comment]
Does this happen in other apps too?

**Comment by zequinh4** [comment]
Hello. For the most part yes. Some video apps in Full Screen mode can bypass this. Thanks for listening!

**Comment by gujjwal00** [comment]
> Some video apps in Full Screen mode can bypass this

Can you tell me which apps?

**Comment by zequinh4** [comment]
Sorry. In fact, even when clicking/touching the screen, this same line appears... It must be impossible to remove it because it is from the system itself.

**Comment by gujjwal00** [comment]
Yeah, if none of the apps is able to hide it, then it is probably impossible.

**Comment by zequinh4** [comment]
> Yeah, if none of the apps is able to hide it, then it is probably impossible.

If you have time to stop and take a look later, I'd be grateful. thank you my friend. hugs from Brazil

**Comment by gujjwal00** [comment]
I googled around a bit, but could not find a way to disable this.

Only interesting lead I found was the last paragraph of this article: https://www.rprna.com/updates/one-ui/one-ui-4-1-tip-how-to-use-multi-windows-on-your-samsung-phone/
I don't know if they are talking about the same line you are, but do check it out.


I am closing this issue for now, but if you find any other app which is able to hide this bar, let me know.

**Comment by gujjwal00** [comment]
Hi @zequinh4 , just wanted to tell you that I am refactoring fullscreen handling in AVNC. I have just released a new version which includes some changes. If you notice any regressions in fullscreen behavior in v2.0.2 (or next few versions), please let me know.

**Comment by zequinh4** [comment]
Hello my friend @gujjwal00 . In version 2.0.2, fullscreen mode continues to work perfectly (with those limitations already mentioned here that must be intrinsic to ONEUI). Thank you for your commitment to improving the APP.
