### ISSUE TITLE
FR: more detailed error messages

### ISSUE THREAD

**Issue by Buntbart** [gujjwal00/avnc#102]
Can we have more detailed output on error messages when connections ar failing, please?
The message:  
`( There was a problem while connecting to machine:22 )`  
doesn't explain very much.

In my case I try to investigate why AVNC does not connect via ssh to one specific server, while  
- other clients like Remmina can connect to this server
- AVNC can connect to other servers in the same way (ssh-tunnel to a localhost-restricted vnc-server)

A bit more of information about the `problem` would be helpful.

**Comment by gujjwal00** [comment]
> Can we have more detailed output on error messages when connections ar failing, please?

I would love to provide more relevant error messages, but my hands are tied here. These messages can come from the 3-party libraries, which sometimes wraps the real error inside a generic error. E.g. in case of LibVNCClient, it simply returns true/false result. I had to [patch](https://github.com/gujjwal00/libvncserver/commit/b18a3272c2a8195b95cdf3645320c71d81b8ac2e) it to get some sensible errors out of of it.

In your case, error comes from `sshlib`, which is usually good about reporting, but sometimes can throw generic error. You can access detailed logs from **Settings => Tools => Logs**. If you are unable to make sense of the logs, please post them here.

**Comment by Buntbart** [comment]
Oh, sorry, I had not initially discovered the log function in the tools.
But it is still confusing:  
- after a reboot of the computer I can get to LightDM via AVNC and can log in.
- when after a while the screen of the computer dims, I can't connect anymore: "Host unreachable". Also when i wake it up i can't connect anymore.
- nevertheless I can still reach the computer from the same smartphone with Termux via ssh and also other VNC clients can connect through ssh tunnel as I said.

See log:
[log.txt](https://github.com/gujjwal00/avnc/files/10096118/log.txt)

**Comment by gujjwal00** [comment]
You seem to be using `machine` as SSH host.
- Is this host reachable from your smartphone (e.g. from termux)? 
- Can you please try using the IP address directly?
- Can AVNC connect to  `machine` without SSH?

**Comment by Buntbart** [comment]
- `ssh user@machine` works in termux
- oh, yes, it works with AVNC while using the IP address directly!
- x11vnc-server on machine is restricted to localhost, so it is intended that I can't connect without SSH.

**Comment by gujjwal00** [comment]
Well if using IP address works, then I don't really know why libssh is throwing `NoRouteToHostException`. Could be a DNS issue or firewall issue. Maybe IPv6 is somehow involved.

You may have to do dome digging yourself 😀. Maybe something special is configured in termux. If you have control over x11vnc-server, you could temporarily allow remote connections.  Or maybe try ConnectBot's SSH client (AVNC uses ConnectBot's SSH library).

**Comment by Buntbart** [comment]
With connecting to the IP address directly I have a workaround now. Thank you for your efforts!

**Comment by Buntbart** [comment]
I tried a little more and found a solution.  
`machine` is a laptop that turns off the wifi after login. The routers DHCP had an IP address `xxx.xxx.xxx.59` stored for the wifi connection.  
Apparently AVNC tried unsuccessfully to connect to it and then gave up instead of trying the other IP address for the ethernet connection on `xxx.xxx.xxx.100`.  
I have now assigned xxx.xxx.xxx.101 to the wifi connection and since then AVNC finds the ethernet connection again, even when the wifi connection for `machine` is turned off.  
Maybe AVNC should make another try in the remaining address range if one IP address is not reachable, since hosts can have more than one IP address.

**Comment by gujjwal00** [comment]
Hi @Buntbart , I have added support for multiple IP address (only had to do this for `libssh`, as non-SSH connections already support this). 

Can you please test the following APK with your original DNS configuration:
https://github.com/gujjwal00/avnc/suites/9546601612/artifacts/454006921

**Comment by Buntbart** [comment]
This version works fine in my old setup!
`machine` gets found even when the wifi-connection with lower IP address is turned off.
Thank you again for your work, I'm looking forward to the next release on F-Droid.

**Comment by gujjwal00** [comment]
Note that libssh only provides a single `connect()` method which does the whole setup (connecting to address, key exchange, host-key verification etc.). So `connect()` can fail for a number of reasons, and blindly retrying `connect()` on every error is not suitable. For now, next address will be tried only if `Host unreachable` error is encountered.
