### ISSUE TITLE
No option to hide the keyboard

### ISSUE THREAD

**Issue by ThieuMinh26** [gujjwal00/avnc#104]
there is no option to turn off the keyboard , why the button can show the keyboard but it can hide the keyboard

**Comment by ThieuMinh26** [comment]
2 finger tap gesture too ,if i open the keyboard how do i disable it

**Comment by gujjwal00** [comment]
Simply press the Back key on navigation bar.

**Comment by gujjwal00** [comment]
> why the button can show the keyboard but it can hide the keyboard

Because, believe it or not, there is no reliable API available to check if keyboard is visible, for all supported Android versions. There are heuristics, which can fail. So I don't want a situation where user is unable to open keyboard.

**Comment by ThieuMinh26** [comment]
> > why the button can show the keyboard but it can hide the keyboard
> 
> Because, believe it or not, there is no reliable API available to check if keyboard is visible, for all supported Android versions. There are heuristics, which can fail. So I don't want a situation where user is unable to open keyboard.

then can you add a new hide key board button or add a option to disable keyboard using 2 finger tap or sth like that ?

**Comment by ThieuMinh26** [comment]
this vnc is way faster than realvnc but it have some annoying feature 🥲

**Comment by ThieuMinh26** [comment]
like there is no option to enable /disable both keyboard and toolbar at the same time , i have to disable it twice🥲

**Comment by gujjwal00** [comment]
>then can you add a new hide key board button 

No, I am not adding a redundant button.

>or add a option to disable keyboard using 2 finger tap or sth like that ?

Maybe an option can be added. But what's your issue with back press?

> like there is no option to enable /disable both keyboard and toolbar at the same time , i have to disable it twice

Have you tried enabling `Open with keyboard` in **Settings => Input => Virtual Keys** ?

**Comment by ThieuMinh26** [comment]
> Maybe an option can be added. But what's your issue with back press?

its hard  to do that and take a lot of of time in portrait mode

>Have you tried enabling Open with keyboard in 
Settings => Input => Virtual Keys

thank you

**Comment by ThieuMinh26** [comment]
and each time i swipe up to press back button i will touch the keyboard

**Comment by gujjwal00** [comment]
Can you please tell me your Android version?

**Comment by ThieuMinh26** [comment]
> Can you please tell me your Android version?

im using android 11

**Comment by gujjwal00** [comment]
Thanks.
Just one more question: You are using three-button navigation bar (instead of gesture navigation), right?

**Comment by ThieuMinh26** [comment]
> Thanks. Just one more question: You are using three-button navigation bar (instead of gesture navigation), right?

yes

**Comment by gujjwal00** [comment]
So your issue seems to be that when you open the keyboard, the navigation bar is still hidden. To close the keyboard, you have to first show the navigation bar by swiping, and than tap on the Back button to close the toolbar. Right?

**Comment by ThieuMinh26** [comment]
> So your issue seems to be that when you open the keyboard, the navigation bar is still hidden. To close the keyboard, you have to first show the navigation bar by swiping, and than tap on the Back button to close the toolbar. Right?

Yes and  that's really annoying for me

**Comment by gujjwal00** [comment]
@ThieuMinh26 Can you test the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/10140699/app-debug.zip)

It should correctly show the navigation bar when keyboard is opened.

**Comment by ThieuMinh26** [comment]
> @ThieuMinh26 Can you test the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/10140699/app-debug.zip)
> 
> It should correctly show the navigation bar when keyboard is opened.

yeah its fixed . But is it normal for test apk to be slower + more screen tearing than stable apk ?

**Comment by gujjwal00** [comment]
Yeah, the APK linked above was a debug build, without any optimizations.

I have pushed the fix:  https://github.com/gujjwal00/avnc/commit/577fdd1344672e84f6434577b7e304f7901dfe6c
Optimized APK: https://github.com/gujjwal00/avnc/suites/9631432148/artifacts/460174850

You can use this APK until next version is released.

**Comment by gujjwal00** [comment]
v2.0.2 is now available.
