### ISSUE TITLE
[Feature request]  Sleep and auto-reconnect.

### ISSUE THREAD

**Issue by jdnumm** [gujjwal00/avnc#107]
I use avnc on an old tablet as an external monitor, and there are two little things that could significantly improve this use case for me.

1. If the host is not reachable anymore, avnc should let the client system sleep. Currently, it just stays on endlessly.

2. When the connection is closed, but I still have a host selected. Avnc should try to reconnect automatically.

So, I could turn off the host and the tablet will also go to sleep mode automatically. When the host starts, the tablet only needs to be turned on and can automatically be used as an external display again.

**Comment by gujjwal00** [comment]
>If the host is not reachable anymore, avnc should let the client system sleep. Currently, it just stays on endlessly.

I was planning to change this behavior some time ago, but forgot. Thanks for reminding me.

> When the connection is closed, but I still have a host selected. Avnc should try to reconnect automatically.

This is much more complex. Many questions needs to be answered here: how long to wait before retrying, how many retries before giving up, what if I don't want this behavior, how to provide feedback to user, what happens when AVNC is in background or screen is turns off,  etc. 

IMO, blindly trying to reconnect may cause more problems then it will solve. Can you just tap on the 'Retry' button in AVNC when you turn on the tablet?

**Comment by jdnumm** [comment]
Thanks for the quick reply 

> IMO, blindly trying to reconnect may cause more problems then it will solve. Can you just tap on the 'Retry' button in AVNC when you turn on the tablet?

That is how I do it now. I think the app just needs to reconnect when it is in focus. It doesn't make much sense in the background because the user can't interact with it. For me, it would do every 30s. 

Maybe like an option when creating a connection?

[ Yes / No ] Automatic reconnect
[ 10s ] (If Yes) Time between two attempts.

**Comment by capatina** [comment]
Hello, if auto-reconnect is more challenging, we would like to see the app auto-connect on startup first. We use the app as a monitor for a device and need it connected when the android tablet restarts for whatever reason

**Comment by gujjwal00** [comment]
First issue about sleep-while-disconnected is already fixed (https://github.com/gujjwal00/avnc/commit/2eac4cbac76823d0d4c01177f12d280ad66b0908) a while back.

About auto-reconnect:
Can you guys test the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/10442945/app-debug.zip)

You can enable auto-reconnect in **Settings => Servers**. AVNC will wait for ~5 seconds before reconnecting. AVNC will not reconnect if it is in background, or screen is off.

**Comment by gujjwal00** [comment]
Auto-reconnect is available in [v2.1.0](https://github.com/gujjwal00/avnc/releases/tag/v2.1.0).
