### ISSUE TITLE
"canvas" centering should account for the height of the virtual keys

### ISSUE THREAD

**Issue by sudomain** [gujjwal00/avnc#109]
Before I explain what I think is a small bug with how the canvas gets centered, I think I should describe my end goal in case there's a work around. I'm connecting to a local vnc server in Termux whose geometry I'm free to change. In portrait orientation, I wish to use the whole screen without:
1. Overlapping elements such as how the virtual keys of AVNC usually cover the bar of my desktop environment.
2. The gray pixels that AVNC show around the canvas when it it too zoomed out.

I can get pretty close to this using a vnc server geometry of 1080x1080 and reseting the zoom to 100%:
![Screenshot_20221212-214249](https://user-images.githubusercontent.com/30786326/207213997-ceff4afb-b98b-45f9-8481-942465399bcd.png)

However, notice in the screenshot that I have both the virtual keys overlapping my bottom status bar and wasteful gray pixels along the top. I can't be sure, but I think the amount of overlap is pretty close to the amount of gray pixels. Ideally, the canvas would be shifted up by this amount to eliminate the overlap and utilize the gray area.

If there's no workaround, I'd like to request that the code that handles the centering of the canvas be changed so that it accounts for the height of the virtual keys

**Comment by gujjwal00** [comment]
Yes, right now, virtual key layout is more optimized for [this](https://github.com/gujjwal00/avnc/blob/master/metadata/en-US/images/phoneScreenshots/8.jpg) case.

Layout handling in AVNC is slightly more complex. I am currently improving it to handle more cases (e.g. display cutouts). I also have ideas about handling virtual keys, but  I don't know how long it will take.

**Comment by gujjwal00** [comment]
Reducing height in geometry is not going to work because AVNC is trying to be helpful by filling vertical scale. So it will up-scale anything you set.

**Comment by sudomain** [comment]
Those dimensions and some very slow zooming makes it perfect, or at least close enough that I can't tell. Thank you.

I can't speak for @PureIncompetence , but ultimately I got the result I wanted from this issue and can close it

**Comment by gujjwal00** [comment]
Fixed in https://github.com/gujjwal00/avnc/commit/f7d5eb682d2df73acd4ae15e0dd483e0457c53c0.

**Comment by nahuhh** [comment]
> Fixed in https://github.com/gujjwal00/avnc/commit/f7d5eb682d2df73acd4ae15e0dd483e0457c53c0.

I have not tested the release version 2.1.1, only 2.0.4 and the dev build posted above. 

2.0.4: 
- the top of your keyboard + screen edges are used as the boundaries. 
- Issue: when opening virtual key row, the bottom boundary isnt changed to respect the added height, resulting in the virtual keys overlapping the viewport

Dev build: 
- while it does succeed at adjusting the bottom boundary, a new issue is introduced.
- issue: with or without the virtual keys enabled, when zoomed the top of the screen cant be scrolled into view.

**Comment by gujjwal00** [comment]
@nahuhh which device are you using? Can you also post any screenshot or video to highlight the issue?
