### ISSUE TITLE
FR: set remote display resolution

### ISSUE THREAD

**Issue by pguenth** [gujjwal00/avnc#11]
First of all, thank you for the great app. Especially the built-in SSH tunneling is extremely useful.
In my opinion it would be very useful to be able to set the remote display resolution in the app. I think at the moment the default server resolution is used which leads to impractical scrolling due to the server's default landscape orientation.
Thank you again!

**Comment by gujjwal00** [comment]
> First of all, thank you for the great app. Especially the built-in SSH tunneling is extremely useful.

Really happy to know that you find it useful!

It is true that currently server's default resolution is used. But the the issue you are describing (that you have to scroll in portrait mode as you cannot see the whole frame) may be related to how AVNC handles zooming.

AVNC tries to maximize the frame size, using bigger side of the viewer. So in effect, it is optimized for the landscape mode. Because if smaller side is used, so that whole frame is visible in portrait mode, frame size becomes too small and you have to regularly zoom-in  to use it.

**Comment by garabik** [comment]
I am quite happy with setting the resolution manually: `$ xrandr`, pick the desired one, then `$ xrandr --output VNC-0 --mode HORIZONTALxVERTICAL`... (I've made a script for this, of course)

**Comment by pguenth** [comment]
> AVNC tries to maximize the frame size, using bigger side of the viewer. So in effect, it is optimized for the landscape mode. Because if smaller side is used, so that whole frame is visible in portrait mode, frame size becomes too small and you have to regularly zoom-in to use it.

Thank you for the clarification, this absolutely makes sense, but I am constantly requiring the keyboard and with the keyboard open the available space on the phone screen becomes relatively small in landscape mode.

> I am quite happy with setting the resolution manually: `$ xrandr`, pick the desired one, then `$ xrandr --output VNC-0 --mode HORIZONTALxVERTICAL`... (I've made a script for this, of course)

Nice idea, I somehow never thought about manually setting the display size on the server side. I think this will work out for me for the moment.

**Comment by garabik** [comment]
> Edit: since the resolution I wanted to set is not an available xrandr mode, I can't use `xrandr --mode`, but I found `xrandr --fb HORIZONTALxVERTICAL` to work (see https://askubuntu.com/a/451968).

That works (at least for me) only if the new size is _bigger_ than the current resolution, otherwise it fails with "specified screen HxV not large enough for output VNC-0". I guess it could depend on the vnc server (currently I am using TurboVNC).

**Comment by pguenth** [comment]
Works for me both ways, I am using TigerVNC on ArchLinux.

**Comment by garabik** [comment]
> Works for me both ways, I am using TigerVNC on ArchLinux.

Switching to TigerVNC, it works - though when I issue the command, my window manager (ratpoison) immediately segfaults, AVNC disconnects, and on reconnecting sometimes shows rather confused picture - something like extremely enlarged part of the screen. So I should not do it without a separate ssh connection to fix the resolution if this happens. That means I'll keep using `--mode`, this is so far 100% reliable.
