### ISSUE TITLE
Feature request: pass-through of gamepad keyevents

### ISSUE THREAD

**Issue by sudomain** [gujjwal00/avnc#111]
Hi I'm trying to get keyevents from a gamepad sent to an application running on my vnc server. The specific gamepad is a "8bitdo zero 2". The server is tigervnc running locally in a debian PRoot in Termux. In an attempt to debug, I used the programs `showkey -a` and `xev` in the proot. I was able to see that most "normal" key events get passed through without issue, but key events from the controller such as `KEYCODE_BUTTON_L1` don't get sent through. Because of this, I think AVNC is ignoring these nonstandard key events.

**Comment by gujjwal00** [comment]
Can you test the gamepad  on a standalone Linux system? Run `xev`, and press different buttons on gamepad. Copy the output from xev, and paste here.

Although I have some idea about XKeySyms, I just want to confirm their values.

**Comment by sudomain** [comment]
Hmm I don't think I have the hardware unfortunately. I have a few linux systems but none with built-in Bluetooth or a Bluetooth adapter. I could order a cheap usb-bluetooth adapter if needed

**Comment by gujjwal00** [comment]
In that case, just use Termux to get key-code for all gamepad buttons, like you did for `KEYCODE_BUTTON_L1`.

**Comment by gujjwal00** [comment]
Ignore previous comment, I don't think it will be helpful.

For each gamepad button, I need to know:
1. Keycode being generated in Android (e.g. `KEYCODE_BUTTON_L1`)
2. XKeySym being generated in `xev`

so that AVNC can map them.

VNC protocol works on key symbols specified by X11. I looked around, but could not find anything related to gamepads. Do you have any other gamepads you can test with standalone server?

**Comment by sudomain** [comment]
Sorry, I don't have other gamepads. I could buy a $15 usb-bluetooth adapter and use it with a separate system with xev.

With a button remapping app called [KeyMapper](https://github.com/keymapperorg/KeyMapper), it's able to detect the KEYCODE_BUTTON_ 's of:
1. SELECT
2. START
3. L1
4. L2
5. A
6. B
7. X
8. Y

Which coincidentally is every button  on the controller except the D-pad:

![Screenshot_20221214-111840](https://user-images.githubusercontent.com/30786326/207650614-32509c84-439f-412b-a73d-a882110e5b79.png)

**Comment by sudomain** [comment]
Hmm. I don't if you're familiar with that app, but it not only detects KEYCODE_s from the OS, but can also send them using its `Input key event` action (keymapper's actions can do other things, but only input key event is relevant). Anyway, if I remap the X button to send "/" (76 KEYCODE_SLASH), avnc will pass it through to the server. However, if I map it to send 99 KEYCODE_BUTTON_X, it does not get passed through. Testing was again done with xev and show key.

Sorry if this is all useless information, just thought I'd share something I tried with a separate app and avnc.

**Comment by gujjwal00** [comment]
>Hmm. I don't if you're familiar with that app, but it not only detects KEYCODE_s from the OS, but can also send them using its Input key event action (keymapper's actions can do other things, but only input key event is relevant). Anyway, if I remap the X button to send "/" (76 KEYCODE_SLASH), avnc will pass it through to the server. However, if I map it to send 99 KEYCODE_BUTTON_X, it does not get passed through. Testing was again done with xev and show key.

Yes this is expected. After AVNC receives an event, it will convert it into corresponding XKeySym and send that to server. It doesn't  matter whether the event came directly from gamepad, or if it was simulated by any app. 

Android and VNC protocol uses different values for keys. E.g. `A` key is represented in Android by `KEYCODE_A [value: 29]`, while corresponding XKeySym is `XK_a [value: 97]`. You can see the conversion table [here](https://github.com/gujjwal00/avnc/blob/cc2b5600fdcc201c571ca1a2a54ecb4616187539/app/src/main/java/com/gaurav/avnc/vnc/XKeySymAndroid.kt#L40).

Issue here is that AVNC doesn't know what value to send to the server once `KEYCODE_BUTTON_X` is recieved. Normally, I can search around to find this information, but I could not find anything about gamepad button in X11 specification (which is where these XKeySyms comes from).

**Comment by gujjwal00** [comment]
> I could buy a $15 usb-bluetooth adapter and use it with a separate system with xev.

I wouldn't recommend recommend buying anything, until there is some clarification on game pad buttons in X11.

**Comment by gujjwal00** [comment]
Looked more into this, and it looks game pad support is simply not possible via VNC.

**Comment by sudomain** [comment]
Thank you for researching it. This is out of my wheelhouse but I was able to follow recommendations [here]( https://askubuntu.com/questions/93772/where-do-i-find-a-list-of-all-x-keysyms-these-days) to search keysyms on my system and was able to find:
`
root@localhost:/usr/include/X11# grep '#define.*XK_L1' /usr/include/X11/*.h

/usr/include/X11/keysymdef.h:#define XK_L1                            0xffc8

/usr/include/X11/keysymdef.h:#define XK_L10                           0xffd1
`
And similar for R1, but I'm guessing this isn't the L1 button since there appears to be 10 of them, and nothing for A B X or Y. Guess I'll have to remap the buttons using KeyMapper. Thanks again

**Comment by gujjwal00** [comment]
> And similar for R1, but I'm guessing this isn't the L1 button since there appears to be 10 of them, and nothing for A B X or Y. 

Yeah, these are the ones I was talking about in my first comment. But apparently these are related to function keys found on some Sun keyboards. `/usr/include/X11/keysymdef.h` has a note explaining their purpose.

**Comment by sudomain** [comment]
In case there's a slight chance this can help someone in the future: This gamepad (and I'm guessing some other gamepads) can be turned on in a "keyboard mode" which makes it appear as a keyboard to Android and sends the characters `c` through `o` depending on which button is pressed. AVNC of course has no problem sending these keys to the server. It also allows D-Pad events (c,d,e, and f keys) to be sent through which wouldn't have been possible when in "Android mode", though they have to be remapped on the server side using a hotkey software. Holding `R` while powering on the pad starts it in keyboard mode.
