### ISSUE TITLE
Mouse is offset upwards

### ISSUE THREAD

**Issue by mariomadproductions** [gujjwal00/avnc#112]
When using touch screen mode in v2.0.1, the mouse is offset upwards by a bit (enough to be annoying). This issue didn't exist in v2.0.0.

**Comment by gujjwal00** [comment]
I am unable to reproduce this issue. Also, I didn't change anything related to touch screen mode in v2.0.1.
Can you please create a screen recording? Remember to enable 'Show taps' option, so that touch points are included in the recording.

**Comment by mariomadproductions** [comment]
Annoyingly I can't recreate it anymore, even though I managed to a few times before...

**Comment by gujjwal00** [comment]
No problem! If you encounter it again, simply reopen this issue.

**Comment by mariomadproductions** [comment]
Thanks.
