### ISSUE TITLE
Include landscape/portrait/Automatic mode setting in Server Profiles instead of in Settings

### ISSUE THREAD

**Issue by barkoder** [gujjwal00/avnc#115]
I connect to an Android VNC server([running droidvnc](https://f-droid.org/en/packages/net.christianbeier.droidvnc_ng/)) in Portrait Mode.  
"Automatic" and "Portrait" in settings work here.

I also connect to a PC in landscape. The "Automatic" setting doesn't work so I have set it to "Landscape" in Settings to get it to orientate correctly.

Currently I'm having to go to settings everytime to switch between the two.

Could you add the landscape/portrait/Automatic option in the server profile, instead of in Settings, so users may set it on a server-by-server basis?

Thanks!

**Comment by gujjwal00** [comment]
This is available in [v2.1.0](https://github.com/gujjwal00/avnc/releases/tag/v2.1.0).
