### ISSUE TITLE
Feature request: change behavior of virtual (modifier) keys: short press keys to make them apply to only next key event, long press to have the key be "sticky".

### ISSUE THREAD

**Issue by sudomain** [gujjwal00/avnc#117]
Hello,

Could the modifier keys (Shift, Ctrl, Alt, and Meta (Windows)) be made so that a long press causes them to become "sticky" (I.e. sticky keys) or applied to every key press until they're turned off with another press please? This is the current behavior of the short press of a modifier key. The reason I ask is because I'd also like the short press of modifier keys to apply only to the next key press, and then deactivate. This is similar behavior to Termux's [extra-keys row](https://wiki.termux.com/wiki/Touch_Keyboard), but also on many Android soft keyboards short pressing Shift tends to only capitalize the next letter, whereas long pressing Shift tends to activate caps lock.

**Comment by gujjwal00** [comment]
Hi @sudomain , I am working on full re-implementation of virtual keys. The new layout follows the same style as Termux. (There are some differences as the use case is different for AVNC). 
- 2-row layout similar to Termux
- Meta keys are automatically released on next key press. Long-press to lock meta keys, as described in this particular issue.
- There are three swipable "pages":
  - First two pages contain keys
  - Similar to Termux, third page contains an editbox. It allows you to have full-fledged Android editing experience in a session. When finished, you can send the whole text to server in one go.


First page:
![Screenshot_2024-04-04-21-51-23-702_com gaurav avnc debug-edit](https://github.com/gujjwal00/avnc/assets/27951674/de3bd2d5-4dbf-420b-9650-74b3e8d782ac)


Edit box:
![Screenshot_2024-04-04-21-52-25-104_com gaurav avnc debug-edit](https://github.com/gujjwal00/avnc/assets/27951674/9b26f614-f0f7-48eb-aaee-8649c06ee283)

---

While there are still some rough edges, I would appreciate if you guys can test it.
Test APK: https://github.com/gujjwal00/avnc/actions/runs/8556937174/artifacts/1385269187

cc @dp-alvarez

**Comment by gujjwal00** [comment]
That was already on my mind, but then the current implementation got slightly more complex. So I decided to get this working for now, and put custom configuration on hold. Maybe someday it will be implemented, but I don't have any immediate plans for it.

That said, is there any key missing from current layout?

**Comment by gujjwal00** [comment]
v2.5 is now available with this change. 
And I will let you know when the keys are more configurable.

**Comment by gujjwal00** [comment]
Hi @sudomain I am working on allowing users to configure key layout. Instead of a file, I have added a small UI to customize keys.

Test APK: https://github.com/gujjwal00/avnc/actions/runs/10252731991/artifacts/1777326375 
Go to `Settings => Input => Virtual Keys => Customize keys` to make changes.

**Comment by sudomain** [comment]
@gujjwal00  Thank you very much!
