### ISSUE TITLE
Feature Request: Toggle Input Mode (Direct Touch / Touchpad) in mid-session menu

### ISSUE THREAD

**Issue by PureIncompetence** [gujjwal00/avnc#118]
I really like the option to change the Input Mode on a per-device basis as it allows to control a remote android device with direct touch while controlling a desktop with touchpad mode.
Lately I noticed that there are several situations where - even controlling a desktop session - direct touch mode would be helpful. Therefore I regularly exited the session, changed the per-device setting between direct touch and touchpad mode and re-entered the session.
If possible it would be very handy to be able to switch between these two control modes using the same swipe-in menu which is used for saving / restoring per-device zoom levels. An extra button "toggle input mode" would be a huge enhancement in usabillity in my opinion.

**Comment by thiswillbeyourgithub** [comment]
+1

This is the one feature that blocks me from using it daily :/ All the rest is top notch it's so frustrating :)

**Comment by gujjwal00** [comment]
Added via https://github.com/gujjwal00/avnc/commit/4b118e853d609e8d4cca81d053229c00ceea0587
Test APK: https://github.com/gujjwal00/avnc/suites/11365394180/artifacts/584517807

This is temporarily gated behind the `Viewer => Toolbar => Show gesture style toggle` preference. When this pref is enabled, you should be able dynamically change gesture from toolbar. Something like this:

![image](https://user-images.githubusercontent.com/27951674/223019086-4942bbf9-1a17-448e-8165-25e51f6bbd85.png)

Let me know if you face any issue.

**Comment by gujjwal00** [comment]
[v2.2.0](https://github.com/gujjwal00/avnc/releases/tag/v2.2.0) is now available.
