### ISSUE TITLE
[Bug]: Clipboard only synced one-way

### ISSUE THREAD

**Issue by babaric-dev** [gujjwal00/avnc#120]
#62 occurs on my device. Still not fixed.

Text on Android clipboard gets sent to remote before connecting but not while connected. Text copied from remote are, however, reflected on client.

Now, everytime I copy something from Android's browser, I need to reconnect to paste to remote.

Idk much about Kotlin and Android apps, but it seems that `onResume` is already implemented (correct me if I am wrong).

Device running Android 13, One UI 5

**Comment by gujjwal00** [comment]
I am out of town for couple of weeks, so can't do much right now. But as you said AVNC only sends text to server when it comes to foreground, i.e. `onResume`. It doesn't listen to clipboard changes in background.

Are you using AVNC in multi-window mode?

**Comment by babaric-dev** [comment]
either way, it doesn't work.

**Comment by gujjwal00** [comment]
Can you please test the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/10379964/app-debug.zip)

After copying something, you need to give focus to AVNC (simply tap anywhere on AVNC). Android restricts clipboard access to focused apps (on API 29+). There is no workaround for this behavior.

**Comment by Saikatsaha1996** [comment]
> Can you please test the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/10379964/app-debug.zip)
> 
> After copying something, you need to give focus to AVNC (simply tap anywhere on AVNC). Android restricts clipboard access to focused apps (on API 29+). There is no workaround for this behavior.

My Android device `api 31`
Copy & pst works just fine.. & yes when anyone wants to pst something `avnc` should on in background

**Comment by gujjwal00** [comment]
Fixed in https://github.com/gujjwal00/avnc/commit/71f84b594bf6269c52d37053a105e09c7ddb94ad.
