### ISSUE TITLE
How do I drag anything?

### ISSUE THREAD

**Issue by Saikatsaha1996** [gujjwal00/avnc#125]
Suppose i open a terminal.. and want to move it left or right.. how do I drag terminal or etc

One more thing i want to copy text from vnc how do I copy?..

**Comment by gujjwal00** [comment]
> Suppose i open a terminal.. and want to move it left or right.. how do I drag terminal or etc

1. Go to **Settings => Input => Drag**, and set it to `Drag remote content`
2. Connect to your VNC server
3. Long-press on anything you want to drag, and move your finger 

> One more thing i want to copy text from vnc how do I copy?..

1. Make sure **Settings => Servers => Clipboard sync** is enabled
2. [Copying from server] After connecting, simply copy anything, like you would do on a laptop. It should automatically become available on Android's clipboard. You can switch to any other app and paste it there.
3. [Copying from Android] Copy something from an app. Switch to AVNC and connect to server (if not connected already). AVNC will send clipboard text to server whenever it comes to foreground.

**Comment by Saikatsaha1996** [comment]
> > Suppose i open a terminal.. and want to move it left or right.. how do I drag terminal or etc
> 
> 1. Go to **Settings => Input => Drag**, and set it to `Drag remote content`
> 2. Connect to your VNC server
> 3. Long-press on anything you want to drag, and move your finger
> 
> > One more thing i want to copy text from vnc how do I copy?..
> 
> 1. Make sure **Settings => Servers => Clipboard sync** is enabled
> 2. [Copying from server] After connecting, simply copy anything, like you would do on a laptop. It should automatically become available on Android's clipboard. You can switch to any other app and paste it there.
> 3. [Copying from Android] Copy something from an app. Switch to AVNC and connect to server (if not connected already). AVNC will send clipboard text to server whenever it comes to foreground.

Just awesome application.. haven't any comments.. very user friendly & all future available..👍

**Comment by gujjwal00** [comment]
Thanks for nice words @Saikatsaha1996!

**Comment by Saikatsaha1996** [comment]
> Thanks for nice words @Saikatsaha1996!

 most welcome 😊

**Comment by Saikatsaha1996** [comment]
@gujjwal00 hello dear can you add support for X-server & Wayland protocol?

I installed GPU driver in but vnc display not coming properly with my own GPU driver.. 

My GPU driver x11 & Wayland protocol GPU driver
Screen is black..
![Screenshot_2023-01-15-06-16-55-370_com gaurav avnc](https://user-images.githubusercontent.com/72664192/212523574-8b9b2261-94e2-4239-b401-957ea4500c0c.jpg)

**Comment by gujjwal00** [comment]
Wayland is not something AVNC has any control over. Your VNC server needs to support it. Check the documentation of you server.

**Comment by Saikatsaha1996** [comment]
> Wayland is not something AVNC has any control over. Your VNC server needs to support it. Check the documentation of you server.

Ohh i am useing tigervnc but display is black.. actually i am not much familiar with vnc or server..

**Comment by gujjwal00** [comment]
Yeah, tigervnc doesn't support Wayland. I think most VNC servers don't support it right now. Only one I am aware of is Gnome in Ubuntu 22.04+

**Comment by Saikatsaha1996** [comment]
> Yeah, tigervnc doesn't support Wayland. I think most VNC servers don't support it right now. Only one I am aware of is Gnome in Ubuntu 22.04+

![Screenshot_2023-01-09-19-58-49-171_com gaurav avnc](https://user-images.githubusercontent.com/72664192/212524298-c26adac7-c364-48bf-abeb-ed14f0cb5a65.jpg)


This is my gnome session with gnome flashback..
Only problem with my GPU own GPU driver

**Comment by gujjwal00** [comment]
Sorry, I am not familiar with gnome flashback.
