### ISSUE TITLE
Bug: Flickering UI due to pre-session post-session orientation mismatch

### ISSUE THREAD

**Issue by barkoder** [gujjwal00/avnc#128]
If the pre-session UI orientation of AVNC does not match post-session exit orientation, AVNC UI will flicker.

AVNC Version 2.0.4

Steps to reproduce:

0. Allow auto-rotate on phone settings.

1. Open AVNC.

2. Visually keep note of the orientation of your screen/UI - Portrait/Landscape.

3. Without rotating the phone, Go to **Settings > Viewer > Screen Orientation** and select "Portrait" if your UI is in "Landscape", OR select "Landscape" if your UI is in "Portrait".

4. Exit Settings and open your server.

5. Rotate your phone to "landscape" if you selected "landscape" in Step 3, or "Portrait" if you selected "Portrait" in Step 3.

6. Press "Back" and exit your VNC Session.

7. Notice the AVNC UI Flicker.

**Comment by gujjwal00** [comment]
I can't reproduce this. UI stays normal for me after step 6.

Which Android version are you using?
Can you create a screen recording?

**Comment by barkoder** [comment]
Sorry, Android 6.0, forgot to mention.

Also want to show that the issue does not exist in the [custom 1.9.2 apk you gave me here](https://github.com/gujjwal00/avnc/issues/89#issuecomment-1216317860) which I was using before updating to 2.0.4.


https://user-images.githubusercontent.com/70430094/213896773-317f3d95-1b28-459b-af00-050229d3c5b9.mp4

**Comment by gujjwal00** [comment]
Can you try the following APK:   https://github.com/gujjwal00/avnc/suites/10753322396/artifacts/539723524

**Comment by barkoder** [comment]
Solved. Thanks @gujjwal00 .
