### ISSUE TITLE
Question regarding image quality.

### ISSUE THREAD

**Issue by Anonymous2716** [gujjwal00/avnc#130]
I use avnc mostly with termux so the vncserver runs on localhost therefore almost unlimited network bandwidth.  And RAW image quality won't be an issue. 

I've seen the other issues on this topic where you added options to enable raw image quality but in the settings of the app I see no such option I'm using version 2.0.0. Am I missing something? Or not been released with this feature yet?

**Comment by Anonymous2716** [comment]
I've noticed that I'm not up to dated then I installed from fdroid again v2.0.4 but still the we settings. And when exporting the Avncconfig.json it exported a 0 byte file on v.2.0.0

```
-rw-rw---- 1 root everybody 0 Jan 24 00:29 'AVNC-Export-1674498547552 Jan 24, 2023.json'
```

**Comment by gujjwal00** [comment]
Raw image quality can be set for individual servers, available in advanced server option. 

2.0.0 had a bug in server exports. It was fixed in https://github.com/gujjwal00/avnc/releases/tag/v2.0.2

**Comment by Anonymous2716** [comment]
Found it thanks. And you might wanna checkout the export/import issue then. Should I close this issue?
