### ISSUE TITLE
View moves off the screen when swiping

### ISSUE THREAD

**Issue by tuanpham-dev** [gujjwal00/avnc#133]
Upgrade AVNC today and I got this issue. You can see in the video when I swipe left and right the view moves left and right too. It stops moving once it moves right.

https://user-images.githubusercontent.com/48458487/216374854-07ee4a59-781c-4c08-b733-cfae4e4d7b3a.mp4

**Comment by gujjwal00** [comment]
This is probably a result of https://github.com/gujjwal00/avnc/commit/6cfa44dc949d2f27cc3c454579d0c9a8fa7f7191.
Does your device has rounded corners?

**Comment by tuanpham-dev** [comment]
Yes and the notch.

**Comment by gujjwal00** [comment]
This patch allowed the frame to pan out of rounded corners. I implemented it considering phones. In retrospect, this was probably not the right decision. I have already received a report on Play Store. I will revert the handling of rounded corners in next release.

I swear, v2.x.x series is cursed 😞. Not a single release in this series has gone smoothly.

**Comment by babaric-dev** [comment]
Same here.

**Comment by tuanpham-dev** [comment]
No worries! Keep up your good work!

Thank you for reversing the update! It's working now.
