### ISSUE TITLE
Unused strings?

### ISSUE THREAD

**Issue by babaric-dev** [gujjwal00/avnc#136]
I am translating AVNC to Trad. Chinese. I noticed a few seemingly unused strings:
- `pref_toolbar_alignment`
- `pref_toolbar_alignment_option_start`
- `pref_toolbar_alignment_option_end`

I will update this issue if I find more unused ones.

**Comment by gujjwal00** [comment]
These are used at **Settings - Viewer - Toolbar Alignment**

**Comment by babaric-dev** [comment]
Oh. Sorry for that.
