### ISSUE TITLE
Feature Request: Drag with One-finger Swipe

### ISSUE THREAD

**Issue by railgauge** [gujjwal00/avnc#137]
When using VNC to remote into KDE Plasma Mobile, the existing AVNC "Drag" input must be used to navigate the UI. It is not convenient to press, hold, then swipe for every interaction, therefore it is requested that the already existing "Drag" function is added as an additional option for the "One-finger swipe" input method. 

With this feature added, the Plasma Mobile UI interaction would be akin to native navigation where one can swipe through home pages and app drawers, etc...

**Comment by gujjwal00** [comment]
Added in https://github.com/gujjwal00/avnc/commit/68af560709bed8469c8474923818fbbed16419de

Test APK: https://github.com/gujjwal00/avnc/suites/11059699996/artifacts/562289856

There is a small issue with fling gesture interfering with dragging, but it will be fixed before next version is released.

**Comment by railgauge** [comment]
Thanks, the test APK works well; navigation is much easier now.

**Comment by gujjwal00** [comment]
[v2.2.0](https://github.com/gujjwal00/avnc/releases/tag/v2.2.0) is now available with drag support.
