### ISSUE TITLE
Word wrap needed in server list

### ISSUE THREAD

**Issue by user8446** [gujjwal00/avnc#140]
After "Show SSH host address in server list" commit: https://github.com/gujjwal00/avnc/commit/7ef81be40648b9ee3114ade27f606e02043d331f and there is a lengthy domain, the line gets cut off. Maybe a word wrap would be best here?

![Screenshot_20230213-222854 (2)](https://user-images.githubusercontent.com/18019245/218634061-1563845c-3782-41ca-8614-f41502d44b15.jpg)

**Comment by gujjwal00** [comment]
Fixed in https://github.com/gujjwal00/avnc/commit/ae31db2d3157505f188cf01560b8e6830dec59b5

When space is limited, middle part of SSH host will be ellipsized.

**Comment by user8446** [comment]
Great solution!
