### ISSUE TITLE
could not connect raspberry pi 

### ISSUE THREAD

**Issue by Jiangshan00001** [gujjwal00/avnc#143]
I do not know why, connect to raspberry pi server is an error:

--------- beginning of main
02-22 15:16:43.911 12103 12398 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=407510, DequeueBufferDuration=947448, forgiveAmount=407510, totalDuration=16493469
02-22 15:16:44.663 12103 12398 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2229592, DequeueBufferDuration=3709896, forgiveAmount=2229592, totalDuration=5643836
02-22 15:16:44.679 12103 12398 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2767772, DequeueBufferDuration=3565937, forgiveAmount=2767772, totalDuration=4901696
02-22 15:16:45.726 12103 12119 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=870464, DequeueBufferDuration=3403125, forgiveAmount=870464, totalDuration=9419490
02-22 15:16:45.742 12103 12119 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2372512, DequeueBufferDuration=2404010, forgiveAmount=2372512, totalDuration=5019403
02-22 15:16:45.759 12103 12119 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1342885, DequeueBufferDuration=1230729, forgiveAmount=1230729, totalDuration=5749147
02-22 15:16:45.775 12103 12119 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1669275, DequeueBufferDuration=605209, forgiveAmount=605209, totalDuration=5643277
02-22 15:16:46.059 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2584166, DequeueBufferDuration=9552448, forgiveAmount=2584166, totalDuration=10578542
02-22 15:16:46.075 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2986219, DequeueBufferDuration=2044479, forgiveAmount=2044479, totalDuration=2486645
02-22 15:16:46.092 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2924054, DequeueBufferDuration=2575521, forgiveAmount=2575521, totalDuration=1996207
02-22 15:16:46.109 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=3077879, DequeueBufferDuration=1922916, forgiveAmount=1922916, totalDuration=1821549
02-22 15:16:46.125 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2276953, DequeueBufferDuration=1479687, forgiveAmount=1479687, totalDuration=2933829
02-22 15:16:46.142 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2686313, DequeueBufferDuration=1607552, forgiveAmount=1607552, totalDuration=2295927
02-22 15:16:46.159 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2824786, DequeueBufferDuration=1728021, forgiveAmount=1728021, totalDuration=2794068
02-22 15:16:46.175 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=3303360, DequeueBufferDuration=2090729, forgiveAmount=2090729, totalDuration=2038463
02-22 15:16:46.193 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2628991, DequeueBufferDuration=2337292, forgiveAmount=2337292, totalDuration=2925644
02-22 15:16:46.209 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2474351, DequeueBufferDuration=1525156, forgiveAmount=1525156, totalDuration=2748878
02-22 15:16:46.226 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2074427, DequeueBufferDuration=2135729, forgiveAmount=2074427, totalDuration=4737500
02-22 15:16:46.242 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1375834, DequeueBufferDuration=1207031, forgiveAmount=1207031, totalDuration=5397396
02-22 15:16:46.260 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1841182, DequeueBufferDuration=1768229, forgiveAmount=1768229, totalDuration=5107620
02-22 15:16:46.278 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1812858, DequeueBufferDuration=1361042, forgiveAmount=1361042, totalDuration=4807611
02-22 15:16:46.296 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1078581, DequeueBufferDuration=1639687, forgiveAmount=1078581, totalDuration=6657474
02-22 15:16:46.543 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2271994, DequeueBufferDuration=2479167, forgiveAmount=2271994, totalDuration=4471480
02-22 15:16:46.560 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2419449, DequeueBufferDuration=1892605, forgiveAmount=1892605, totalDuration=3463520
02-22 15:16:48.377 12103 12103 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/12103/rtg
02-22 15:16:48.377 12103 12103 E RtgSchedIpcFile: setCommandByIoctl not opened
02-22 15:16:48.646 12103 12103 E RtgSchedIpcFile: RtgSchedIpcFile failed to open /proc/12103/rtg
02-22 15:16:48.646 12103 12103 E RtgSchedIpcFile: setCommandByIoctl not opened
02-22 15:16:56.760 12103 12121 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2683582, DequeueBufferDuration=6539739, forgiveAmount=2683582, totalDuration=7227836
02-22 15:16:56.780 12103 12121 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2193990, DequeueBufferDuration=2809271, forgiveAmount=2193990, totalDuration=3807593
02-22 15:16:56.794 12103 12121 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2224041, DequeueBufferDuration=2875885, forgiveAmount=2224041, totalDuration=4382126
02-22 15:16:58.212 12103 12119 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=330506, DequeueBufferDuration=1525781, forgiveAmount=330506, totalDuration=22290029
02-22 15:16:58.231 12103 12121 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=3000640, DequeueBufferDuration=1309010, forgiveAmount=1309010, totalDuration=2870350
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine: Connection failed
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine: java.io.IOException: Authentication failed
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at com.gaurav.avnc.vnc.VncClient.connect(VncClient.kt:2)
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at com.gaurav.avnc.viewmodel.VncViewModel.access$connect(VncViewModel.kt:68)
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at com.gaurav.avnc.viewmodel.VncViewModel$launchConnection$1.invokeSuspend(VncViewModel.kt:8)
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
02-22 15:16:58.656 12103 12158 E ReceiverCoroutine:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
02-22 15:17:01.546 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2077271, DequeueBufferDuration=1867604, forgiveAmount=1867604, totalDuration=4491739
02-22 15:17:01.565 12103 12398 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2593638, DequeueBufferDuration=1964427, forgiveAmount=1964427, totalDuration=3870111
02-22 15:17:02.861 12103 12119 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=252227, DequeueBufferDuration=2531354, forgiveAmount=252227, totalDuration=10576796
02-22 15:17:02.879 12103 12119 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=747748, DequeueBufferDuration=1085573, forgiveAmount=747748, totalDuration=6375857
02-22 15:17:02.979 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2273276, DequeueBufferDuration=3663802, forgiveAmount=2273276, totalDuration=4967666
02-22 15:17:02.979 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1847686, DequeueBufferDuration=1753646, forgiveAmount=1753646, totalDuration=3906011
02-22 15:17:03.027 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=603825, DequeueBufferDuration=1625156, forgiveAmount=603825, totalDuration=4942507
02-22 15:17:03.044 12103 12398 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=677831, DequeueBufferDuration=1972083, forgiveAmount=677831, totalDuration=5093505
02-22 15:17:03.061 12103 12398 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=239475, DequeueBufferDuration=1474584, forgiveAmount=239475, totalDuration=5509748
02-22 15:17:03.311 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2605663, DequeueBufferDuration=3488230, forgiveAmount=2605663, totalDuration=3793517
02-22 15:17:04.342 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=3060753, DequeueBufferDuration=2084583, forgiveAmount=2084583, totalDuration=2066955
02-22 15:17:04.358 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2896147, DequeueBufferDuration=2019479, forgiveAmount=2019479, totalDuration=2501770
02-22 15:17:04.374 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2890964, DequeueBufferDuration=1454636, forgiveAmount=1454636, totalDuration=2543619
02-22 15:17:04.391 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=3067987, DequeueBufferDuration=1567500, forgiveAmount=1567500, totalDuration=2247794
02-22 15:17:04.408 12103 12144 E OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2975124, DequeueBufferDuration=1270833, forgiveAmount=1270833, totalDuration=2528992

**Comment by gujjwal00** [comment]
Seems to be an authentication issue. You can look at #7 , #97 , #124 for possible workarounds.

**Comment by Jiangshan00001** [comment]
thanks @gujjwal00

**Comment by Jiangshan00001** [comment]
sudo nano /root/.vnc/config.d/vncserver-x11
and add the following line at the end of the file:

Authentication=VncAuth

this will fix the error.
