### ISSUE TITLE
a long touch

### ISSUE THREAD

**Issue by song-73** [gujjwal00/avnc#146]
**Description**

It doesn't recognize the touch for a long time.

**Additional Info**
- App Version: 2.1.2 (22)
- Android Version: 13 (33)

**Comment by gujjwal00** [comment]
Are you talking about all touch gestures, or just about the `Long press`?
Please also attach a screenshot of your gesture settings **(AVNC Settings => Input)**.

**Comment by song-73** [comment]
Did I set it up wrong? 
It works when you use your smartphone and press the icon (switch) on the screen for more than 1 second, but it doesn't work. 
Other icons (switches) work well regardless of the length of the installation. 

 Thank you for the quick...



-----Original Message-----

**Comment by gujjwal00** [comment]
Sorry, I am still not 100% sure which portion of the app you are talking about.
Are you facing issue with one of these:

![image](https://user-images.githubusercontent.com/27951674/222354543-bac61e5c-74c2-45e5-bcf4-017097557e15.png)

**Comment by song-73** [comment]
There must have been a lack of explanation.

There is a button that you need to remotely access and press and hold the icon on the screen

Touch is not working in the app..

The button works well if you press it short.
The button that needs to be pressed for a long second doesn't work.

Is there any option to press and hold on the phone in the settings..

If the setting goes into input, there is a long press and I don't know what double click, middle click, right click means....

ㅠㅠ
-----Original Message-----

**Comment by gujjwal00** [comment]
Ah! I understand the issue now.
There are two possible ways to long-press a button on the server:

1. Using double tap and swipe
    - Double tap on the button, but don't lift up the finger after second tap. 
    - Slightly move the finger, while keeping it on the button
    - Button should be activated now.
2.  Using long-press and swipe
    - Go to **Settings => Input** in AVNC
    - Set `Long press and swipe` to `Drag remote content` 
    - Go back and connect to your server
    - Long-press on the button (you should feel the haptic feedback)
    - Slightly move the finger, while keeping it on the button
    - Button should be activated now.

**Comment by gujjwal00** [comment]
Has your issue been resolved @song-73 ?

**Comment by song-73** [comment]
Hi, buddy. The problem that the remote touch does not work by pressing the button for a long time is not solved. I've tried what you explained and it really works sometimes. Go to Settings and push remote content is on tap and push twice. The long push and push looks like a mouse button setting.


-----Original Message-----

**Comment by gujjwal00** [comment]
Can you post a screenshot or screen recording of the issue?
Details about your VNC server (name and version), OS etc. would also be helpful.

**Comment by gujjwal00** [comment]
Closing this, feel free to reopen if you have more details about the issue.
