### ISSUE TITLE
Key up events for modifier keys are not sent on exit

### ISSUE THREAD

**Issue by thechosenreader** [gujjwal00/avnc#15]
The virtual keyboard sends the keydown and keyup events for `Shift`, `Ctrl`, and `Alt` separately. 

This makes it possible for a user to send the keydown event for a modifier and then exit before sending the keyup. 

On my computer (KDE neon 5.22, X server 1.20.9, kernel 5.4.0-77-generic), this results in all input events being handled as if those modifier keys were pressed. I can only fix it by manually sending the keyup event for the correct modifier key.

I have created a pull request that solves this by dispatching the keyup events for Shift_R, Control_R, and Alt_R in VncActivity.onStop.

**Comment by gujjwal00** [comment]
Thanks for this. I am working on a similar issue too, where mouse buttons are not released properly in some edge cases.
I will review the PR later today.
