### ISSUE TITLE
Feature request: Allow rearranging servers on list

### ISSUE THREAD

**Issue by barkoder** [gujjwal00/avnc#151]
Currently new servers get added to the bottom of the list. But I want them close to some other server.

Currently I'm having to export the servers to json and manually edit the `ID` accordingly, and re-import it to rearrange the list of servers.

It would be great if there was an option to rearrange them.

Thanks!

**Comment by gujjwal00** [comment]
Sorry, but is not something I am going to implement. It was also suggested in #4. As I said then, it requires a lot of work, and the natural gesture to trigger re-ordering (long-press) is already used for context menu.

You don't have manually edit ID though. You can enable `Settings =>  Interface => Sort saved servers by name` and name your servers accordingly (e.g. start them with a number).

**Comment by barkoder** [comment]
> It was also suggested in #4. 

Sorry should have checked for dupes. My bad.

>You can enable `Settings =>  Interface => Sort saved servers by name`

Okay that's good enough. Thanks!
