### ISSUE TITLE
Feature: import/export settings

### ISSUE THREAD

**Issue by babaric-dev** [gujjwal00/avnc#153]
We can import and export VNC servers. Why not app settings?

**Comment by gujjwal00** [comment]
Before AVNC was released, I did try to include settings in import/export. But the `SharedPreferences` API was very limiting for this task. Its not really designed for bulk get/set, and required manual handling of different values and types. There is no version handling built-in, so ensuring some forward/backward compatibility requires extra work. Compared to this, server database is well modeled, version based, and well supported by serialization library.

That was the original reason. Now some settings are more complex. We have stuff like `Servers => Lock saved servers`, which involves user verification. There are couple of transient settings not exposed via UI. So adding import/export is even less desirable now.
