### ISSUE TITLE
Bug: cannot translate text

### ISSUE THREAD

**Issue by babaric-dev** [gujjwal00/avnc#155]
![Screenshot_20230313_093642_AVNC](https://user-images.githubusercontent.com/104625126/224589075-1afe07e4-d5f0-4e1f-8071-b8870f5de870.jpg)
We cannot translate the message because it seems to be hard coded in English.
Location of string: Settings → Viewer → (scroll to bottom)
```
Show gesture style toggle
```

**Comment by gujjwal00** [comment]
I usually hard code strings if they are supposed to be temporary/experimental. If you guys don't mind translating, I can put these in `strings.xml` to allow translation.

**Comment by babaric-dev** [comment]
Idea: maybe add a section for experimental settings?

**Comment by gujjwal00** [comment]
There _was_ an experimental section:

<img width="200" src="https://user-images.githubusercontent.com/27951674/224597146-25775e4c-f7cb-4a59-a681-b970c46a466f.png" />

One issue was that it grouped a bunch of unrelated settings together, so experience was not good. Now I put experimental settings near other related options.

I have to clarify one thing though: Even experimental stuff is only hard coded if string is likely to be deleted in next or second next version. If I end retaining/stabilizing the setting, I will move it to `strings.xml`.
