### ISSUE TITLE
Bug: black screen sometimes

### ISSUE THREAD

**Issue by babaric-dev** [gujjwal00/avnc#156]
Sometimes when logging in a server, it shows a black screen. It seems to occur randomly.

**Comment by gujjwal00** [comment]
Yeah, that happened for me too with TigerVNC. Next time it happens, please post the logs from AVNC.

**Comment by babaric-dev** [comment]
I don't want to post the full logcat but which part in the logs are relevant to this issue?

**Comment by gujjwal00** [comment]
I want to know if the receiver thread has crashed. Usually there is a stack trace in the logs.

BTW, AVNC can't access full logcat. It only shows logs created by itself.

**Comment by gujjwal00** [comment]
After some testing, I am about 80% sure this is a bug in TigerVNC. If you disable clipboard sharing in AVNC Settings, you will be able to trigger it more reliably.

It feels like a race-condition. When extended clipboard is enabled, TigerVNC sometimes drops the initial framebuffer update request. So client ends up waiting for update, while server is waiting for update request.

**Comment by gujjwal00** [comment]
TigerVNC is working correctly. This bug is causes by buffering in LibVNCClient.
Please try the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/11015772/app-debug.zip)

**Comment by yuanjv** [comment]
> TigerVNC is working correctly. This bug is causes by buffering in LibVNCClient. Please try the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/11015772/app-debug.zip)

yes, this version 100% fixed the random black screen for me.
btw, will you include this fix on the next release?

**Comment by gujjwal00** [comment]
Thanks for testing @yuanjv . Yes, it will be included in next release.

**Comment by yuanjv** [comment]
great

**Comment by gujjwal00** [comment]
v2.2.1 is now available with this fix.
