### ISSUE TITLE
The client doesn't send cedilla to the server.

### ISSUE THREAD

**Issue by Will200381** [gujjwal00/avnc#159]
**Description**

The client doesn't send cedilla to the server.

**Additional Info**
- App Version: 2.1.2 (22)
- Android Version: 12 (31)

**Comment by gujjwal00** [comment]
Can you tell me a bit more about your setup:
- Which VNC server (name & version) are you using
- Are you sharing text via clipboard, or typing on a hardware keyboard
- Do other characters work correctly

**Comment by Will200381** [comment]
Package: tigervnc
Version: 1.10.1-37
Maintainer: @termux
Installed-Size: 3740 kB
Depends: libandroid-shmem, libc++, libgnutls, libjpeg-turbo, libpixman,
libx11, libxau, libxdamage, libxdmcp, libxext, libxfixes, libxfont2,
opengl, openssl, perl, xkeyboard-config, xorg-xauth, xorg-xkbcomp, zlib
Suggests: aterm, xorg-twm
Homepage: https://tigervnc.org/
Download-Size: 951 kB
APT-Manual-Installed: yes
APT-Sources: https://mirror.fcix.net/termux/termux-x11 x11/main aarch64
Packages
Description: Suite of VNC servers. Based on the VNC 4 branch of TightVNC.

I'm typing on a software keyboard

The other characters work correctly


Em ter., 28 de mar. de 2023 10:47, Gaurav Ujjwal ***@***.***>
escreveu:

**Comment by gujjwal00** [comment]
Please go to `Settings => Tools => Key test` in AVNC. Type the character which is not working (and couple of characters which are working). Now copy event log and paste it here.

**Comment by Will200381** [comment]
<details>
<summary>Teste de teclado</summary>
<p>

```python
KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_ALT_LEFT, scanCode=0,
metaState=META_ALT_ON|META_ALT_LEFT_ON, flags=0x0, repeatCount=0,
eventTime=20197643, downTime=20197643, deviceId=-1, source=0x101,
displayId=-1 }
KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_C, scanCode=0,
metaState=META_ALT_ON|META_ALT_LEFT_ON, flags=0x0, repeatCount=0,
eventTime=20197643, downTime=20197643, deviceId=-1, source=0x101,
displayId=-1 }
KeyEvent { action=ACTION_UP, keyCode=KEYCODE_C, scanCode=0,
metaState=META_ALT_ON|META_ALT_LEFT_ON, flags=0x0, repeatCount=0,
eventTime=20197643, downTime=20197643, deviceId=-1, source=0x101,
displayId=-1 }
KeyEvent { action=ACTION_UP, keyCode=KEYCODE_ALT_LEFT, scanCode=0,
metaState=0, flags=0x0, repeatCount=0, eventTime=20197643,
downTime=20197643, deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_G, scanCode=0, metaState=0,
flags=0x0, repeatCount=0, eventTime=20207290, downTime=20207290,
deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_UP, keyCode=KEYCODE_G, scanCode=0, metaState=0,
flags=0x0, repeatCount=0, eventTime=20207290, downTime=20207290,
deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_W, scanCode=0, metaState=0,
flags=0x0, repeatCount=0, eventTime=20210940, downTime=20210940,
deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_UP, keyCode=KEYCODE_W, scanCode=0, metaState=0,
flags=0x0, repeatCount=0, eventTime=20210940, downTime=20210940,
deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_MULTIPLE, keyCode=KEYCODE_UNKNOWN, scanCode=0,
characters="ž", metaState=0, flags=0x0, repeatCount=0, eventTime=20216022,
downTime=20216022, deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_MULTIPLE, keyCode=KEYCODE_UNKNOWN, scanCode=0,
characters="ñ", metaState=0, flags=0x0, repeatCount=0, eventTime=20218751,
downTime=20218751, deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_MULTIPLE, keyCode=KEYCODE_UNKNOWN, scanCode=0,
characters="μ", metaState=0, flags=0x0, repeatCount=0, eventTime=20221080,
downTime=20221080, deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_MULTIPLE, keyCode=KEYCODE_UNKNOWN, scanCode=0,
characters="§", metaState=0, flags=0x0, repeatCount=0, eventTime=20233547,
downTime=20233547, deviceId=-1, source=0x101, displayId=-1 }
KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=0,
metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x0, repeatCount=0,
eventTime=20242348, downTime=20242348, deviceId=-1, source=0x101,
displayId=-1 }
KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_A, scanCode=0,
metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x0, repeatCount=0,
eventTime=20242348, downTime=20242348, deviceId=-1, source=0x101,
displayId=-1 }
KeyEvent { action=ACTION_UP, keyCode=KEYCODE_A, scanCode=0,
metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x0, repeatCount=0,
eventTime=20242348, downTime=20242348, deviceId=-1, source=0x101,
displayId=-1 }
KeyEvent { action=ACTION_UP, keyCode=KEYCODE_SHIFT_LEFT, scanCode=0,
metaState=0, flags=0x0, repeatCount=0, eventTime=20242348,
downTime=20242348, deviceId=-1, source=0x101, displayId=-1 }


Preview text: çgwžñμ§A

```

</p>
</details>

Em seg., 3 de abr. de 2023 23:27, Gaurav Ujjwal ***@***.***>
escreveu:

**Comment by gujjwal00** [comment]
So the issue here is how Android generates event for `ç`:
 - Left Alt down
 - C down
 - C up
 - Left alt up

If you test with `xev` on server, you will see that AVNC forwards all events as expected.
But it doesn't work, because server expects a single `ç` event, and not `Alt_Left` + `ç`. `ž` and `ñ` don't generate extra `Alt` event, so they work as expected.

Given this situation, I doubt any other VNC client will work either.

**Comment by Will200381** [comment]
Sorry to disagree with you, but RealVNC Client works.

Em sex., 7 de abr. de 2023 03:03, Gaurav Ujjwal ***@***.***>
escreveu:

**Comment by gujjwal00** [comment]
RealVNC client has probably found a workaround for this.

**Comment by gujjwal00** [comment]
I finally had some time to look at this, and I have a possible workaround. If you are still using AVNC 😀, you can test the following APK to see if it works in your case: https://github.com/gujjwal00/avnc/actions/runs/7767205642/artifacts/1217378319 

cc @allytiago

**Comment by Will200381** [comment]
Thank you very much for your consideration, but i don't need it anymore.
________________________________
De: Gaurav Ujjwal ***@***.***>
Enviado: sábado, 3 de fevereiro de 2024 10:36
Para: gujjwal00/avnc ***@***.***>
Cc: Will200381 ***@***.***>; Author ***@***.***>
Assunto: Re: [gujjwal00/avnc] The client doesn't send cedilla to the server. (Issue #159)


I finally had some time to look at this, and I have a possible workaround. If you are still using AVNC 😀, you can test the following APK to see if it works in your case: https://github.com/gujjwal00/avnc/actions/runs/7767205642/artifacts/1217378319

cc @allytiago<https://github.com/allytiago>

**Comment by gujjwal00** [comment]
No problem, have a good day :)
