### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by HilmiRidho** [gujjwal00/avnc#161]
very smooth I see speeds of over 70mbps, but I get more fps when running glxgears in tightvnc viewer (from android to pc). Is this because the performance depends on the cpu?
on pc : 440fps+ (using usb tethering)
on android : 180fps+

**Comment by gujjwal00** [comment]
Where is your VNC server running: PC or Android?
Are VNC server & AVNC running on same device?

**Comment by HilmiRidho** [comment]
vnc server run on android chroot

**Comment by HilmiRidho** [comment]
yes, using the same device, namely android (localhost) and using a pc (usb tethering android to pc, faster than wireless)

**Comment by gujjwal00** [comment]
If AVNC and VNC server are running on same device, that might explain the lower FPS. Both AVNC and glxgears will be competing for the same CPU/GPU, and the scheduler is likely to give priority to AVNC as it will be in foreground.

Side note: I am assuming the 440/180 number is coming from glxgears. The "actual" FPS in AVNC (i.e. how frequently AVNC renders the contents received  form  server) will be capped to to your screen refresh rate.
