### ISSUE TITLE
Feature request: Open app and connect to specific address through ADB

### ISSUE THREAD

**Issue by KodzghlyCZ** [gujjwal00/avnc#162]
Hi

I'm making an automated script to run X11VNC server on my machine and then automatically run AVNC connecting to localhost on specific port. I was trying several things, but none of them work. 
If there's some way to run the app through ADB with it directly connecting, please let me know, thanks <3

**Comment by gujjwal00** [comment]
Yes, you can start AVNC from ADB. AVNC supports `vnc://` URIs, which can be used to directly connect to a server.

Suppose the IP address of your machine is `192.168.226.208`. You can do something like this to start connection:
```bash
adb shell am start 'vnc://192.168.226.208'
``` 

You can also directly launch servers saved in AVNC:
```bash
adb shell am start 'vnc://?ConnectionName=Foo'
``` 
where `Foo` is the name of server saved in AVNC.
 
More details about `vnc://` URIs: https://www.rfc-editor.org/rfc/rfc7869.html
