### ISSUE TITLE
Feature request: Touchpad mouse "deadzone"

### ISSUE THREAD

**Issue by Marisa-Chan** [gujjwal00/avnc#166]
**Description**
It's really great work, but what I want is ability for mouse "not be in center" of zoomed screen when it in "touchpad" mode. It's something like rectangle area(in percent) in center of screen where movement of cursor will do not cause scroll zoomed screen. 

Also will really like to see option for rearrange or enable/disable for additional keyboard keys panel, to enable only wanted (or may be hot keys shortcuts too)

**Additional Info**
- App Version: 2.2.1 (24)
- Android Version: 10 (29)

**Comment by gujjwal00** [comment]
> It's really great work, but what I want is ability for mouse "not be in center" of zoomed screen when it in "touchpad" mode. It's something like rectangle area(in percent) in center of screen where movement of cursor will do not cause scroll zoomed screen.

Glad to know you like AVNC. Unfortunately, what you are describing is a very specific issue (and probably complicated to implement).

I would suggest you to use dynamic gesture styles. Go to `Settings => Viewer => Toolbar` and enable `Show gesture style button`. Now you can change gesture style directly from toolbar drawer, without disconnecting from server. Just switch to `Touchscreen` mode when you want the screen to stay still.

> Also will really like to see option for rearrange or enable/disable for additional keyboard keys panel, to enable only wanted (or may be hot keys shortcuts too)

While fully configurable keys are not on my roadmap, I am hoping to implement different "layouts" someday. For now my advice is to use dedicated apps like 'Hacker's Keyboard' for best experience.

PS: Sorry for late response.
