### ISSUE TITLE
Feature request : be able to customize further more the gestures and controls

### ISSUE THREAD

**Issue by pierreduf** [gujjwal00/avnc#174]
Hello ! 

I'm wondering how much of work would be needed to have more ways to customize the gesture and controls.

I'm using your app with termux to launch linux games and that's working great, many thanks ! But for a specific game, I'd like to emulate kind of "mobile app" controls, that means : 

- use pinch to zoom to trigger a mouse wheel scroll up and down (zoom content) : today, only two-finger swipe can do that (no the same thing as pinch to zoom)
- use one tap + drag to emulate to move game content : in my game it does not correspond to a left click + drag (that would be too easy  :)) but to a middle click + drag

Of course, for other apps and other games those controls could be different so I'd like to have a way to modify control and gestures with possibly any combinations I want (input being one tap, double tap, tap + swipe and output being whatever click need + drag or not etc...)

Is there any possibility to customize those controls/gestures without heavily modifying you code ? Maybe leave the preferences as it is today but be able to customize further with a config file or something like that ?

That would be a real + versus other vnc clients which are already much more limite than yours !

**Comment by pierreduf** [comment]
Just seen that you've documented really well your code thanks ! But I'll be happy to have some guidance from you if you think those modifications are not too complicated to do

![image](https://github.com/gujjwal00/avnc/assets/4528088/94724656-11f0-4bf6-935a-ae087254cfba)

**Comment by gujjwal00** [comment]
Hi @pierreduf , sorry for not responding sooner, I am just catching up with my backlog after a long hiatus.


> * use one tap + drag to emulate to move game content : in my game it does not correspond to a left click + drag (that would be too easy  :)) but to a middle click + drag

Dragging with middle button is already possible with double-tap-and-swipe or long-press-and-swipe gestures.

> Of course, for other apps and other games those controls could be different so I'd like to have a way to modify control and gestures with possibly any combinations I want (input being one tap, double tap, tap + swipe and output being whatever click need + drag or not etc...)
> 
> Is there any possibility to customize those controls/gestures without heavily modifying you code ? Maybe leave the preferences as it is today but be able to customize further with a config file or something like that ?

No, AVNC doesn't have any more config options, other than those available in Input Settings. But, IMHO, AVNC is not the right place to customize the input in the way you want. You will find [more](https://wiki.archlinux.org/title/Mouse_buttons) options to remap buttons on Linux side, which might work depending of currently active window.
