### ISSUE TITLE
Screen can not go to sleep state

### ISSUE THREAD

**Issue by ken1901** [gujjwal00/avnc#178]
Hi,

Thanks for your great work. I have an issue that screen does not go to sleep state after letting idle for long hours. Can I somehow enable screen timeout?

Regards,

Ken

**Comment by gujjwal00** [comment]
Hi @ken1901 , sorry for late response.
[v2.3.0](https://github.com/gujjwal00/avnc/releases/tag/v2.3.0) is now available with an option to disable screen wakelock (in Viewer settings).
