### ISSUE TITLE
Connect to a server while already connected (running in Picture-in-picture mode) would open a new session instead of resume the old one

### ISSUE THREAD

**Issue by RadarNyan** [gujjwal00/avnc#179]
I'm using UltraVNC as server and configured as: max viewers 1 & disconnect oldest.

When connected to the server and switch to other apps (thus making the session continue visible in Android Picture-in-picture mode) then switch back to avnc, trying to connect to the same server again would result in the PiP window session disconnect and a new session is opened to the server.

If the server is configured as max viewers 1 & refuse new connection, repeat the steps above would result in fail to connect while the session in PiP window continue to work.

The desired behavior would be resume the existing session instead of opening two sessions to the same server.

**Comment by gujjwal00** [comment]
Hi @RadarNyan , sorry for late reply but this is working as intended. 
Once a session/activity enters Picture-In-Picture, it cannot exit automatically without user action. There _is_ a way to force single session/activity using `singleTask` mode, but it limits us to one session even if you go back and click on a different server. And right now, AVNC doesn't support this mode anyway.
