### ISSUE TITLE
"Shift" can't work in keyboard hotkey/shortcuts

### ISSUE THREAD

**Issue by babaolanqiu** [gujjwal00/avnc#18]
When I try to use Shift in any keyboard shortcuts, it seems to be recognized as a capital letter modifier first. For example, when I try to use "Ctrl+Shift+K" in VScode, it goes into "Ctrl+K Ctrl+Shift+". I tried another VNC viewer and Shift can perform functionally in that.

**Comment by gujjwal00** [comment]
Can you tell me which VNC server and OS you are using?

**Comment by babaolanqiu** [comment]
VNC: Xvnc TigerVNC 1.8.0
OS: CentOS Linux release 7.4.1708 (Core) Linux 3.10.0-693.el7.x86_64

**Comment by gujjwal00** [comment]
Can you please try the APK i am attaching here?
[app-debug.zip](https://github.com/gujjwal00/avnc/files/7612100/app-debug.zip)

**Comment by babaolanqiu** [comment]
Shift works properly now! Thanks👍( while mouse passthrough seems not configured 'cause there are two mouse cursers now)

**Comment by gujjwal00** [comment]
> while mouse passthrough seems not configured 'cause there are two mouse cursers now

If you want to hide the remote cursor, you can edit the server profile and turn on 'Hide Remote Cursor' in Advanced options (OR are you having a different issue?)

**Comment by babaolanqiu** [comment]
I mean when I connect to the same server, AVNC 1.2.0 and VNC viewer by RealVNC show only the local cursor, but this debug version shows two cursors.

**Comment by gujjwal00** [comment]
That's weird, I have not changed anything related to cursor recently. I will take a look.

Can you please also double check that 'Hide Remote Cursor' is indeed turned on in debug version?

**Comment by babaolanqiu** [comment]
My bad, I thought it's by default turned on so I didn't check it. Now everything is cool, thanks!

**Comment by gujjwal00** [comment]
Great. Thanks for reporting this issuing.
