### ISSUE TITLE
Always-onscreen keyboard bar

### ISSUE THREAD

**Issue by domportera** [gujjwal00/avnc#181]
Firstly, thank you a million for this app. I've been looking for an open source alternative to the Remotix app and no one has ever even come close until yours, and I've looked regularly for a long time. Amazing work, I've officially uninstalled it and haven't looked back

But anyway one thing that'd be really great and cool and epic would be an option to keep that bottom keyboard row on screen at all times. I'm always reaching for it and it would be nice to just keep it there

**Comment by gujjwal00** [comment]
Glad you find AVNC useful! I have tried to make it as seamless as possible.

There is already an option to automatically open "virtual keys" with the soft-keyboard (`Settings => Input => Virtual keys`). But if you are talking about showing them when connection is started, that can be implemented too.

**Comment by domportera** [comment]
I do have that option checked, i just would like it on screen by default. Bonus points for an option to have a "show keyboard" button on there too ;)

**Comment by gujjwal00** [comment]
I will change the `Open with keyboard` option to a list with three options: Open manually, Open automatically, and Open with keyboard.

**Comment by domportera** [comment]
perfect thanks so much!

**Comment by AtmanActive** [comment]
Hi,

Thank you very much for developing this awesome software.

While we're on the subject of on-screen keyboard and when and how to open it, I just wanted to share my experience here:
- when I'm using AVNC on my phone, for quick sessions, then, the two-finger-tap to open keyboard works well, although I do need to tap and tap and tap to get it right (maybe this action could be backed up by a hardware key, volume-up or volume-down or something)
- when I'm using AVNC on my tablet, which has a mouse attached to it, for longer sessions, then, I always need android keyboard + virtual keyboard open, so I find myself two-finger-tap-tapping all the time and then I realized that it would be super useful if we could have a global option "auto open keyboard on session start"

So I found this thread and figured, best to join in here.

Thanks.

AVNC rocks!

**Comment by denilsonsa** [comment]
Although a slightly different request, it's still similar enough that I'm going to share my feedback here.

When using a tablet with a thick and strong case, it's really hard to swipe from the edge of the device, as the case goes around the screen. Thus, it takes too many tries to open the sidebar.

I would suggest to incorporate the sidebar buttons into the keyboard bar. Being able to quickly toggle the touchscreen/touchpad behavior without accidentally moving the mouse cursor would be very welcome.

Likewise, it would be nice to have virtual buttons for scrolling up/down and middle-click.

I would like to have the keyboard bar always visible.

I understand this isn't the original request of this issue, but it's related and I didn't want to open another issue for something so similar. (Also, I typed this on AVNC with touch keyboard and a laggy VNC connection.)

**Comment by gujjwal00** [comment]
Hi all, a bit late, but next version will contain many improvements related to virtual keys:
- Two-row layout, similar to Termux
- Dedicated button to toggle Android soft-keyboard
- Persistence of visibility across sessions: Once opened, virtual keys will continue to automatically open  on each connection (same goes for closing them)
- Other changes like a textbox to allow full-fledged editing experience, and long-press to 'lock' meta keys

Preview:
![image](https://github.com/gujjwal00/avnc/assets/27951674/cbe5482f-a339-42bf-8d78-b7922bd7a993)


Test APK: https://github.com/gujjwal00/avnc/actions/runs/9303532905/artifacts/1552524465

**Comment by domportera** [comment]
oh this is lovely, just tried it! Thank you so much - I've actually since switched back to Remotix because of these issues and I am happy to come back with these changes :)

**Comment by gujjwal00** [comment]
Great! I had hoped to implement these sooner but couldn't get enough free time to properly fix all of these (re #117 , #187) .

**Comment by bcm314** [comment]
Two-row layout is great, still one feature request:
on my tablet, this virtual keyboard is only half of my screen width, which is wasting of space.
How about make it using the complete with, to also have the "extended keys" easy reachable at the same time?

**Comment by gujjwal00** [comment]
Yeah, its more optimized for mobiles. Making these more configurable is already on my todo list.
