### ISSUE TITLE
Oculus Quest 2 compatibility

### ISSUE THREAD

**Issue by BITR353T** [gujjwal00/avnc#182]
I was able to install the app on a quest and have it not crash. The message that I get is "native Library is missing, you may have installed the wrong apk. Install from f-driod or Google play."
Is this a soft-lock or really missing library?

Avnc would be more useful than virtual Desktop.

**Comment by gujjwal00** [comment]
AVNC uses spit APKs on Play Store to reduce download size. So if you install from Play Store, and they copy the APK from that device, it may not include all native libraries included in AVNC.

To avoid this issue, please use the APKs listed here: https://github.com/gujjwal00/avnc/releases . 
You can also download APKs from https://f-droid.org/packages/com.gaurav.avnc/ .
