### ISSUE TITLE
Suggestion: Add no-input option

### ISSUE THREAD

**Issue by Splarkszter** [gujjwal00/avnc#183]
Hello and i hope you are having a lovely day.

I wish to have an option to disable input, view-only mode. I like to have my phone as just a mirror for writting things down on paper without having to move my neck up and down. But you know, arm and palm sometimes touching the screen moving the stuff around.

Thanks for this project, is really awesome to see such good quality work being done here. It is very well done.

**Comment by gujjwal00** [comment]
Hi @Splarkszter, this option is already available:
**Long press on server -> Edit -> Advanced -> View only**

**Comment by Splarkszter** [comment]
> **Long press on server -> Edit -> Advanced -> View only**

Oh, i never noticed that button that appears on a one use dialog, mybad.
Thanks for the insight!

I would suggest either making it easier to access or a notice at the bottom of the input settings like "Looking for something else?"

:)

**Comment by gujjwal00** [comment]
You are right. "Advanced" should probably be changed to "More Options".

BTW, there is an option in Interface Settings to directly bopen advanced options when you click on the '+' button.
