### ISSUE TITLE
Feature request: One-time modifiers

### ISSUE THREAD

**Issue by dp-alvarez** [gujjwal00/avnc#184]
Currently, if you press one of the modifiers (ctrl, shift, meta, etc) they stay pressed until you tap on them again.
Since most times these modifiers are used for hotkeys, it would be convenient if they were automatically disabled after the next (non-modifier) key. A double tap or hold would keep them pressed.

Small feature but would be very convenient!

**Comment by dp-alvarez** [comment]
Just saw #117 is a duplicate. Closing

**Comment by gujjwal00** [comment]
This is now implemented.

**Comment by dp-alvarez** [comment]
That is fantastic, and much more comprehensive than the initial bug report, thanks for the ping!

Really appreciate the time you put into it, of all the android VNC clients I tried this is the best so far, fantastic piece of free software
