### ISSUE TITLE
Request: Add animated spinner gif while in discovery mode

### ISSUE THREAD

**Issue by Jrchintu** [gujjwal00/avnc#19]
# Request
Replace loading logo in discovery tab with animated logo for indicating a background process of discovery is ongoing.

# Background
A still logo while an ongoing background process looks weired to end user, replacing loading logo with loading gif or some othere kind of visuals will look nice.

**Comment by gujjwal00** [comment]
It already *is* an animating progress bar. Is it not animating for you?

**Comment by Jrchintu** [comment]
> It already _is_ an animating progress bar. Is it not animating for you?

Unfortunately while enabling other acessablity service for some app i accidently pressed remove animation toggle, now after disabling that toggle the animations works perfectly, Sorry for that i will close this issue

**Comment by gujjwal00** [comment]
No problem! Happy to help.
