### ISSUE TITLE
Feature Request: Add a option to change resolution and color depth

### ISSUE THREAD

**Issue by MyBlueHorizon** [gujjwal00/avnc#193]
Add a option to change resolution and color depth can help users reduce their network usage or have a better experience.

**Comment by gujjwal00** [comment]
This has been suggested already:
- Resolution: Its better to change this on server side. Only few servers supports this protocol extension. For these servers, if you want to match the resolution to local screen size, AVNC already has an option for this.
- Color depth: AVNC uses OpenGL ES, which limits the options to 16bit and 24bit. Supporting 16bit is quite a lot of effort given the frame manipulation involving cursor rendering. However, if somebody wants to give it a go, I will be happy to take a patch.

You can look at **Image quality**  in advanced option to reduce network usage.
