### ISSUE TITLE
Feat: Use the top URL bar for searching

### ISSUE THREAD

**Issue by michaelphagen** [gujjwal00/avnc#196]
Thank you for creating this app, it is by far the fastest and most comfortable VNC client on the google play store. One small feature request that would be a huge help for users like me with many (50-100) devices, a search. Something at the top to let me search through my saved connections would be a big help. Not necessary, but it would be appreciated.

As per email discussions I am opening this issue to track progress on implementing this feature.

Thank you!

**Comment by gujjwal00** [comment]
Implemented in https://github.com/gujjwal00/avnc/commit/c2ff8aedc4207c2fe361893862e3b52b5d3ce947
Test APK: https://github.com/gujjwal00/avnc/actions/runs/7318899861/artifacts/1133780837

**Comment by michaelphagen** [comment]
This seems to work great! Thank you so much!!!

**Comment by gujjwal00** [comment]
v2.3.0 is available with this change. 
FYI, AVNC will now keep track of how many times you have connected to a server, and put the most frequent servers on top.
