### ISSUE TITLE
Touch screen mode: enable pop up of auto hide on target at screen edge

### ISSUE THREAD

**Issue by freebrowser1** [gujjwal00/avnc#198]
This is an excellent VNC viewer app, the best available for Android. But what this app still lacks, is support for popup at edge of screen. E.g. many apps and OS-es have an option when the mouse pointer hits the left (or right, top or bottom) a menu appears. This works when AVNC is in trackpad mode, but not (a.k.a. very difficult) in Touchscreen mode. Particularly when on the target screen for e.g. Windows the task bar or under macOS the dock has auto-hide. Even some apps (Stellarium) have auto-hide as well.

An idea might be when zooming out the local panel to less than 100% so the displayed target screen is smaller than the Android screen so it contains black edges. In that state clicking above the target screen pops up the top bar (e.g. macOS menu bar if auto-hide on server) as if the mouse arrow is moved to the upper edge, clicking left of it pops up the left bar (e.g. the Ubuntu app bar) and so on. That would be very useful.

BTW, implementing this request 'Feature Request: Lock zoom / disable pinch to zoom #169' would be useful as well.

**Comment by gujjwal00** [comment]
A bit late but this is now implemented. Test APK: https://github.com/gujjwal00/avnc/actions/runs/10319585304/artifacts/1794973232


> BTW, implementing this request 'Feature Request: Lock zoom / disable pinch to zoom #169' would be useful as well.

It has already been implemented.

**Comment by freebrowser1** [comment]
I tested it shortly, but how does it activate actions close to the edge of the screen ?

**Comment by gujjwal00** [comment]
Just like you said, tap on the black area around the frame, and pointer should move to the edge towards tap. 

Is it not working for you? (I tested with Windows taskbar & Linux Mint panel)

**Comment by freebrowser1** [comment]
That indeed works, but connecting to servers which are currently offline does not timeout. After 20 seconds it is still trying to connect which is way too long.
Can the connect timeout be made user definable ?

**Comment by gujjwal00** [comment]
> That indeed works

Great!

> but connecting to servers which are currently offline does not timeout. After 20 seconds it is still trying to connect which is way too long.
> Can the connect timeout be made user definable ?

AVNC uses LibVNCClient, which I think uses default system timeout. I am not adding a preference for this because you can simply tap the Back button whenever you want.

**Comment by freebrowser1** [comment]
Another question, why is this a separate app AVNC.ci ?
When I installed the app, it did not overwrite the existing app but created a new instance. Is this on purpose ?

**Comment by gujjwal00** [comment]
APK linked above is just a test app. It is built automatically by [CI pipeline](https://github.com/gujjwal00/avnc/actions) whenever a change is pushed to AVNC repo.

> Is this on purpose ?

Yes, these APKs are meant for quick testing (although you can use it however long you want), and installed separately to avoid affecting the main app.

---
As the feature has been implemented, I am closing this issue.
Have a nice day.
