### ISSUE TITLE
Keyboard accent and AltGr

### ISSUE THREAD

**Issue by zequinh4** [gujjwal00/avnc#20]
Hi. Love your VNC app. We have a Samsung Dex community in Brazil with over 5,000 active users in a telegram group who are clamoring for writing and Portuguese support. It is possible to add accent support and the "AltGr + Q" and "AltGr + W" keys so that we can use the characters "/" and "?". Below is a picture of the keyboard in portuguese brazil ABNT2 layout that is the standard of the TabS7/6. Thanks.
![IMG_20211129_153141_534](https://user-images.githubusercontent.com/51301335/143923253-dd9e428c-4046-4fea-8671-ed620d438477.jpg)

**Comment by gujjwal00** [comment]
Glad you like AVNC!

> It is possible to add accent support

Accent support was added in the latest version (see #14), pending on F-Droid. It works correctly with TightVNC server at least.

> the "AltGr + Q" and "AltGr + W" keys 

This should already work, but its possible something is missing. Can you please tell me which VNC server + OS you are using?

Also, I am attaching a debug APK here. It will log all key events received from Android. Please try to enter those characters with this, and post the logs here.

[app-debug.zip](https://github.com/gujjwal00/avnc/files/7460625/app-debug.zip)

You can grab the logs from 'Settings => Tools’ in AVNC, or by using adb.

**Comment by zequinh4** [comment]
Hello my friend. Sorry I'm late. I saw you release an update on F-droid. Thank you very much for your agility and support to our android community. It's working perfectly in ubuntuKDE (Andronix). Thank you one more time.
