### ISSUE TITLE
Feature request: Add a button to remove the left panel

### ISSUE THREAD

**Issue by RebornOfc** [gujjwal00/avnc#200]
So once you connect there is this left panel that shows up when you drag around the left of the screen, but there is a problem, I constantly have the need to keep dragging things around there, and the left panel shows up in my way, the real problem is that it makes clicking not possible until the panel is closed. So, please add a option in the menu somewhere to remove the left panel, because we don't need it when we are using a mouse and keyboard.

**Comment by gujjwal00** [comment]
@RebornOfc I have added an option to disable the left panel. 
Test APK: https://github.com/gujjwal00/avnc/actions/runs/8009875903/artifacts/1267620617
You can control it via `Settings => Viewer => Toolbar => Swipe-in from edge to open`
