### ISSUE TITLE
Is it possible to auto connect to server?

### ISSUE THREAD

**Issue by gety9** [gujjwal00/avnc#204]
I use avnc with only 1 server (to connect to vnc server (tigervnc on termux) on my tablet). Is it possible to auto connect to it? If server is on/discovered - simply to connect rightaway (instead of me making the click on it every time)

If it's not possible currently would you consider adding something like "trusted/preferred server" check box to settings server?
(so any time it's online avnc will auto connect to it by itself)

**Comment by gujjwal00** [comment]
Sorry, that's not possible.

But if you are using a decent enough launcher, you can pin a shortcut to your server on home screen:
 
https://github.com/gujjwal00/avnc/assets/27951674/ca80bac9-3bbe-4009-a9bf-921a2aad99c3

**Comment by urbanbur** [comment]
Thanks. My device is a creepy Hikvision doorphone, so its a no-go.

**Comment by gujjwal00** [comment]
@urbanbur which Android version are you running?

**Comment by urbanbur** [comment]
I have a DS-KH9510-WTE1 (first generation) running Android 5.

**Comment by pergolafabio** [comment]
Hi, tested it also here, also hikvision user
Those devices are indeed limited, no playstore, we can only sideload apk files to it
They have their own launcher, so we are limited there too..

**Comment by gujjwal00** [comment]
Please test the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/14481105/app-debug.zip)
To enable auto-connect, long press on server => Edit => Advanced => Enable 'Auto-connect when app starts'.

**Comment by pergolafabio** [comment]
that works great!!

**Comment by gujjwal00** [comment]
v2.4.2 is now available with this option.
