### ISSUE TITLE
Android 14 Fullscreen Broken

### ISSUE THREAD

**Issue by Bradfreeman1** [gujjwal00/avnc#205]
Been using AVNC for well over a year now as its the most responsive vnc app ive tested, however since updating to android 14 it seems the fullscreen setting is broken. The top taskbar of my ubuntu distro is only clickable with fullscreen disabled. I have attached a video.

https://github.com/gujjwal00/avnc/assets/30218062/0add7736-85ba-42ce-a6ea-96ee761d018c

**Comment by gujjwal00** [comment]
This looks related to the issue: #203 

Please install the following APK (it includes a bunch of input logging):  [app-debug.zip](https://github.com/gujjwal00/avnc/files/14064777/app-debug.zip)

Then do as follows:
1. Connect to the server in fullscreen mode (should already be enabled)
2. Click a few times on the top taskbar, which as you said won't actually work
3. Go back, disable fullscreen mode, and reconnect
4. Click a few times on the taskbar, this time it should work
5. Go back and open `Settings => Tools => Logs`
6. Copy the logs and paste here

**Comment by gujjwal00** [comment]
And a quick question: Does tapping with finger works in full screen?

**Comment by Bradfreeman1** [comment]
Tapping with my finger does not work, it looks like the remote pointer just won't go past where the dex title bar pops up in fullscreen mode and gets stuck. Thought i should also clarify the problem is only with samsung dex and the apps title bar, if i use avnc just on my phone then fullscreen works as intended, however that just isn't as much fun. 

[logs.txt](https://github.com/gujjwal00/avnc/files/14075442/logs.txt)

**Comment by gujjwal00** [comment]
For some reason system is not delivering motion events to AVNC when mouse is in topmost area. 

Looking around, it looks like a bug in OneUI 6.0:
https://old.reddit.com/r/SamsungDex/comments/18gibtf/oneui_6_improvements_on_phones/kd4eisj/    (first comment)
https://techcommunity.microsoft.com/t5/azure-virtual-desktop-feedback/samsung-one-ui-6-0-dex-top-bar-blocks-remote-desktop/idi-p/4005831

Do you have any 'feedback' app installed form Samsung? It might be a good idea to report this to Samsung Developers.

**Comment by Bradfreeman1** [comment]
That's a shame, thank you for the response. I'll definitely report this bug, im sure i can work around it until the 6.1 update. Thank you for keeping avnc updated as well, you're doing gods work sir!
