### ISSUE TITLE
SSH Tunnel is broken since v2.3.0: "There was a problem while connecting to xxx.xxx.xxx.xxx"

### ISSUE THREAD

**Issue by gujjwal00** [gujjwal00/avnc#207]
This is caused by the 'full mode' of R8, which breaks sshlib. This mode was off by default, but AGP 8.2 seems to have tuned it on. The issue is only visible in optimized builds.

Thanks to **Hiroshi MATSUOKA** for reporting this.

**Comment by gujjwal00** [comment]
Fixed in https://github.com/gujjwal00/avnc/commit/9a66581c92f6f87d9353596328e2047bf2820caf
v2.3.1 is now available.

**Comment by gujjwal00** [comment]
I tried v2.3.1 from F-Droid, but I can't reproduce this. I am able to connect with RSA & Ed25519 keys of different sizes.
Can you please try this unoptimized APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/14318209/app-debug.zip)

About that stacktrace: It looks impossible to me, unless R8 literally removed functioning code. Can you upload the APK you are testing with?

**Comment by gujjwal00** [comment]
> I tried with the debug-apk (once using password- and once using key-based auth) and it works perfectly fine.

So maybe the optimizations done by R8 are causing trouble.

> At connection attempt I'm getting the following prompt (not sure if thats new, since I didn't reinstall / re-add my servers for some time now):

Yeah, that's normal for first connection. It is similar to `~/.ssh/known_hosts` file used by `ssh` client. 


> The APK I'm using is the one from F-Droid. Since AVNCs APK is multi-arch you must have used the same one for testing as I did. I can still reupload it here nonetheless: [com.gaurav.avnc_28.zip](https://github.com/gujjwal00/avnc/files/14318371/com.gaurav.avnc_28.zip)
> **Edit:** Just to rule out any possible incompatibillities introduced by F-Droids compiling process I tested with your APK from github releases and got the exact same result.

Yeah, that rules out any APK related issue.


> I tried the F-Droid Build with another client device, running LineageOS 20 (Android 13). There it (ssh-tunnel with password-based auth) does work. The original client device in question is still running Android 11, so it seems to depend upon the android version.

I have tested v2.3.1 to work correctly on following platforms:
- Android 13 phone
- Android 14 in emulator
- Android 11 in emulator 
- Android 5 in emulator


> If you need any additional logs / information, please let me know. I'm happy to help debugging this issue.

Different Android Gradle Plugin versions uses different versions of R8. Current v2.3.1 is built with AGP 8.2.0. So its possible that this particular version is the culprit. 

I am attaching two optimized APKs here:
- [app-ci-8.1.4.zip](https://github.com/gujjwal00/avnc/files/14318783/app-ci-8.1.4.zip) Built with AGP 8.1.4
- [app-ci-8.2.2.zip](https://github.com/gujjwal00/avnc/files/14318786/app-ci-8.2.2.zip) Built with AGP 8.2.2

Please test with both of these. For the version you fail to connect successfully, please post the full logs (if you can use `adb logcat` that would be great, otherwise just use Logs dialog in AVNC settings).

**Comment by gujjwal00** [comment]
> If you can give me a hint how to filter (e.g. what to grep for) the logcat output for only the relevant information I would repeat the test to provide logcat output.

Well, the test didn't work so just AVNC log is fine for now.

Please test these:
[app-ci-ssh21.zip](https://github.com/gujjwal00/avnc/files/14319442/app-ci-ssh21.zip)
[app-ci-ssh23.zip](https://github.com/gujjwal00/avnc/files/14319444/app-ci-ssh23.zip)

These have different SSH library versions. I think atleast the first one will work correctly.

**Comment by gujjwal00** [comment]
Ok, now we know the problematic combination: The issue happens with sshlib 2.2.23, when compiled with AGP 8.1+, with optimizations ON, on some specific devices.

About the issue: sshlib uses tink crypto library. It was updated in v2.2.23. One of the thing that changed is how two byte arrays are compared. Newer version uses Java's `MessageDigest.isEqual()` method, instead of custom check. For some inexplicable reason, this method is returning `true` when comparing two different arrays. To test this I added a test in previous APKs. Look at the first line of logs for `app-ci-ssh23`:
```python
30257 30301 E SSHTest : true
```
This should have been `false` like in case of `app-ci-ssh21`. This incorrect behavior trips up the tink library during key exchange, and a value which should not have been equal to, ends up being equal to `0000000000000000000000000000000000000000000000000000000000000000`, resulting in that exception. 

I am adding couple more APKs, with a bit more testing. Please post the logs for these:
[app-ci-test.zip](https://github.com/gujjwal00/avnc/files/14320621/app-ci-test.zip)
[app-debug-test.zip](https://github.com/gujjwal00/avnc/files/14320623/app-debug-test.zip)

**Comment by gujjwal00** [comment]
Also, please tell me your device model and more about Android version (is it a custom ROM like MIUI or OneUI?)

**Comment by gujjwal00** [comment]
> ```python
> 6794  6823 D SSHTest : b1 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> 6794  6823 D SSHTest : b2 = [9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> 6794  6823 D SSHTest : MessageDigest.isEqual(b1, b2) = true
> 6
> ```

This is the problematic part. As you can see, b1 & b2 byte arrays are different at first byte, but `MessageDigest.isEqual(b1, b2)` is returning true here. And it only seems to happen in optimized builds.

At this point, I need to reproduce this locally to be able to find the root cause. Thanks for testing all the APKs.

I don't want to downgrade sshlib because newer version includes fixes for terrapin attack. 



> ```python
> 6794  6823 D SSHTest : d = [20 numbers between -119 and 118, redacted]
> ```

Just as a note, this is SHA1 digest of byte array `b2`.

**Comment by gujjwal00** [comment]
After quite a bit of testing, I still can't reproduce it. Only reference I found to this bug is this issue: https://github.com/nightscout/AndroidAPS/issues/3039 . This too happens on Android 11, and on specific devices. If you check the logs linked there in first comment, you will find the same exception being thrown as we see here.

So, I want you to please run a few final tests before I chalk it up to an Android bug:

1.  These two are simplest possible APKs with zero dependencies. Theey just contain a byte array equality check, and will print the result on screen.
     [simple-debug.zip](https://github.com/gujjwal00/avnc/files/14368470/simple-debug.zip)
     [simple-release.zip](https://github.com/gujjwal00/avnc/files/14368471/simple-release.zip)
2. If both of those report success, then please try to log into ssh server via ConnectBot app. AVNC uses ConnectBot's SSH library, and if ConnectBot is working then we need to figure out why only AVNC is triggering this.
3. Finally, test this version of AVNC: [avnc-ci-keeprules.zip](https://github.com/gujjwal00/avnc/files/14368468/avnc-ci-keeprules.zip)
    I added a few more R8 `keep` rules after looking through ConnectBot's sources.

**Comment by gujjwal00** [comment]
> > […] before I chalk it up to an Android bug
> 
> Am I interpreting this statement correctly, that this is a (probably rare) android bug

Yes, that's right. Its an Android bug. For reference, this is the code contained in those simple APK:

```java
 private void test() {
        byte[] b1 = new byte[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        byte[] b2 = new byte[]{9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        String arraysResult = Arrays.equals(b1, b2) ? "Error: Arrays.equals(b1, b2) is true" : "Success: Arrays.equals works as expected";
        String messageDigestResult = MessageDigest.isEqual(b1, b2) ? "Error: MessageDigest.isEqual(b1, b2) is true" : "Success: MessageDigest works as expected";
        String version = BuildConfig.DEBUG ? "Debug version" : "Release Version";
        textView.setText(version + "\n\n" + arraysResult + "\n\n" + messageDigestResult);
    }
```
`MessageDigest.isEqual(b1, b2)` & `Arrays.equals(b1, b2) ` are both Java functions, and they should always return `false` for these arrays. There is no difference between two simple APKs, other than that the first APK is debugable. So I would guess that its a bug in JIT/pre-compilation.

> which you can't affect, but which you also can't / won't work around somehow in AVNC's code?

Yes, there is no workaround other than downgrading sshlib to older version.

> Because that would be a bummer for me and probably others who arent willing to replace perfectly working devices just because they were declared EOL by their manufacturers, as we would have to stay on AVNC version 2.2.3.

When I was looking at #81 , I briefly tried to find alternative ssh libraries, but I could not find anything better than Connectbot's library. Not to say Connectbot's sshlib is perfect. I have do shit like [this](https://github.com/gujjwal00/avnc/blob/e193c3fd7cedab55cb0c86f3b1a1791d4c8abbc3/app/src/main/java/com/gaurav/avnc/viewmodel/service/SshTunnel.kt#L121-L136), just to find a port for tunnel.

But recently, I have been using https://github.com/apache/mina-sshd as a dummy server for writing SSH tunnel tests in AVNC. So one possibility is to migrate to that for client side too. Its not flawless though. mina-sshd doesn't [officially](https://github.com/apache/mina-sshd/blob/master/docs/android.md) support Android, and I haven't looked closely at the client-side feature set (and that it doesn't trigger the same bug 😀).

**Comment by kruton** [comment]
Nice investigation, but I'm alarmed you didn't report it to the https://github.com/connectbot/sshlib repo. At any rate, it appears that tink has changed enough that this probably won't happen.
