### ISSUE TITLE
Make available apks?

### ISSUE THREAD

**Issue by iluvatar1** [gujjwal00/avnc#21]
Hi, thanks for the app . I was testing it but I have problems with my s-pen on my tablet, the pointer in avnc does nit follow the pen. I have played with the input settings but still no fix. I am using version 1.0.1 from f-droid. But I see here that you are in version 1.3.0. But no apk is available. Could you please make then available or put the latest version in f-droid? thanks!

**Comment by gujjwal00** [comment]
Hi @iluvatar1 , S-Pen support was added in v1.2.0, which is [available on F-Droid](https://f-droid.org/packages/com.gaurav.avnc/). v1.3.0 has already been picked up by F-Droid, so it should be available soon.

I am also planning to provide APKs here on GitHub in near future.

**Comment by iluvatar1** [comment]
This is very strange. My updated f droid only shows version 1.0.1
![SmartSelect_20211130-214717_F-Droid](https://user-images.githubusercontent.com/1454267/144162784-132e4996-2885-4cce-86ab-f7a73994b5de.jpg)
should I do simething?

**Comment by iluvatar1** [comment]
Forget it, I had to update the repos. Thanks.

**Comment by gujjwal00** [comment]
No problem! Try out the S-Pen, and let me know if you face any issue.
