### ISSUE TITLE
Request for Feedback: Exclude passwords from exported data

### ISSUE THREAD

**Issue by gujjwal00** [gujjwal00/avnc#215]
I am planning to restructure credential storage in AVNC. Tentative (and long-term) goals are:
- Reduce the amount time for which credentials are loaded in memory
- Possibly use Android KeyStore  to encrypt passwords
- A way to generate SSH keys inside AVNC
- Sharing SSH keys across server profiles

Right now, users can import/export saved servers from AVNC settings. As part of the restructuring, I would like to exclude three fields from exported data: **VNC password**, **SSH password**, and **SSH private key**. Rest of the data will be imported/exported as usual. Exporting these has always felt a little off to me. Excluding these will also remove the requirement to authenticate users before export.

So if anyone have use cases related to this, please let me know.

*PS: Any opinion/ideas about asking this type of feedback in general are also welcome.*

**Comment by RadarNyan** [comment]
The entire point of export & import is to make the configuration process easier across multiple devices (or simply as a backup). I personally don't use this, but I can see that if someone has many servers configured, it would be very annoying to have to configure all the credentials manually for each one of them.

How about encrypting sensitive data using AES before exporting? Of course, this would require the user to enter a password when importing the data. Inputting a password once would be much better than setting up credentials one by one.

**Comment by gujjwal00** [comment]
> The entire point of export & import is to make the configuration process easier across multiple devices (or simply as a backup). I personally don't use this, but I can see that if someone has many servers configured, it would be very annoying to have to configure all the credentials manually for each one of them.

I agree with the sentiment, and that was the original motivation behind this feature. But I also don't want to focus too much on such a scenario. Most people aren't using more than a few servers, and I don't believe re-entering credentials once after restoring from backup is that annoying.

> How about encrypting sensitive data using AES before exporting? Of course, this would require the user to enter a password when importing the data. Inputting a password once would be much better than setting up credentials one by one.

That sounds good, but it just adds an extra step after user authentication. I don't want to introduce another level of complexity just for exports.

---

The thing that worries me most is uses leaking their secrets 'accidentally'. If users are aware of the risks, then I am fine with exporting secrets. So, I think making the users opt into exporting secrets with a checkbox would solve that. It would also give them a choice to export without secrets.

**Comment by user8446** [comment]
I'm in the camp to have secrets included. Having the checkbox for user choice would probably be the best.

Any backups should be encrypted and/or secured anyway which is trivial.

**Comment by gujjwal00** [comment]
AVNC now has a option (unchecked by default) to include secrets in exports.
