### ISSUE TITLE
Feature request stereoscopic or monoscopic image

### ISSUE THREAD

**Issue by rimwulf** [gujjwal00/avnc#217]
Think this would be a good feature I won't be much good for gaming but it's a fairly interesting concept when hooked through USB to a computer.

**Additional Info**
- App Version: 2.2.3 (26)
- Android Version: 14 (34)

**Comment by rimwulf** [comment]
Adding stereocoscopic view where it can be added to a VR viewer/Google
cardboard. This way it can be viewed as VR.

**Comment by gujjwal00** [comment]
Sorry, that's not possible. 
First, I am still not entirely sure how you want to use AVNC in VR. There is no 3D content in AVNC.
Second, I am not even remotely experienced in VR development. So, even if there was something to here, I don't know how to do it.
