### ISSUE TITLE
Feature Request: WOL

### ISSUE THREAD

**Issue by bcm314** [gujjwal00/avnc#218]
Would be nice to have implemented Wake On LAN.

In first step, maybe an extra button on each server would be ok (or simply always make WOL first and VNC-connection have to be manually retried).

The final step, I would suggest the following, when tapping on a server:
- if no WOL is configured/enabled, behavior as it currently is
- else (if WOL is configured/enabled), make a ping first
- if received echo, behavior as it currently is
- else (no echo) send WOL
- wait n seconds (as server needs different time to boot, this value should be set for each server)
- start VNC conection

masybe:
- to be fastest (make n very low), VNC conection should be retried for maximum m seconds if VNC-server not yet ready.

also: could make pings in the server-list before, to show with green/red button the state of them.

**Comment by gujjwal00** [comment]
@bcm314 Can you try the following APK: https://github.com/gujjwal00/avnc/actions/runs/9338437912/artifacts/1560192543

You can add MAC address in Advanced server options. Then long-press on the server and send WoL packet.

**Comment by bcm314** [comment]
Hi,

yes, it works very well - tested on two clients and with two different servers.

It's a little bit uncomfortable (using long-tap and many times tapping for reconnect), but I guess it's only the first test, right?

To remember:
maybe an option in the server settings "always send WOL after short tap and do reconnect for x times"

**Comment by gujjwal00** [comment]
Try this: https://github.com/gujjwal00/avnc/actions/runs/9354967090/artifacts/1563768652
It will automatically send WoL packet before connecting, and use the auto-reconnect feature to retry connection.

**Comment by bcm314** [comment]
Works perfect!!!

**Comment by gujjwal00** [comment]
v2.5 is available with WoL support.
The UI is slightly updated: You need to first enable the `Wake-on-LAN` checkbox before entering MAC address.
