### ISSUE TITLE
Cannot connect to vnc on debian bookworm on raspberry pi

### ISSUE THREAD

**Issue by KhurramFHassan** [gujjwal00/avnc#223]
**Description**
As the subject says. It just says "Disconnected (Connection closed by the server). RVNC Viewer works without any problems.

**Additional Info**
- App Version: 2.4.2 (31)
- Android Version: 9 (28)

Thanks
Khurram

**Comment by gujjwal00** [comment]
Which VNC server are you using?

Also, please go to `AVNC Settings => Tools => Logs`, copy the logs and paste here.

**Comment by gujjwal00** [comment]
You might also want to look at this issue: https://github.com/gujjwal00/avnc/issues/143. Default settings of VNC server on Raspberry Pi seems to be only supported by RealVNC Viewer.

**Comment by gujjwal00** [comment]
According to logs, the password didn't match. Can you please double check the password saved in AVNC?

**Comment by KhurramFHassan** [comment]
I have retyped the password but the result is the same. The vnc server is
configured with legacy vnc password authentication. Ultravnc viewer also
has the same problem is AVNC.

Khurram

**Comment by gujjwal00** [comment]
In that case, server logs from pi might indicate what the problem is.

**Comment by gujjwal00** [comment]
Have you checked the server logs on Raspberry Pi?

**Comment by KhurramFHassan** [comment]
This is what I get in the server log:

<13> 2024-04-14T16:59:22.352Z xxx vncserver-x11[701]: Connections:
> connected: x.x.x.x::x (TCP)
> <14> 2024-04-14T16:59:22.418Z xxx vncserver-x11[701]: SConnection: Client
> needs protocol version 3.8
>

Khurram

**Comment by gujjwal00** [comment]
Have you figured anything out, @KhurramFHassan ? 
Given UltraVNC viewer has the same problem, and logs from server are not helpful, there doesn't seem to be anything I can do here.
