### ISSUE TITLE
Feature Request: Mouse Scroll Bar

### ISSUE THREAD

**Issue by juk154** [gujjwal00/avnc#226]
When using the browser, you need to narrow the view to manipulate the right scrollbar, which is very annoying. It is suggested to add a mouse scrollbar on the right side of AVNC, and control the scrollbar of the browser up and down by dragging this mouse scrollbar.

**Comment by gujjwal00** [comment]
Hi, can you please describe the issue in English?

**Comment by juk154** [comment]
> 您好，您能用英语描述一下这个问题吗？

Feature Request: Mouse Scroll Bar


When using the browser, you need to narrow the view to manipulate the right scrollbar, which is very annoying. It is suggested to add a mouse scrollbar on the right side of AVNC, and control the scrollbar of the browser up and down by dragging this mouse scrollbar.

**Comment by juk154** [comment]
> Hi, can you please describe the issue in English?

Feature Request: Mouse Scroll Bar


When using the browser, you need to narrow the view to manipulate the right scrollbar, which is very annoying. It is suggested to add a mouse scrollbar on the right side of AVNC, and control the scrollbar of the browser up and down by dragging this mouse scrollbar.

**Comment by shunf4** [comment]
you can try my fork https://github.com/shunf4/avnc/actions/runs/9312188580

modification mainly done at efdbebd1d4ed3bded3b421373fc33daab5f210ec and 85ec6d84e5eee4711694a5c1c888c2f0f5b3a5f4

**Comment by gujjwal00** [comment]
@juk154 v2.5 is  now available with improved virtual keys. Among other things, now it has Page Up/Down keys to control scrolling:
 ![image](https://github.com/gujjwal00/avnc/assets/27951674/cbe5482f-a339-42bf-8d78-b7922bd7a993)

You can also use different swipe gestures (e.g. two-finger swipe) to scroll content on remote server. Go to Input section in AVNC Settings, and select the gesture you want to use for scrolling. Or, you can try @shunf4's fork mentioned above.
