### ISSUE TITLE
Not working with x11vnc's -ncache flag

### ISSUE THREAD

**Issue by fishBone000** [gujjwal00/avnc#227]
```
-ncache n

              Client-side caching scheme.  Framebuffer memory n (an integer) times that of the full
              display is allocated below the actual framebuffer to cache screen contents for  rapid
              retrieval.   So  a  W x H frambuffer is expanded to a W x (n+1)*H one.  Use 0 to dis‐
              able.
```
Connecting AVNC to `-ncache` flag enabled x11vnc server will...well say the scale of shared area over VNC is 1600x900, on AVNC it will look like a 1600x9000 screen, with the first 1600x900 area on top the shared desktop, while the rest 1600x8100 below is black, sometimes with artifacts.

**Comment by fishBone000** [comment]
Expected:
```
+-------------+
|             |
|  1600x900   |
|             |
+-------------+
```
Actual:
```
+-------------+
|             |
|  1600x900   |  <- Screen being shared
|             |
+-------------+
|             |
|  1600x900   | <- Black, sometimes there's artifacts, like frozen windows
|             |    |
+-------------+    |
|             |    |
|  1600x900   | <- |
|             |    |
+-------------+    |
...
+-------------+    |
|             |    |
|  1600x900   | <- |
|             |
+-------------+

```

**Comment by gujjwal00** [comment]
This is working as expected. Please see x11vnc [FAQ](https://github.com/LibVNC/x11vnc/blob/master/doc/FAQ.md#q-79-can-x11vnc-do-client-side-caching-of-pixel-data-ie-so-when-that-pixel-data-is-needed-again-it-does-not-have-to-be-retransmitted-over-the-network).

Relevent portion:
`
A drawback of the "-ncache n" method is that in the VNC Viewer you can scroll down and actually see the cached pixel data. So it looks like there is a bug: you can scroll down in your viewer and see a strange "history" of windows on your desktop. This is working as intended. One will need to try to adjust the size of his VNC Viewer window so the cache area cannot be seen.
`

**Comment by fishBone000** [comment]
Oh, alright. RealVNC's VNC Viewer automatically adjusts the window, so I thought it's a bug of AVNC. 
Is it possible for AVNC do that too? Think it would be more convenient.

**Comment by fishBone000** [comment]
```
 +--+-------------+--+
 |  |             |  |
 |  |  1600x900   |  |  <- AVNC is not zooming in furthur!
 |  |             |  |     
 |  +-------------+  |
 +--|.............|--+
    |  1600x900   | 
    |             |
    +-------------+
         ....
```

**Comment by gujjwal00** [comment]
You can try increasing Maximum zoom in **Settings => Viewer**

**Comment by fishBone000** [comment]
Oh I see that setting, thanks.  
I still hope that AVNC can auto adjust the window though, for better user experience.

**Comment by gujjwal00** [comment]
The problem with this option is that its transparent to VNC clients like AVNC, even though that's an explicit goal. From AVNC's perspective, ther is no difference between a real 1600x9000 screen and a 1600x900 screen with -ncache = 9.

AVNC tries to fit the entire remote screen at 100% zoom, and that works well for the "normal" aspect ratios.

So my advice is to zoom-in to appropriate size and than save that zoom so you don't have to do it repeatedly. You can also lock the zoom so that it doesn't change in response to pinch gestures.

**Comment by fishBone000** [comment]
I see, advice taken. Thanks!
