### ISSUE TITLE
Function keys not shown anymore since 2.50

### ISSUE THREAD

**Issue by freebrowser1** [gujjwal00/avnc#230]
Since version 2.50 when popping up the keyboard by two finger click, it does not show F1..F12 anymore. 
Even when "Show all keys" is enabled, no function keys are shown.

**Comment by gujjwal00** [comment]
They are visible, you just have to swipe left to access them.  There are 2 (3 if you enable 'Show all keysc)  "pages" which you can swipe horizontally to switch.

Yes, I know, in retrospect, this could have been better communicated to the users.

**Comment by freebrowser1** [comment]
I checked it and it works.

**Comment by Zopiac** [comment]
Yes, better communication would have been nice, but this also leaves plenty of unused space (and wasted movements swiping) when in landscape mode or on tablets even in portrait. Filling the space would be appreciated!

**Comment by gujjwal00** [comment]
I have changed the layout to match with old behavior. It will be available in next release.
