### ISSUE TITLE
Clipboard sync does not work from Android to remote

### ISSUE THREAD

**Issue by graidl** [gujjwal00/avnc#231]
When connecting to an Ubuntu remote server running tigervnc and copying some text in another Android app to the clipboard, I can't paste it in the remote session. The other direction works.

**Comment by gujjwal00** [comment]
How is tigervnc started? Do you know if its the standalone version, or the scraping one?

Does it always happens? For example, does pasting works if you copy something **before** connecting to server?

**Comment by graidl** [comment]
I use the standalone version of tigervnc.

Playing around more, I made the following observations:

- The problem seems to be specific to selecting and copying normal text from pages shown in chrome or also firefox.
- Copying text from other apps, e.g. Google Keep, Vim or Xodo PDF Reader, works.
- Long-pressing a link on a page shown in chrome and selecting either "copy URL" or "copy link text"  also works! Moreover, also copying text from within an edit box in chrome does work.
- Copying normal text from a chrome page before connecting with AVNC also  does *not* work, while copying an URL etc. does.
- The behavior is the same on my Pixel 7 Pro and on an older Galaxy Tab 6.
- I use Gboard, but also switching to Swiftkey does not change anything.
- In RVNC, in comparison, copying works in all cases.

I hope this helps. Thank you for your great work!

**Comment by gujjwal00** [comment]
Thanks for the testing effort. I think I understand the issue now. 

Recent version of AVNC refactored clipboard handling, and it seems to have mistakenly ignored clip texts in HTML format. Please test the following APK, it doesn't contain the offending code and should work in all cases: 

https://github.com/gujjwal00/avnc/actions/runs/8556956979/artifacts/1385272272

**Comment by graidl** [comment]
Yes, I can indeed confirm that this APK resolves the issue.
Thanks for the quick fix!

**Comment by gujjwal00** [comment]
v2.5.1 is available with the fix.
