### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by blchen2003** [gujjwal00/avnc#234]
**Description**黑屏

**Additional Info**
- App Version: 2.5.1 (33)
- Android Version: 13 (33)

**Comment by gujjwal00** [comment]
Describe the issue in English please

**Comment by juk166** [comment]
he means

Description：black screen

Additional Info

- App Version: 2.5.1 (33)

- Android Version: 13 (33)

**Comment by juk166** [comment]
> Describe the issue in English please

he means

Description：black screen

Additional Info

- App Version: 2.5.1 (33)

- Android Version: 13 (33)

**Comment by gujjwal00** [comment]
Well that's not much to go with. Thanks for translating.

@blchen2003 can you give more details about the issue? Which server are you using? Have you tried any other VNC client?

**Comment by gujjwal00** [comment]
Feel free to reopen if you have more details.
