### ISSUE TITLE
bug: Unable to connect when updating to 2.5.1 and causing phone to freeze

### ISSUE THREAD

**Issue by Hgnim** [gujjwal00/avnc#236]
I tried to connect to my VNC server after updating from 2.2.3 to 2.5.1, but my phone system froze during the connection process, causing multiple system components to be unresponsive and requiring a restart. I deleted the software and restored it to the original version, but it was of no use. This is a very serious problem, it cannot be used properly and has caused my system to be unresponsive

**Comment by gujjwal00** [comment]
Just curious, how big is the resolution and how much RAM does your phone have?
