### ISSUE TITLE
Virtual keys cause unexpected offset/zoom

### ISSUE THREAD

**Issue by breakingspell** [gujjwal00/avnc#237]
Hello, I have a report on a regression after v2.5.0 with the virtual keys rewrite (otherwise an excellent improvement!) 
https://github.com/gujjwal00/avnc/commit/9a0dfdef9ddee74a410abf6aef0f8cf2af594378

----
**Description**

Summoning the device keyboard with the new virtual keys visible will cause the zoom to change when the device keyboard is invoked or dismissed. 
Likely related, if the virtual keys are visible on session start, this also offsets the viewer by the height of the two-row bar, which causes vertical travel that the zoom lock would normally prevent. 

----

**Notes**
Quick recordings of the expected behavior (2.4.2) 

https://github.com/user-attachments/assets/7ac024dd-59a2-4be4-bee9-89167b3db32b

and then the regression (2.5.1)

https://github.com/user-attachments/assets/e01d5d64-a549-4e5b-b0cc-2ab2681eefd9

Essentially there shouldn't be any zoom changes thanks to the zoom lock (another excellent feature). It's most noticeable if you have a remote matched to your device screen height. 

It's like the keys are now being drawn in the same region as the viewer. Quick glance makes me think it may be related to the style changes in 
[app/src/main/res/layout/virtual_keys.xml](https://github.com/gujjwal00/avnc/commit/9a0dfdef9ddee74a410abf6aef0f8cf2af594378#diff-cedcbb2659280376deb9f17a561e2271aba7b7e3c00d550f1b0d6caf42ca6bb1) 
[app/src/main/res/values/styles.xml](https://github.com/gujjwal00/avnc/commit/9a0dfdef9ddee74a410abf6aef0f8cf2af594378#diff-1e051f2b0330608e92eba8edc616403ec7bdaa76e29ce0cfb794700686715925)

----
**Additional Info**
- App Version: 2.5.1 (33) 
- Android Version: 11 (30)

**Comment by gujjwal00** [comment]
Hi @breakingspell , This is how virtual keys have behaved in previous versions too. You might be just now noticing it now because virtual keys are a bit taller, and they retain visibility across sessions.

**Comment by breakingspell** [comment]
Hello @gujjwal00, 
I do notice now that the offset behavior is the same in both versions (1-row virtual bar also offsets the viewer, it just wasn't behavior yet to show by default). The vertical travel/offset is undesirable when the guest height is locked to device height, but not a "regression" then :slightly_smiling_face: 

However, zoom is still affected and probably the most pressing. Zoom seems to be retained in all cases on the old version, no small "jump" as the latest version does.

https://github.com/user-attachments/assets/4dcaa1f1-f85a-4910-8f67-2d8af2b5c55f

Could the virtual keys be treated as "floating" in some manner to prevent both of these behaviors? 
I found some posts regarding elements and changing scrolling/floating behavior by cleverly nesting the <layout> structure that I want to test and see if they help.

**Comment by gujjwal00** [comment]
Thanks for the details. You have already done the legwork for me. I can confirm the issue.

It seems to be caused by the use of [ViewPager2](https://github.com/gujjwal00/avnc/blob/5e85fe40febf180915c6ce55ce51f9d1328da0b7/app/src/main/res/layout/virtual_keys.xml#L27-L30) for hosting the virtual keys. For some reason, simply adding the ViewPager2 causes the root view to report incorrect size which in turn affects the base zoom level.

Getting ViewPager2 to work for this use case was already quite cumbersome, and it didn't do as well with the users as I had hoped for. So, it needs to be replaced with a better alternative.

**Comment by breakingspell** [comment]
Glad I could help ID the root cause. I didn't realize ViewPager2 was a standard library till just now, learning at each step of this!

In testing yesterday I tried adding and removing some of the `android:` content parameters and moving them between the layout nodes, no positive effect. I haven't ran into other issues with the virtual keys, to note. 

Now knowing the value is being reported incorrectly by this library, I wonder if there's a way to check for the condition that triggers it (`!isFullscreen && virtKeysVisible`) and fix the value by re-checking or using another method to check size.

**Comment by breakingspell** [comment]
Terrific, the zoom works as expected. The virtual keys also fit horizontally with Show All Keys now, they didn't before. 

Great refinement, thanks!

**Comment by breakingspell** [comment]
Thanks again, this is fixed 💯
