### ISSUE TITLE
[Enhancement] Support showing actual remote cursor or invert mouse color

### ISSUE THREAD

**Issue by sbobbo** [gujjwal00/avnc#241]
I have my desktop set to invert my mouse color per the standard windows mouse settings such that my mouse cursor automatically shows as white on black backgrounds and black on white backgrounds, etc.

AVNC does not seem to support that functionality. The cursor always shows as a black mouse cursor, even when the actual mouse cursor on the remote screen is white.

Is there any chance of improving this?

Thank you!

**Comment by gujjwal00** [comment]
AVNC will draw whatever image is sent by the server as cursor, so its probably the VNC server which is not sending updated cursor image.

Cursor image exchange is not part of the core RFB protocol, and servers differ in how they send cursor images. Can you tell me which OS and VNC server are you using?
