### ISSUE TITLE
Feature request: Have option to put the virtual keys on the left or right edge of the screen

### ISSUE THREAD

**Issue by StriverKlu** [gujjwal00/avnc#242]
Hi gujjwal00, thank you very much for creating such an amazing app. It is the best VNC app I've ever used on my phone.

I'm wondering if you could add an option in the app to put the virtual keys on the left or right edge of the screen. Right now it is on the bottom of the screen, and the view moves up and down with the mouse on landscape mode. Below is an example, the view moves up:
![Screenshot_20240727_001135_AVNC](https://github.com/user-attachments/assets/3b97cf84-6fc5-4cd9-bb00-5f4c3ac1d04e)

Because my phone has round corners, I always leave some space on the left and right of screen. If the virtual keys can be put on these spare space (left or red edge) like the tool bar, it can take advantage of these wasted space and the view will not move too. Below is an example, it will be great if the virtual keys can be put in the place circled in red.
![Snipaste_2024-07-27_00-23-53](https://github.com/user-attachments/assets/649f2b14-6b76-408a-aef3-3cae7601f387)

Thank you again for your work and wish you great day.

**Comment by gujjwal00** [comment]
Hi @StriverKlu ,  moving virtual keys to the side is not really feasible. These are implemented with a horizontal scroll View & pager. You can also swipe the keys to left to access a text box for full fledged editing experience. So the only way to move these to side like you suggested is to have a second implementation with vertical scroll View. I obviously don't want to do that for such an edge case.

However, I can disable the up/down movement of frame view because that seems to be your main problem.

**Comment by StriverKlu** [comment]
Hi @gujjwal00, thank you so much for your response.

Yeah, it will be great if there can be an option to disable the up/down movement of the frame view. Very appreciated.

**Comment by gujjwal00** [comment]
Quick question @StriverKlu ,  are you using 'Touchpad' gesture style?

The main reason to move the frame up/down was to allow you to access the UI hidden by the virtual keys, without closing virtual keys.. So I am thinking about disabling up/down movement only when 'Touchpad' gesture style is active, where you can access the partially visible UI via mouse pointer.

**Comment by StriverKlu** [comment]
Hi @gujjwal00, thanks for asking. 

Yes, I'm using "Touchpad" gesture style.

**Comment by gujjwal00** [comment]
This is fixed in latest release.

**Comment by StriverKlu** [comment]
@gujjwal00 Thank you!
