### ISSUE TITLE
Request: support sntrup761x25519 (Simplified NTRU Prime)

### ISSUE THREAD

**Issue by VA1DER** [gujjwal00/avnc#247]
OpenSSH's default is now the hybrid Simplified NTRU prime / ed25519 KEX.  As the new default, many sites have switched to it and employ it exclusively.   It would be beneficial if AVNC supported it for SSH connections

**Comment by gujjwal00** [comment]
AVNC uses ConnectBot's SSH library for connections, so it's limited to the schemes supported there.

**Comment by gujjwal00** [comment]
However, if you have some other way to start the tunnel, AVNC should be able to use that.

**Comment by VA1DER** [comment]
Are you capable of running an actual SSH binary?  The termux project maintains OpenSSH binaries that will work and could be included with avnc.

**Comment by gujjwal00** [comment]
Sorry, that's not a feasable solution. Instead, you can launch AVNC from Termux (for a given IP address or a server already saved in AVNC), after starting the tunnel.
