### ISSUE TITLE
Input/Stylus: Remote cursor doesn't follow local cursor

### ISSUE THREAD

**Issue by personalizedrefrigerator** [gujjwal00/avnc#25]
## Summary
 * Unless touching the screen with the stylus,
     * The remote cursor is stationary while moving the local cursor
 * Moving the cursor with a bluetooth mouse (while not clicking) works fine

https://user-images.githubusercontent.com/46334387/146277332-96dc5f31-d574-443b-9451-613ae83d296d.mp4

**Comment by gujjwal00** [comment]
Can you tell me the version of AVNC installed?

**Comment by gujjwal00** [comment]
and which VNC server you are using.

**Comment by personalizedrefrigerator** [comment]
AVNC 1.4.0, tigervncserver 1.11.0

**Comment by gujjwal00** [comment]
I am uploading a test app here. It can record various motion events received from Android during a gesture. Please run this app and move the stylus in gray area, then paste the logs here.


[touch-tester.zip](https://github.com/gujjwal00/avnc/files/7415435/touch-tester.zip)

**Comment by personalizedrefrigerator** [comment]
I think the issue is in `TouchHandler.kt`, line 71. Changing
```kt
         if (Build.VERSION.SDK_INT < 23 || !mousePassthrough || !e.isFromSource(InputDevice.SOURCE_MOUSE))
```
to
```kt
        if (Build.VERSION.SDK_INT < 23 || !mousePassthrough
                || !e.isFromSource(InputDevice.SOURCE_MOUSE) && !e.isFromSource(InputDevice.SOURCE_STYLUS))
```
fixes the issue.

**Comment by gujjwal00** [comment]
Thank you for identifying the issue, and fixing it. I have added the fix via https://github.com/gujjwal00/avnc/commit/191d394304aa26427bc0311c714a965946be3a11. Please test it out.
