### ISSUE TITLE
Application function addition

### ISSUE THREAD

**Issue by 2006fcyz** [gujjwal00/avnc#251]
Add an interactive button to AVNC to support horizontal and vertical screen switching.
Or add gravity direction detection, and when the gravity direction changes, change the direction to horizontal or vertical screen direction.

thank you

**Comment by gujjwal00** [comment]
It already works that way. If you change phone's gravity, AVNC will automatically match that.

**Comment by 2006fcyz** [comment]
> It already works that way. If you change phone's gravity, AVNC will automatically match that.

thank you

It would be better if a button for manually switching between horizontal screen and vertical screen could be added to the sliding-out menu function interface after connecting AVNC.

thank you

**Comment by gujjwal00** [comment]
There are already two options to set preferred orientation:
- Global option (AVNC Settings => Viewer)
- Per-server option (Long press on server => Edit => Advanced)

You can also use Android's quick-setting tile to control orientation. So, sorry, but I don't want to add another button for this.

**Comment by 2006fcyz** [comment]
thank you

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
