### ISSUE TITLE
Feature Requestl: configurable time to retry

### ISSUE THREAD

**Issue by Fabrice-Bernes** [gujjwal00/avnc#252]
I have a server set to restart as soon as it crashes, so I know it's immediately accesible everytime I disconnect.

The current setting for reconnecting automatically takes arround 5 seconds to actually try again, so it's currently faster for me to press the button myself.

I don't know if having an instant re-try is too much of a niche case to be worth adding, but in any case, thanks in advance.

**Comment by gujjwal00** [comment]
Its already on my todo list. Infact, last few AVNC versions will try to reconnect immediately if it got disconnected while app was in background.

**Comment by gujjwal00** [comment]
AVNC will now try to reconnect after 1 second, 3 seconds, and then every 5 seconds.

Test APK: https://github.com/gujjwal00/avnc/actions/runs/11985836957/artifacts/2227725485

**Comment by Fabrice-Bernes** [comment]
I tried that test APK, and it works as expected. I like this solution, Thanks.
