### ISSUE TITLE
v2.6.1: Android -> remote Clipboard sync does not work

### ISSUE THREAD

**Issue by gothka404** [gujjwal00/avnc#256]
Hi,
first I'd like to thank you for this awesome app. Came to conclusion this is the best available FOSS android app!

Everything worked smoothly except pasting clipboard from Android client to remote device. Clipboard sync from remote -> client works though.

**Client environment:**
- Android 14 
- AVNC 2.6.1 (F-Droid)
- Settings -> Server -> "Clipboard sync" is enabled

**Server environment:**
- Gnome Remote Desktop on Fedora 40 with VNC enabled via CLI/`grdctl`

**Reproduction/observations:**
- Open any text editor on remote and copy `foo` into clipboard
- Connect to remote via Android app AVNC
- Right at connection start, remote clipboard (`foo`) is copied to Android client clipboard, which is expected
- After that, tried to copy text `bar` to Android client clipboard and pasted it into text editor of remote target via AVNC app (long press -> Paste)
- Still the old value `foo` from remote clipboard is pasted, Android client clipboard has `bar` -> not synced
- Btw: When switching from another app to copy something into clipboard, and back to AVNC, I noticed app hint "AVNC pasted from your clipboard" is displayed
- pasting works from another client to remote (tried with desktop client Remmina) 

Current workaround:
- In toolbar of AVNC swipe left to get to the input dialog "Send text to server"
- Paste Android clipboard into this diallog, which sends text to remote
- Hence AVNC app seems to be able to access Android clipboard, but it is just not forwarded to remote 

Let me know, if I can be of any assistance.

Related: https://github.com/gujjwal00/avnc/issues/231

**Comment by gujjwal00** [comment]
Thanks for the detailed write-up and testing. Let me see if I can reproduce the issue.

In the meantime, can you please copy the logs from Settings -> Tools -> Logs, and paste here. You don't have to copy something in other app,  if you type something in "Send text to server" box and copy it, AVNC should try to send it to server.

**Comment by gujjwal00** [comment]
It looks like a bug in extended clipboard implementation on LibVNCClient (VNC library used by AVNC), but it will take some time to find the root cause.

**Comment by gothka404** [comment]
Interesting, thanks for the status update! Take your time, I (probably) won't be of any help debugging this lib.

**Comment by gujjwal00** [comment]
So this is actually a bug in Gnome Remote Desktop. GRD doesn't handle UTF8 clipboard text, but still advertises support for it. When AVNC sends UTF8 clipboard text, GRD silently discards it. Remmina works because it is not sending UTF8 text ( try to copy some emojis ).

You can open a issue in GRD repo if you want. It's a relatively easy fix because internally GRD already uses UTF8. I will try to send a patch if I can find some time.

**Comment by gothka404** [comment]
@gujjwal00 Awesome!

Unfortunately I needed to wipe my testing machine. When having time, I will reinstall it, test out UTF-8 clipboard text handling with my environment, create an issue in https://gitlab.gnome.org/GNOME/gnome-remote-desktop and report that back to you, so you might add technical details beyond bare user story and possibly link a patch to it.

Alternatively feel free to create the issue yourself, if it makes sense for you to directly add technical details.

Having sorted this error out, AVNC definitely is the way to go for me with GRD >= 47 (with VNC support), as best mobile client from all RDP + VNC apps available.

Thanks again very much for having gone this debugging route!

**Comment by gothka404** [comment]
@gujjwal00 Created [issue](https://gitlab.gnome.org/GNOME/gnome-remote-desktop/-/issues/225)

**Comment by gujjwal00** [comment]
Thanks @gothka404
