### ISSUE TITLE
Software Keyboard/Ctrl Key: Not recognised

### ISSUE THREAD

**Issue by personalizedrefrigerator** [gujjwal00/avnc#26]
## Summary
 * Pressing `Ctrl+D` on a software keyboard does not send `Ctrl+D` to the remote host

https://user-images.githubusercontent.com/46334387/146279002-ecbd520d-114d-4b5e-b05c-2f1e1868400d.mp4

I'm using the Samsung Virtual Keyboard. As such, I understand if this can't easily be debugged/fixed!

## Version information
AVNC 1.4.0, tigervncserver 1.11.0

**Comment by personalizedrefrigerator** [comment]
> To debug this we need to know what events are sent by this keyboard. Can you please add a log line like this
> 
> ```kotlin
>   Log.d("KeyHandler", "uChar = ${getUnicodeChar(event)}, event = $event")
> ```
> 
> at the beginning of [handleKeyEvent()](https://github.com/gujjwal00/avnc/blob/191d394304aa26427bc0311c714a965946be3a11/app/src/main/java/com/gaurav/avnc/ui/vnc/KeyHandler.kt#L108) and collect the logs.
> 
> I have tested with Hacker's Keyboard, and its working correctly.

```python
# Ctrl+A
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_A, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON|META_CTRL_RIGHT_ON, flags=0x6, repeatCount=0, eventTime=39104637, downTime=39104637, deviceId=0, source=0x0, displayId=0 }
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_A, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON|META_CTRL_RIGHT_ON, flags=0x6, repeatCount=0, eventTime=39104638, downTime=39104638, deviceId=0, source=0x0, displayId=0 }

# Just A, no ctrl
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_A, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=39118262, downTime=39118262, deviceId=-1, source=0x101, displayId=-1 }
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_A, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=39118262, downTime=39118262, deviceId=-1, source=0x101, displayId=-1 }

# Ctrl+Shift+A
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_A, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON|META_CTRL_RIGHT_ON, flags=0x6, repeatCount=0, eventTime=39234179, downTime=39234179, deviceId=0, source=0x0, displayId=0 }
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_A, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON|META_CTRL_RIGHT_ON, flags=0x6, repeatCount=0, eventTime=39234179, downTime=39234179, deviceId=0, source=0x0, displayId=0 }
```

Note: I see no difference between the `Ctrl+A` and the `Ctrl+Shift+A` output. The difference between the `Ctrl+A` and `A` output is the `metaState` property.

**Comment by gujjwal00** [comment]
Yeah, that's definitely weird. For comparison, here is the log for `Ctrl+A` using Hacker's Keyboard:
```python
D/KeyHandler: uChar = 0, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_CTRL_LEFT, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x0, repeatCount=0, eventTime=1639704361047, downTime=1639704361047, deviceId=-1, source=0x0 }
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_A, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x0, repeatCount=0, eventTime=1639704361047, downTime=1639704361047, deviceId=-1, source=0x0 }
D/KeyHandler: uChar = 97, event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_A, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x0, repeatCount=0, eventTime=1639704361047, downTime=1639704361047, deviceId=-1, source=0x0 }
D/KeyHandler: uChar = 0, event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_CTRL_LEFT, scanCode=0, metaState=META_CTRL_ON|META_CTRL_LEFT_ON, flags=0x0, repeatCount=0, eventTime=1639704361047, downTime=1639704361047, deviceId=-1, source=0x0 }
```

Your keyboard is not generating standalone `Ctrl`/`Shift` up/down events. And as you said, there is no indication of `Shift` being down during `Ctrl+Shift+A`.

**Comment by gujjwal00** [comment]
As this not a bug in AVNC, how do you want to proceed?

**Comment by personalizedrefrigerator** [comment]
> As this not a bug in AVNC, how do you want to proceed?

Here are some options:
 * Close this issue — it's not an AVNC issue
 * Look at `event.metaState` and send key events based on it if we didn't originally receive an `ACTION_DOWN` for that key.
     * `KeyHandler` is getting long. If we do this, it might make sense to first refactor `KeyHandler`. (E.g. using the decorator pattern,
```kt
 private val filter = DiacriticsHandler(KeyRemapper(ModifierHandler())));
 
 ...
 
  private fun handleKeyEvent(event: KeyEvent): Boolean { 
     return filter.handleKeyEvent(event, dispatcher)
  }
```
).

**Comment by gujjwal00** [comment]
> Close this issue — it's not an AVNC issue

I should, but I have trouble saying No to other people 😊.
Can you switch to any other keyboard app (you might like them even more 😄)? If not, we can add the workaround in AVNC.

About the decorator pattern, these "snippets" are small enough for individual functions and we should be fine for a little while. Even if we split them across classes, I would want them to stay in the same file to keep them coupled together. I have tried very hard to keep `KeyHandler` properly organized & documented so that it is easy to read.

**Comment by personalizedrefrigerator** [comment]
I'll try reporting the bug to Samsung (I like the keyboard's handwriting recognition). I normally use an external keyboard, so don't encounter this issue often.

Thank you for your help!

**Comment by gujjwal00** [comment]
So... I was thinking about this (its stuck in my head now), and how complex our workaround might be. Something simple like this (in `KeyHandler`) could work:
```kotlin

    private var metaState = 0

    private fun simulateMetaKeys(event: KeyEvent) {
        val isDown = (event.action == KeyEvent.ACTION_DOWN)
        val isConsistent = KeyEvent.isModifierKey(event.keyCode) ||
                           event.modifiers == 0 ||
                           metaState == event.metaState

        if (isConsistent) {
            metaState = event.metaState
            return
        }

        if (event.hasModifiers(KeyEvent.META_ALT_RIGHT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_ALT_RIGHT, isDown)
        else if (event.hasModifiers(KeyEvent.META_ALT_LEFT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_ALT_LEFT, isDown)

        if (event.hasModifiers(KeyEvent.META_CTRL_RIGHT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_CTRL_RIGHT, isDown)
        else if (event.hasModifiers(KeyEvent.META_CTRL_LEFT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_CTRL_LEFT, isDown)
    }
```

And, if we add a pref for meta key simulation, we can simplify this further by dropping the `metaState` tracking, and simulating meta keys unconditionally, when that pref is turned on. 

We can remove this workaround when Samsung fixes the bug (likely never 😔).
So do you want to wok on it?

**Comment by personalizedrefrigerator** [comment]
> So... I was thinking about this (its stuck in my head now), and how complex our workaround might be. Something simple like this (in `KeyHandler`) could work:
> 
> ```kotlin
>     private var metaState = 0
> 
>     private fun simulateMetaKeys(event: KeyEvent) {
>         val isDown = (event.action == KeyEvent.ACTION_DOWN)
>         val isConsistent = metaState == event.metaState ||
>                            event.modifiers == 0 ||
>                            KeyEvent.isModifierKey(event.keyCode)
> 
>         if (isConsistent) {
>             metaState = event.metaState
>             return
>         }
> 
>         if (event.hasModifiers(KeyEvent.META_ALT_RIGHT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_ALT_RIGHT, isDown)
>         else if (event.hasModifiers(KeyEvent.META_ALT_LEFT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_ALT_LEFT, isDown)
> 
>         if (event.hasModifiers(KeyEvent.META_CTRL_RIGHT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_CTRL_RIGHT, isDown)
>         else if (event.hasModifiers(KeyEvent.META_CTRL_LEFT_ON)) emitForAndroidKeyCode(KeyEvent.KEYCODE_CTRL_LEFT, isDown)
>     }
> ```
> 
> And, if we add a pref for meta key simulation, we can simplify this further by dropping the `metaState` tracking, and simulating meta keys unconditionally, when that pref is turned on.
> 
> We can remove this workaround when Samsung fixes the bug (likely never 😔). So do you want to work on it?

I can work on it (and submit a PR when I have time)!
