### ISSUE TITLE
Feature Request - Stylus Support

### ISSUE THREAD

**Issue by leandro-benedet-garcia** [gujjwal00/avnc#263]
Hello, I have a Samsung S6 2024 that has a stylus support and I am using AVNC client side and the command
```
krfb-virtualmonitor --name WirelessDisplay --resolution 2000x1200 --password 123456 --port 5900
```

To generate a virtual screen and open a vnc server in my machine with a KDE 6 session running wayland. The mouse does move when I hover my pen, but when I press my stylus to the screen, nothing happens.

So I would like to request the feature of stylus support, preferably with pressure support so I can sculpt in Blender in my computer.

I would be able to implement this feature if someone would be able to guide me which files to modify

**Comment by leandro-benedet-garcia** [comment]
Here are the logs:
https://pastebin.com/4ZLZmHNN

Also, I tested again, the mouse does not move in the computer, I am starting to think it might be a bug in `krfb-virtualmonitor` instead.


> VNC protocol doesn't have any concept of pressure, or even a stylus for that matter. So this is not possible.

Strange, TurboVNC [seems to support them](https://github.com/TurboVNC/turbovnc/issues/154) (Why I asked in the first place, thought vnc protocol supported it) 

Do they have a extra implementation of the vnc protocol?

**Comment by gujjwal00** [comment]
The logs look normal, so this might be a server issue. Please try with a different VNC server. Or try a different VNC client, e.g. MultiVNC, to rule out issue in AVNC.

> Do they have a extra implementation of the vnc protocol?

Yes, TurboVNC is probably using an extension.

**Comment by gujjwal00** [comment]
TurboVNC appears to be using GII extension, which doesn't seem to be supported by anyone else. AVNC uses LibVNCClient which also doesn't support it.

So I don't think there is anything to do here for AVNC, unless basic pointer movement with stylus is broken.
