### ISSUE TITLE
Keyboard Sidebar/Swipe mapped to back: Unable to open with touch

### ISSUE THREAD

**Issue by personalizedrefrigerator** [gujjwal00/avnc#27]
## Summary
 * On my device, swiping from the edge of the screen (with touch) is mapped to `back` because it has no physical back button.
 * As such, the OS consumes the swipe-from-left gesture that would otherwise open the sidebar.

## Version Information
 * AVNC 1.4.0

**Comment by personalizedrefrigerator** [comment]
Closing: A two-finger swipe from the left edge of the screen also opens the sidebar.

**Comment by gujjwal00** [comment]
You can also align the toolbar to right edge in Settings.

**Comment by personalizedrefrigerator** [comment]
> You can also align the toolbar to right edge in Settings.

Swiping from the right edge also triggers the back action.
