### ISSUE TITLE
mouse button not working on games

### ISSUE THREAD

**Issue by JunkyardCat** [gujjwal00/avnc#270]
so muse clicks dont seem to work on games . moonlight (sunshine) app works fine. was wondering whats the difference between this and moonlight app when it comes to mouse input? are there plans on implementing moonlights way of inputting mouse clicks?

**Comment by gujjwal00** [comment]
Try enabling `Send delayed click events` in Advanced server options (Long press on server => Edit => Advanced).

**Comment by JunkyardCat** [comment]
i spoke to soon. i didnt test the right mouse button. it doesnt seem to work

**Comment by gujjwal00** [comment]
Yeah, that option only affects the left click. I will apply the workaround to right click too in next release.

**Comment by gujjwal00** [comment]
v2.7.0 is available with the change. Enabling  `Send delayed click event` should work for right click too.
