### ISSUE TITLE
For multiple monitors on the server side, could the Android client provide monitor selection function?

### ISSUE THREAD

**Issue by cruisermaxx** [gujjwal00/avnc#273]
As the title described, avnc on Android can't select the remote monitor like PC Viewer. Could this function be added?

Thanks for discussing!

**Comment by gujjwal00** [comment]
I don't think there is any support for multiple monitors in VNC protocol, but there may be an extension. LibVNCClient doesn't have anything related to multiple monitors, so this is not something I can add in AVNC.

What is is 'PC Viewer'? A VNC client like AVNC?

**Comment by cruisermaxx** [comment]
The RealVNC Viewer on PC has this function. Is it poosible to realize for AVNC?
![PC1 Snipaste_2024-11-22_22-33-05](https://github.com/user-attachments/assets/da5f4c23-88a0-4ed3-b317-38d26a945443)

**Comment by cruisermaxx** [comment]
> Which VNC server are you using?您使用的是哪个 VNC 服务器？

The TightVNC

**Comment by cruisermaxx** [comment]
> I looked into it, and I think this is done via ExtendedDesktopSize protocol extension. Basically, server _still_ sends all screens to VNC client in a giant buffer, but it can tell the client about different screen boundaries. Client can then choose to draw only a part of the buffer.我研究了一下，我认为这是通过 ExtendedDesktopSize 协议扩展完成的。基本上，服务器_仍然_在一个巨大的缓冲区中将所有屏幕发送到 VNC 客户端，但它可以告诉客户端不同的屏幕边界。然后，客户端可以选择仅绘制缓冲区的一部分。
> 
> This is quite a big task to implement because client needs to handle everything. Some work is needed in LibVNCClient to expose proper screen information. AVNC frame rendering needs to be updated to only render partial buffer, and input handling will have to account for per-screen coordinates.这是一项相当大的任务，因为客户需要处理所有事情。在 LibVNCClient 中需要做一些工作来公开正确的屏幕信息。AVNC 帧渲染需要更新为仅渲染部分缓冲区，并且输入处理必须考虑每个屏幕的坐标。
> 
> So, while things may change in future, I am not implementing this for now, sorry.所以，虽然将来情况可能会发生变化，但我现在不会实施它，抱歉。

Thanks for your replying! No wonder RealVNC is only implemented on the PC client, it is not introduced on the Android side.
I hope it is still implemented in the future, now remote is a trend~
