### ISSUE TITLE
Is it possible to remotely display a specified program window？

### ISSUE THREAD

**Issue by cruisermaxx** [gujjwal00/avnc#276]
When remote control Windows PC, sometimes we don't need display the whole desktop.
Sometimes display a specified program window is easier to use.
So is it possible to achieve on the AVNC client or it need the Windows TightVNC to support?

Thank you for discussing!
Best regards,
Henry

**Comment by gujjwal00** [comment]
No, this is not possible from AVNC. You can check TightVNC if something like this is available.
