### ISSUE TITLE
[Feature Request] Option to hide local Android cursor

### ISSUE THREAD

**Issue by personalizedrefrigerator** [gujjwal00/avnc#28]
## Summary
 * Currently, when an external mouse is connected, the local Android system cursor completely covers the remote cursor

## Proposed Solution
 * An option to hide the local cursor would therefore be useful!

## Alternative Solutions
 * Not making this a setting and always hiding the local cursor
   * This would make it harder to debug input issues.

## Version Information
AVNC 1.4.0

**Comment by personalizedrefrigerator** [comment]
https://user-images.githubusercontent.com/46334387/146331435-0a0d4ede-e709-4d69-8814-1932804d655c.mp4

**Comment by gujjwal00** [comment]
Maybe you have already tried it, but there is an option to hide the remote cursor. When editing a Server, tap on 'Advanced', and enable 'Hide Remote Cursor'. This is better for responsiveness but you loose the context-aware cursors.

I will try to implement hiding local cursor when I have some time.
