### ISSUE TITLE
Button to show keyboard

### ISSUE THREAD

**Issue by dbolton** [gujjwal00/avnc#3]
I don't see a way to show the keyboard, but I see one in your screenshots. How do I get the keyboard show?

Samsung, Android 11

**Comment by gujjwal00** [comment]
You can swipe-in from the left edge.
You can also long press on the left edge to peak it.

It's a simple drawer widget, like the one in home activity. If you prefer, you can set the alignment to right edge in settings.

**Comment by dbolton** [comment]
Perfect! Thank you.
