### ISSUE TITLE
Two-finger scrolling not working with Samsung trackpad (keyboard cover)

### ISSUE THREAD

**Issue by gujjwal00** [gujjwal00/avnc#31]
Greetings @gujjwal00 . Once again, thank you very much for your commitment to the community. I did the test with the samsung trackpad (keyboard cover). Single click and double click working perfectly. The movement too.

Mistake
I cannot scroll to move up or down a content.

What happens?
When you try to scroll with two fingers on the trackpad, what happens is a navigation through the elements of the screen without the pointer moving.

https://user-images.githubusercontent.com/51301335/147293565-f4bed359-868f-4a05-baae-055cb2cf8549.mp4

_Originally posted by @zequinh4 in https://github.com/gujjwal00/avnc/issues/5#issuecomment-1000534505_

**Comment by gujjwal00** [comment]
I am attaching a test app here which can record touch events received from Android. Can you please run this, perform some gestures with touchpad, and post the logs here?

[touch-tester.zip](https://github.com/gujjwal00/avnc/files/7435574/touch-tester.zip)

**Comment by zequinh4** [comment]
Hi. Hope I managed to do it the right way hihihi. Merry Christmas and thank you again!

[Logs.txt](https://github.com/gujjwal00/avnc/files/7774274/Logs.txt)

**Comment by zequinh4** [comment]
@gujjwal00  Another test.

[Logs2.txt](https://github.com/gujjwal00/avnc/files/7774278/Logs2.txt)

**Comment by gujjwal00** [comment]
Thanks for the logs @zequinh4 , and Merry Christmas to you too 🎅.

I have some questions:
- What actions have you configured for `1 Finger Swipe` & `2 Finger Swipe` gestures in settings?
- Have you enabled the `Hide Remote Cursor` server option?
- Are you using the APK I posted in #5 ?

**Comment by zequinh4** [comment]
Hello again my friend @gujjwal00 :santa: 
> * Quais ações você configurou para `1 Finger Swipe`& `2 Finger Swipe`gestos nas configurações?
**Yes, I set it up like the image below.**
> * Você habilitou a `Hide Remote Cursor`opção do servidor?
**Yes, I hid the cursor because there is always a delay.**
> * Você está usando o APK que postei no modo [Adicionar Mouse Trackpad e gesticular como o laptop ]
**I'm using this apk (app-test.zip) that you made available!** --> (https://github.com/gujjwal00/avnc/issues/5)[ nº 5](https://github.com/gujjwal00/avnc/issues/5) ?[](https://github.com/gujjwal00/avnc/issues/5)

![Screenshot_20211224-134640_AVNC](https://user-images.githubusercontent.com/51301335/147365624-5b896d87-0f86-4959-bb6e-bc7c67afba48.jpg)
![Screenshot_20211224-134654_AVNC](https://user-images.githubusercontent.com/51301335/147365629-c195891d-0e14-4d15-9d98-bd2d9b5cd068.jpg)
![Screenshot_20211224-135049_AVNC](https://user-images.githubusercontent.com/51301335/147365635-66b42aa2-0290-4d61-9257-e0f3ccd1077a.jpg)

**Comment by gujjwal00** [comment]
Thank you. 

So what's happening here is that 2-finger swipe is being treated as 1-finger swipe, to which you have assigned `Move Pointer` action. So the remote pointer is being moved, but as you have hidden it, its not visible.

Unfortunately, this is out of my control. If you look at the logs:
```kotlin
GestureStart: Swipe
...
OT: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=591.27625, y[0]=306.92072, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x10000002, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=368685017, downTime=368685017, deviceId=181, source=0x3002, displayId=0 }
OT: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=584.3911, y[0]=306.92072, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x10000002, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=368685033, downTime=368685017, deviceId=181, source=0x3002, displayId=0 }


GestureStart: 2-finger Scroll
...
OT: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=869.8763, y[0]=309.9757, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x10000002, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=368698215, downTime=368698215, deviceId=181, source=0x3002, displayId=0 }
OT: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=869.99115, y[0]=293.48785, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x10000002, edgeFlags=0x0, pointerCount=1, historySize=2, eventTime=368698232, downTime=368698215, deviceId=181, source=0x3002, displayId=0 }
```

you will notice that both of these gestures are generating similar events, and `pointerCount` is 1 in both cases. Hence, AVNC is unable to differentiate between two gestures.

This is a known issue with how this device generates touchpad events, and if you read through #9 , you will notice some other issues.

If you want, you can set the action for '1-Finger Swipe' to `Scroll Remote Content`.

**Comment by zequinh4** [comment]
@gujjwal00  Interestingly putting "1 finger swipe" as scroll and keeping "2 finger swipe" as scroll is working perfectly. Thank you my friend!
I'm looking forward to releasing this update on F-Droid!


https://user-images.githubusercontent.com/51301335/147368429-a53fb01e-9424-4f6b-bbdb-3ff770b8d1c2.mp4
![Screenshot_20211224-151620_AVNC](https://user-images.githubusercontent.com/51301335/147368445-21bd53f4-788b-4a32-9871-7ea663d6e803.jpg)

**Comment by zequinh4** [comment]
@gujjwal00  
I suggest the implementation of a switch in the "input" menu so that this configuration automatically occurs for the Samsung Bookcover Keyboard. Ex: "Samsung Bookcover Keyboard". It would easily solve this compatibility issue! Hugs!

**Comment by gujjwal00** [comment]
You don't have to wait for F-Droid update. Current version there already supports setting scroll on 1-finger swipe.

Automatic setting change via hardware detection is out of scope, for now at least.
