### ISSUE TITLE
hardware acceleration in frame buffer

### ISSUE THREAD

**Issue by SaicharanKandukuri** [gujjwal00/avnc#32]
@gujjwal00 

can you use OpenGL or Vulkan to render frame buffers to remove screen tearing and all laggy stuffs

```c
glBindFramebuffer(GL_FRAMEBUFFER, fbo);  
```
> or is It possible?

**Comment by gujjwal00** [comment]
AVNC is already using OpenGL ES for rendering.

**Comment by SaicharanKandukuri** [comment]
Oh!!! ya!

60 FPS renders
✌️
