### ISSUE TITLE
How do I translate AVNC?

### ISSUE THREAD

**Issue by eshagh79** [gujjwal00/avnc#33]
Hello,
I use your program and thank you for making this great software.
I would like to contribute to the translation of this program into my own language, how can I do this?
Do you use a translation service like weblate or transifex? Or I have to send the translations to this repository.
Good luck

**Comment by gujjwal00** [comment]
Hi @eshagh79 , happy to see AVNC being useful to you.

I have not setup any translation service yet. I will look into setting something up for better translation experience.

In the meantime, you can send a PR here in the repo if you're comfortable with it. I am open to whatever works best for you. Please let me know if you need help with something.

**Comment by gujjwal00** [comment]
Weblate project for AVNC is now live & approved: https://hosted.weblate.org/engage/avnc/
