### ISSUE TITLE
Allow Alt+Tab (and other special keys) to be captured by the remote machine

### ISSUE THREAD

**Issue by azrielgold** [gujjwal00/avnc#37]
Currently, when using AVNC with an external physical keyboard, the Alt+Tab keyboard sequence is captured by the phone (client) and not by the remote machine (the VNC server).

While this behavior is desired in some cases, in other cases it gets in the way of seamless remote work. For example, when using AVNC with Samsung DeX, the Alt+Tab sequence triggers the DeX app switcher instead of the app switcher in the remote machine. This gets in the way of working smoothly with the remote machine.

Perhaps a more general option to toggle capturing special keys (Alt+Tab, Alt+Shift, WinKey, WinKey+Tab, WinKey+E, etc.) remolty or locally is the best solution for this issue.

Thanks for your great app.

**Comment by gujjwal00** [comment]
I will look into it, but it is possible that there is no way to capture these keystrokes. AVNC itself is already forwarding all received keystrokes directly to server.

**Comment by azrielgold** [comment]
Thanks for the response!

I'll note that some other apps do capture the keystrokes I mentioned when used in DeX. Both the Microsoft RDP app (https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx) and the VMware Horizon app (https://play.google.com/store/apps/details?id=com.vmware.view.client.android) capture Alt+Tab and the Windows Key. Horizon also captures Alt+Shift while RDP does not.

The VNC system itself seems to support sending special keystrokes, since the RealVNC Windows client (VNC Viewer) has an option called SendSpecialKeys under File > Preferences... > Expert (see: https://help.realvnc.com/hc/en-us/articles/360002254618-VNC-Viewer-Parameter-Reference-#viewer-sendspecialkeys).

**Comment by gujjwal00** [comment]
Hi @azrielgold , can you please test this APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7789847/app-debug.zip)

Please try all keystrokes you mentioned in issue description. 
Also, grab the Logs from `Settings => Tools => Debugging`, and paste them here.

**Comment by zequinh4** [comment]
Hello my friend @gujjwal00. Excuse the intrusion @azrielgold , however it is a subject that also interests me. I noticed that the application was translated to Portuguese (most of it) and that it added the possibility to hide the android cursor itself. I loved it!. Follow the logs as requested. When we press for example "Alt+Tab" the command is carried out in Dex and not in AVNC. Hugs!
[log.txt](https://github.com/gujjwal00/avnc/files/7790081/log.txt)

https://user-images.githubusercontent.com/51301335/147691157-c4a109c8-9eaf-4742-933f-bb0c72e14635.mp4

**Comment by gujjwal00** [comment]
@zequinh4 Please try this APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7790230/app-debug.zip)

And please paste the logs here (even if meta keys are captured correctly).

**Comment by zequinh4** [comment]
Apparently "Alt + Tab" works perfectly. CMD ("Windows") key too. The txt file follows.

[log (1).txt](https://github.com/gujjwal00/avnc/files/7790275/log.1.txt)

**Comment by zequinh4** [comment]
@gujjwal00 
Fixing the CMD ("Windows") key does not work. It does not dictate function to AVNC or the android system.



https://user-images.githubusercontent.com/51301335/147696243-acf16039-072e-457d-9231-3219bfb021c7.mp4

**Comment by azrielgold** [comment]
Attached is the log file you asked for.

1. I tried the Alt-Tab key sequence which did not work (it triggered the DeX app switcher rather than the Linux one in the VNC server).
2. I also pressed the WinKey which triggered the DeX app screen.
3. Finally, I pressed the Alt+Shift keystroke and it triggered the Android/Samsung keyboard language switcher but that sequence was also sent to the server so I think this sequence works fine.

So just Alt+Tab and any keystroke that involves the WinKey are problematic.

Thanks again for all your work!

[log.txt](https://github.com/gujjwal00/avnc/files/7790465/log.txt)

**Comment by zequinh4** [comment]
Hello my friend @azrielgold . I test using this apk. For me it worked ALT-TAB without problems. However, WinKey(CMD) does not work! 



> @zequinh4 Please try this APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7790230/app-debug.zip)
> 
> And please paste the logs here (even if meta keys are captured correctly).

**Comment by gujjwal00** [comment]
@azrielgold , as @zequinh4 mentioned, please use the 2nd APK.

**Comment by gujjwal00** [comment]
Ignore my previous comment.

Can both of you please test this APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7791215/app-debug.zip)

It should fix the Windows/CMD key issue.

**Comment by azrielgold** [comment]
@gujjwal00 I tried the new APK and it's great.
Now, all the keystrokes that I am testing work perfectly, as expected.
Alt+Tab, the Windows key alone, WinKey+E (or WinKey+<any other key> are all captured by the remote server and not by the local client, exactly as it should be. Thanks so much!

Would you like me to send you the log with this apk too, or is there no need for that?

**Comment by gujjwal00** [comment]
No need for the logs now, previous logs were enough.

**Comment by gujjwal00** [comment]
Fixed in https://github.com/gujjwal00/avnc/commit/c5b4b2b720775039df2dc1e7fa7802cc1ea7d27a.

Please note that these keys will be captured only when:
- Samsung DeX is supported
- DeX mode is currently active
- VNC session is active
