### ISSUE TITLE
Translation error to Portuguese Brazil

### ISSUE THREAD

**Issue by zequinh4** [gujjwal00/avnc#39]
Hello my friend @gujjwal00 . I've already made some suggestions on the translation site, but I don't know how it works. Here are some suggestions for errors and incomplete translations! I'm glad to be able to help with your magnificent app.

![Screenshot_20220102-193448_AVNC](https://user-images.githubusercontent.com/51301335/147891237-0646a28f-3f80-4e44-a550-cce074d6d3c9.jpg)

Follow System Theme = Seguir Tema do Sistema
Dark = Modo Escuro
Light = Modo Claro

![Screenshot_20220102-193501_AVNC](https://user-images.githubusercontent.com/51301335/147891267-c6c551f3-7107-4326-8ccd-6ee8d74f16d4.jpg)

Start = Início
End = Final

![Screenshot_20220102-193521_AVNC](https://user-images.githubusercontent.com/51301335/147891275-0d137a94-67ef-4a59-81a4-ca7c1a8930d1.jpg)

In Brazilian Portuguese we do not have an equivalent term for "Picture-in-Picture" so they are used the same in English and we do not translate the expression. So the correct one is "Picture-in-Picture" and not "Picture-in-Picture".

![Screenshot_20220102-193547_AVNC](https://user-images.githubusercontent.com/51301335/147891321-353e09d0-98c8-4198-b9f5-42ba55a0dd59.jpg)

Hide Local (Android) Cursor = Ocultar Cursor do Android

![Screenshot_20220102-193606_AVNC](https://user-images.githubusercontent.com/51301335/147891361-385c52ae-c6c1-420a-b5e6-7d673507a35d.jpg)

Clear = Limpar

![Screenshot_20220102-215547_AVNC.jpg](https://user-images.githubusercontent.com/51301335/147893737-095101ee-5b2a-498a-9a60-9ea21a9db074.jpg)

Full Immersive mode = Modo totalmente imersivo
Hides all system Bars... = Oculta todas as barras do sistema no modo tela cheia

**Comment by gujjwal00** [comment]
Thanks @zequinh4. Updated in https://github.com/gujjwal00/avnc/commit/fd2314f0044af3db7a975f67c729b7094677b414

You should be logged into Weblate (you can login via GitHub), to commit translations. Anonymous users can only submit suggestions. You will also get proper attribution if you are logged in. Once you update translations there, I will merge them here after some time.

Or, you can directly edit the [strings.xml](https://github.com/gujjwal00/avnc/blob/master/app/src/main/res/values-pt-rBR/strings.xml) file, here on GitHub.  Navigate to the file, and click on the pencil icon ![image](https://user-images.githubusercontent.com/27951674/147896709-19215ccb-d5a3-4d90-a743-11e675b21f55.png) to start editing. Once you are done, commit the changes. It will open a PR in this repo.
