### ISSUE TITLE
FR: sort list of servers

### ISSUE THREAD

**Issue by Buntbart** [gujjwal00/avnc#4]
Thank you very much for AVNC!! And also thank you for putting it on F-Droid!

This is by far the best VNC-Client for Android I've seen so far.

I would appreciate very much if it was possible to manually sort the list of known servers. As an alternative it would be helpful to sort the servers in alphabetical order.

Thank you!

**Comment by gujjwal00** [comment]
Glad you like it!

Sorting alphabetically by name is relatively easy to implement as we can simply pass the required order to database query.

Sorting manually would require implementation of drag-n-drop in server list and the logic to save/update prefered positions. I would like to avoid this route if this is not somethig critical to you. As a poor man's alternative for this, you could  (ab)use the 'Duplicate' option to create copies in preferred order and then remove the originals .

**Comment by gujjwal00** [comment]
Hi @Buntbart , I have implemented a preference to sort saved servers alphabetically (https://github.com/gujjwal00/avnc/commit/7cfc4d6915f2efa3c700380ea7070813807c589f).
You can now enable `Settings -> Interface -> Sort Server List` to sort servers.

You can use this [debug apk](https://github.com/gujjwal00/avnc/suites/4031275991/artifacts/102016182) to test it out.
If you have any feedback, let me know.

**Comment by gujjwal00** [comment]
OK.

I am closing this issue now, but feel free to reopen it if you encounter a problem.
