### ISSUE TITLE
Remove additional comments in Persian

### ISSUE THREAD

**Issue by eshagh79** [gujjwal00/avnc#46]
Hello
There is no need for this comment in Persian anymore. Because you have modified the strings, no longer need to use directional control characters.
https://github.com/gujjwal00/avnc/blob/ef107b1fd3078143451ba6b3c221e76905354e02/app/src/main/res/values-fa/strings.xml#L80
Please delete it the next time you import these new translations from the weblate.

**Comment by gujjwal00** [comment]
Thanks, will do.

Side note: Due to email difference with Weblate, your contributions are not fully reflected on GitHub.
