### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by user8446** [gujjwal00/avnc#48]
Hello,

Thank you for the great VNC client app... I love the VNC/SSH integration.  I'm using it with TightVNC & OpenSSH.

I looked for a donation link on F-Droid, the app itself, and here on GitHub and couldn't find a donation link. I always try to "buy a coffee" as a thank you and to help development.

**Comment by gujjwal00** [comment]
I am glad you like AVNC. And thank you for your support & consideration, really appreciate it.

I would kindly invite you to first consider supporting the libraries used by AVNC. Although I have put a lot of effort in AVNC, I still think it would not have the same features and performance without them. I can recommend the following libraries:

- https://github.com/LibVNC/libvncserver
- https://github.com/libjpeg-turbo/libjpeg-turbo


I am not opposed to receiving donations for AVNC, and can setup something if you would like that.

**Comment by user8446** [comment]
I just that by having a donation link it gives users a way to either say thanks or to help if they are unable to contribute code.
Thanks for pointing out those libs, I just sent them both coffee as well!

**Comment by user8446** [comment]
Ok I just tried to donate via PayPal through Liberapay and received:

```
Failure
The payment processor PayPal returned an error: “PAYEE_ACCOUNT_RESTRICTED: The merchant account is restricted. | PayPal debug_id: 62cf34056a749”.
```

I'll try again later, maybe it's not fully active yet.

**Comment by gujjwal00** [comment]
It looks like I will have to complete full KYC with Paypal and upgrade to business account, before I can accept international payments in India. I will let you know when its done.

**Comment by user8446** [comment]
You can also just link your direct PayPal and then people can send direct without you having to upgrade to a business account.

**Comment by gujjwal00** [comment]
Ok, here is the link: https://paypal.me/gujjwal00
(Same username & profile pic as GitHub)

**Comment by user8446** [comment]
PayPal errors out with: Sorry, this recipient can’t accept payments right now.

Looks like they are making it difficult to send you those Kingfishers :)

**Comment by gujjwal00** [comment]
Yeah, I had a feeling they won't allow it.

Its because of regulations here. I have been reading on this lately, and it looks like OSS donations were not given much (if any) thought. You have to either export goods/services as a business, or register as charitable organization with government under FCRA. FCRA requires dedicated bank account & reporting, and registration will probably cost more than I will ever receive. Its more targeted toward larger NGOs & religious charities. 

GitHub Sponsors looks promising in this regard but still is in beta for India. I will try with Paypal (or any other donation platforms?), and see how it goes.

**Comment by user8446** [comment]
Maybe check out Open Collective & Ko-fi as well

**Comment by gujjwal00** [comment]
Ok, done with upgrade to Paypal business account. I have also opened an Stripe account and connected it to Liberapay. Stripe seems to have lower transaction fee, but there are some bug reports about payment failure to Indian Stripe accounts on Liberapay. Hopefully one of them will work.

**Comment by gujjwal00** [comment]
Thanks @user8446 , really appreciate it. And yes, the coffee will definitely taste sweeter :) 
I will post the link on both places.
