### ISSUE TITLE
Translations in Portuguese Brazil

### ISSUE THREAD

**Issue by zequinh4** [gujjwal00/avnc#55]
Hello my friend @gujjwal00 . Sorry to message you here. I still don't quite understand how translations work. Below are some translations of the new content added. Hugs.

![Screenshot_20220205-212125_AVNC](https://user-images.githubusercontent.com/51301335/152663561-0378b17c-3674-4fbc-a0e3-2efab88126ba.jpg)

Default Security = Segurança Padrão
None = Nenhuma

![Screenshot_20220205-212138_AVNC](https://user-images.githubusercontent.com/51301335/152663674-b3843747-e5a4-4064-8b77-012386d33906.jpg)

Direct Touch = Toque direto
Do actions at touch-point = Faça ações diretas com o toque na tela
Do actions at point = O toque na tela controla o cursor

![Screenshot_20220205-213946_Opera](https://user-images.githubusercontent.com/51301335/152663780-cc626481-63dd-449c-ac68-903b08778c0d.jpg)

Autorun = Executar automaticamente
Discover servers while on homepage = Descubra automaticamente servidores enquanto estiver na página inicial
Hightlisht rediscovered servers = Destaque servidores redescobertos

![Screenshot_20220205-214522_AVNC](https://user-images.githubusercontent.com/51301335/152663893-14b5f426-13c9-4577-b14b-c71501761212.jpg)

The correct one for fullscreen translation is: "Usar tela cheia" and not: "Usar tela completa"

**Comment by gujjwal00** [comment]
Thanks @zequinh4 .

**Comment by zequinh4** [comment]
> >The correct one for fullscreen translation is: "Usar tela cheia" and not: "Usar tela completa"
> 
> `Use Fullscreen` was changed to `Fullscreen` during English string cleanup. So would the new translation be `Tela cheia` ?

Hello my friend. Yes the translation of Fullscreen is "Tela Cheia"

**Comment by gujjwal00** [comment]
Updated. Thanks @zequinh4 .
