### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by zequinh4** [gujjwal00/avnc#56]
Hello again my friend @gujjwal00 . I was testing the function of controlling the cursor via touch, however, I could not scroll the content using two fingers. Regardless of the relationship setting, the two fingers zoom in or out of the remote server area. Follow the video demonstrating. Hugs

https://user-images.githubusercontent.com/51301335/152664257-9ddb02d8-ce30-44a7-b131-704a70bae28e.mp4

**Comment by gujjwal00** [comment]
I will take a look.

**Comment by gujjwal00** [comment]
Hi @zequinh4, sorry for late reply.
I am unable to reproduce the issue. For me, two-finger swipe will scroll remote content irrespective of Direct Touch mode.

In the demo you posted, there is "nothing to scroll" at browser start page, so even if AVNC sent scroll events, those will not have any effect. Can you please try with a website (like GitHub), or a large text file?

Tip: If your screen is large enough and you don't normally zoom in/out, you can set both `Minimum Zoom` & `Maximum Zoom` to 100%. This way, frame size won't change during two-finger swipe, and you will have much better experience with remote scrolling.

**Comment by zequinh4** [comment]
Hello again @gujjwal00 . It worked by changing the Minimum Zoom & Maximum Zoom to 100%. Thanks!
