### ISSUE TITLE
(Enhancement) (feature request) Move screen as cursor goes.

### ISSUE THREAD

**Issue by Anonymous2716** [gujjwal00/avnc#58]
Nice interface , clear resulation and smoothness a combination in my opinion its better than other vnc client apps. But in zoomed screen as i move the cursor the screen doesn't move (as it does in realvnc app).  Guess its under development .Expect the feature in near future.

**Comment by gujjwal00** [comment]
Yeah, touchpad mode was implemented recently so there is still room for improvement. I will try to implement this feature, but it probably won't happen this month.

**Comment by gujjwal00** [comment]
Hi @Anonymous2716 , this has been implemented. Frame will now follow the cursor when 'Direct touch' is disabled.
You can use the following APK to test it: https://github.com/gujjwal00/avnc/suites/5812767723/artifacts/194574168

**Comment by Anonymous2716** [comment]
@gujjwal00 awesome its perfect. Thanks for your time and for the  app.

**Comment by gujjwal00** [comment]
You can watch #69 for quality control management.

**Comment by Anonymous2716** [comment]
Alright thanks.

**Comment by PureIncompetence** [comment]
I totally agree regarding this app: definitely the best FOSS VNC viewer on Android so far.
Like the creator of that issue I also came here from RealVNC viewer and missed the feature he described. In said app though its implemented combined with the "touchpad"-style cursor behaviour, which does not seem to be possible in aVNC so far, if I'm not mistaken.
To me (and probably some other users coming from realvnc viewer) having this feature implemented in the "touchscreen" cursor mode too would make aVNC perfect.

**Comment by gujjwal00** [comment]
Hi @PureIncompetence , thank you for kind words.

Can you please explain a bit more about what you are missing? For context, AVNC has two main touch modes:

- **Direct touch ON** This is the typical Android-style behavior, and clicks happen on touch point. 
-  **Direct touch OFF** This is more like a laptop touchpad, swiping moves the pointer and clicks happen wherever the pointer is. Frame/Viewer will follow the cursor in this mode.

You can change the touch mode in settings.

**Comment by PureIncompetence** [comment]
Hi @gujjwal00 , I will try to explain it as understandable as I'm able to.

What I was describing was regarding to the 'Direct touch OFF'-mode.
When the view was somewhat zoomed in (so I wasn't seeing the whole remote screen on my phone), the part I was seeing was moving with the cursor, keeping it centered on the local screen, as long as possible / until I reached the edges of the remote screen.
The difference I noticed to your 'Direct touch OFF'-mode: In aVNC I need to move the cursor to edge to change make the frame/viewer follow that direction.

I will attach a screen recording to make it clear. First I will remote control my computer using realvnc-viewer, in the second half of the video I'm using AVNC:

https://user-images.githubusercontent.com/66217283/165918004-6d2dbffc-f6c9-4352-890d-94e4470d1e71.mp4

**Comment by Anonymous2716** [comment]
This is exactly what I was talking about.

**Comment by gujjwal00** [comment]
Thanks for the video, now I understand the issue. I will try to implement this behavior.

**Comment by gujjwal00** [comment]
Can you both please test the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/8596807/app-debug.zip)
Pointer should now stay in center as long as possible.

**Comment by Anonymous2716** [comment]
Yes thanks thats awesome. Might need to adjust sensitivity in the settings and it looks perfect in my view . also need a little resolution improvement.

**Comment by PureIncompetence** [comment]
Yes, thats the cursor behaviour we described. Imho Its much more convenient to use than it was before.
Thank you.
