### ISSUE TITLE
Can you add two finger tap gesture for mouse right click?

### ISSUE THREAD

**Issue by aliyoge** [gujjwal00/avnc#6]
Because if i enable drag gesture, then i can't tigger long press for mouse right click.

**Comment by gujjwal00** [comment]
You actually *can* trigger the right click in this case. You just have to **lift** your finger after long press, and not move it. When you set an action for drag gesture in settings and then long press during a session, AVNC waits for your next move to decide whether its a simple long press or a drag gesture (and yes, I know its not very intuitive).

This is the reason why drag gesture is not assigned an action by default as I was worried about the discoverability.

Two finger tap is not detected by Android's `GestureDetector`, which is used by AVNC. I can't promise anything but I will look into detecting it manually, and will add a preference for it if it can be detected reliably.

**Comment by gujjwal00** [comment]
So the detection works reliably with the current algorithm I have (we can even detect 3/4 finger taps). 

Now the question is, where to do the click:
-  Touch-point of first finger
-  Touch-point of second finger
-  Middle of both touch-points
-  Wherever the pointer is  (currently not possible as AVNC does not have this info)

**Comment by gujjwal00** [comment]
I have added 2-finger Tap gesture (https://github.com/gujjwal00/avnc/commit/a7d939d9534cc1401c0061a2c52ccf651c4d582e):
-  Currently the default action for this gesture is to open keyboard. I find it useful that I can tap with both thumbs to open keyboard and start typing straight away.
- You can change the action to Right-Click. Click will be sent to the touchpoint of first finger.
- I am marking it Experimental for this release.

Any feedback is welcome! You can use [this apk](https://github.com/gujjwal00/avnc/suites/4212242193/artifacts/108827107) to test it out (it can be installed alongside existing app).
