### ISSUE TITLE
Suggestion: Make viewer follow where mouse go

### ISSUE THREAD

**Issue by Yonle** [gujjwal00/avnc#64]
While zooming, The viewer does not follow where the cursor go. So this feature may be good to be added.

**Comment by gujjwal00** [comment]
Please see #58 .

**Comment by gujjwal00** [comment]
Hi @Yonle  , this has been implemented. Frame will now follow the cursor when 'Direct touch' is disabled.
You can use the following APK to test it: https://github.com/gujjwal00/avnc/suites/5812767723/artifacts/194574168

**Comment by Yonle** [comment]
> Hi @Yonle , this has been implemented. Frame will now follow the cursor when 'Direct touch' is disabled. You can use the following APK to test it: https://github.com/gujjwal00/avnc/suites/5812767723/artifacts/194574168

Worked well!

**Comment by gujjwal00** [comment]
AVNC v1.8.0 is now available on F-Droid.
