### ISSUE TITLE
remote content scrolling is too sensitive for me

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gujjwal00/avnc#65]
Hi,

I have been using your great (!) app to highlight my pdf directly on my phone.

The only issue I noticed so far is that the remote content scrolling is *super* sensitive.

Could you consider either toning it down or making it user adjustable? If not, do you know of any workaround?

Anyway thanks a lot for this app :)

**Comment by gujjwal00** [comment]
Yes, a preference can be added for sensitivity. Just give me some time.

**Comment by gujjwal00** [comment]
Implemented in https://github.com/gujjwal00/avnc/commit/127d1325a9d41e019a58857dce08f9b48db5fe81.
Test APK: https://github.com/gujjwal00/avnc/suites/5626840231/artifacts/183368768

@thiswillbeyourgithub please test the APK linked above. You can modify the sensitivity in `Settings -> Input -> Gestures`.

**Comment by thiswillbeyourgithub** [comment]
Hi!

Thanks a lot for the quick response :)

I just tested it and unfortunately I'm not sure it makes that big of a difference. I think the issue is not actually "speed" but rather a too high "acceleration" if you get what I mean.

In other words, dragging across the screen just an inch makes you end up uncontrollably far from the starting point.

**Comment by gujjwal00** [comment]
In that case, you will have to change the host/server settings.  AVNC simply generates Mouse Wheel Up/Down/Left/Right events. How much content is scrolled for a single event depends on the host.

If I recall correctly, both Windows & Linux distros have settings to control this behavior.

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot!

**Comment by gujjwal00** [comment]
So I will remove the preference then (unless someone has a better usecase for it). I don't want to have unnecessary/ineffective preference, and as shown here, this setting is handled more effectively on the host side.

**Comment by RuofengX** [comment]
Hi! I am using AVNC on my android tablet. I also met the scoll speed issue. I am using tigerVNC with xfce as a windows manager. And I could not find the scoll speed setting in my host system preference. 

I think the scolling speed setting is not totally unnecessary,  and it could be a workaround in some rare cases, for another example that you have to scoll to the setting but the speed is to fast. Maybe I think it is better to add this feature in *advance setting* or other space.

**Comment by gujjwal00** [comment]
Hi @RuofengX, since then I have added another preference named 'Swipe sensitivity'. It is similar to the preference mentioned here, but more general.
