### ISSUE TITLE
Feature request: quality and color settings

### ISSUE THREAD

**Issue by jose1711** [gujjwal00/avnc#69]
Could you please add per-connection quality and color-depth settings to the application?

**Comment by gujjwal00** [comment]
I am already working on quality control. Basic work is done, just need some finishing.

I will not add color-depth setting though. AVNC is using OpenGL ES, which already limits the possible options to only 16bit & 24bit, and upcoming support for client-side cursor rendering makes it pretty hard to support 16bit.

**Comment by jose1711** [comment]
> I am already working on quality control. Basic work is done, just need some finishing.

:partying_face: 

> I will not add color-depth setting though. AVNC is using OpenGL ES, which already limits the possible options to only 16bit & 24bit, and upcoming support for client-side cursor rendering makes it pretty hard to support 16bit.

yes, that makes perfect sense. thank you.

**Comment by gujjwal00** [comment]
It got delayed quite a bit, but I have finally finished it. You can now change image quality in advanced server options:
##
![image](https://user-images.githubusercontent.com/27951674/198047637-b47d485d-8839-4a25-8c63-e7a25ed4a743.png)
##

Test APK:  https://github.com/gujjwal00/avnc/suites/8969083439/artifacts/412379656

It will be available in next release.

**Comment by gujjwal00** [comment]
[v2.0.0](https://github.com/gujjwal00/avnc/releases/tag/v2.0.0) is now available.
