### ISSUE TITLE
Pi

### ISSUE THREAD

**Issue by Gottarocket** [gujjwal00/avnc#7]
Cant connect to pi change all auth on advanced settings but shows same issue disconnected error

**Comment by gujjwal00** [comment]
Can you please paste the logs again ( with `VncAuth` enabled in the server)?

AVNC, as it uses LibVNCClient, supports many security types. Issue here is that security types used by RealVNC server seems to be proprietary ( I could not find much information as to how they work). So they are only supported by RealVNC client.
