### ISSUE TITLE
Force portrait and force landscape mode

### ISSUE THREAD

**Issue by gerrishons** [gujjwal00/avnc#74]
This is handsdown the best vnc app ive used, however i have a new feature to request: the force portrait and force landscape mode

**Comment by gujjwal00** [comment]
Thanks, I will look into it.

**Comment by gujjwal00** [comment]
Hi @gerrishons, I have implemented a preference for the screen orientation (`Settings => Viewer => Screen orientation`).

You can test this APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/8702232/app-debug.zip)
Let me know if it works correctly for you.

Thank you.
