### ISSUE TITLE
Feature Request: option to disable "natural scrolling" / to reverse scrolling direction

### ISSUE THREAD

**Issue by PureIncompetence** [gujjwal00/avnc#75]
When I activate remote content scrolling via 'Input' -> 'Two-finger swipe' -> 'Scroll remote content' the remote content is scrolling down when I swipe up and vice versa. Afaik that's called 'natural scrolling'. For me and probably others it would be helpful being able to choose the scrolling direction which we regard as intuitive.

**Comment by gujjwal00** [comment]
It should be pretty simple to implement (just have to flip the sign of two variables), so I don't have any problem with it.

My only concern is UI complexity of settings - i.e. Input Settings page is already a bit crowded, and I am slightly cautious about adding new preferences there. So instead of making the new preference always visible, I think it would be better if new pref is only visible when `Scroll remote content` option is used. Let me figure out if this is possible.

**Comment by gujjwal00** [comment]
One more question: does 'natural scrolling' only affect the vertical motion?

**Comment by gujjwal00** [comment]
> I honestly had to try that. I can't remeber when I last used vertical scrolling inside a VNC session.

I may be misunderstanding something, but if you don't use vertical scrolling then this feature seems unnecessary to me?

> Appearently the two-finger-scrolling doesn't work vertically at all, in no direction.

Again, I may be missing something, but your initial comment suggests that setting 'Two-finger swipe' to  'Scroll remote content' was working.

**Comment by gujjwal00** [comment]
No problem! 

I am attaching an APK here:  [app-debug.zip](https://github.com/gujjwal00/avnc/files/8635535/app-debug.zip)

Please test it out when you have some time. 'Natural scrolling' preference should become visible when remote scrolling is used. It is 'ON' by default to preserve current behavior. 

About horizontal scrolling: Its working correctly on my side. Please double-check that the cursor is *over* scroll area, as scroll events are sent at cursor's position.

**Comment by sudomain** [comment]
Could natural scrolling please be renamed to something more intuitive like "invert vertical scrolling"? I wasn't familiar with natural scrolling and had to search it and then come here. Not a big deal if not,  I know what it is now, but I imagine others will have to look it up also :)

**Comment by gujjwal00** [comment]
After trying to come up with a short & clear enough summary for both On & Off states, and failing miserably, I am just going with 'Invert vertical scrolling' here. It will be disabled by default. Any changes you have made to 'Natural scrolling' until now will be automatically migrated.
