### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [gujjwal00/avnc#76]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 78 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on AVNC (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve AVNC's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by gujjwal00** [comment]
To be honest, this looks like automated spam. Also your tool and AVNC both being freely available, anyone can do this analysis, so I don't understand the "secrecy" here.

But in any case, you can reach me at: avnc.help@gmail.com

**Comment by misterAnderson90** [comment]
Hello @gujjwal00, 

I'm sorry for not responding to you before. I just sent you an e-mail with the private gists. Can you please evaluate the gists with your perceptions? Please let me know if you have any doubts.

**Comment by gujjwal00** [comment]
Hi @misterAnderson90, none of the issues you have described in the mail is related to AVNC itself. They are triggered by Connectbot's SSH library used in AVNC.

I have no control over this library, and no idea how valid your issues are.  I suggest you contact the library authors, but I doubt you will get a response there.

**Comment by gujjwal00** [comment]
Just a quick feedback:

IMHO, using final APK for analysis has some drawbacks. You have no way to differentiate between actual app code and third-party libraries. This results in obviously duplicated, and misdirected effort on your part. And as you are already aware, the context (line numbers, file names etc.) of the issue is often lost in optimized APK.

Good luck with you PhD and research :+1: .
