### ISSUE TITLE
Enhancement idea: option to show toolbar (permanently?) on top/bottom in portrait mode

### ISSUE THREAD

**Issue by PureIncompetence** [gujjwal00/avnc#78]
In my opinion the wording for current options on where to align the toolbar (start/end) aren't optimal, left/right might be be more comprehensible.
Additionally it might be useful for portrait mode to align the toolbar to the bottom of the screen, especially if the content isn't zoomed in enough to fill 100% of the screen. (I'll attach a screenhot to show what I mean.)
![screenshot_toolbar_top+bottom](https://user-images.githubusercontent.com/66217283/167196075-c896ad39-b2c1-4877-a66c-68963ea90aaa.jpg)

Using this space for the toolbar would enable it to stay there permanently, even while controlling the remote system, which might be more convenient to use, as it wouldn't be necessary to use a gesture each time you need the keyboard or extra keys.

Another possibillity to show the toolbar permanently would be making it semi-transparent (being 100% visible if it wouldn't cover any of the remote screen's content and becoming e.g. 30% or 50% visible if it otherwise would). In my eyes this would be the preferred solution, even though having the toolbar at the bottom in portrait mode might still be neat from an ergonomy perspective (easier to reach with the thumb).

**Comment by gujjwal00** [comment]
> In my opinion the wording for current options on where to align the toolbar (start/end) aren't optimal, left/right might be be more comprehensible.

This is a result of me trying to be "technically correct". When alignment is 'Start', toolbar will align with left-edge for LTR languages like English, while it will align with right-edge when in RTL mode, e.g. with Persian. We can force the left-right alignment irrespective of the layout mode, but I tried to be consistent with other UI elements.


As for the top-bottom toolbar position, it is not possible with current code. Toolbar is currently implemented using `DrawerLayout`, like the one on home page of AVNC.  `DrawerLayout` handles toolbar visibility, animation and gesture detection. Unfortunately,  it only supports left/right alignment.

I will look into other possible solutions for this, but I can't promise anything.

PS: Sorry for late reply.
