### ISSUE TITLE
S-Pen not functional

### ISSUE THREAD

**Issue by didierm** [gujjwal00/avnc#8]
Thank you for what looks like a very promising app.

I use VNC to connect to localhost, which is launched by an Xvnc session inside a Fedora distro deployment via Termux : this allows to run (aarch64) Linux applications almost natively on Android.

My main interest is running note-taking apps not available for Android (mainly Xournal++ and Okular).
This is on a Galaxy Tab S6 Lite with S-Pen (capacitive touchscreen, + EMR layer for the S-Pen).
This works quite well with e.g. [MultiVNC](https://github.com/bk138/multivnc).

With avnc, the S-Pen actions are only partly registered : 
* with **"Mouse Passthrough" enabled** : 
 * mouse pointer follows the pen tip when dragging/drawing with the pen ;
 * no mouse clicks registered when touching, double touching, long pressing or dragging the pen tip on the surface.
* with **"Mouse Passthrough" disabled** : 
 * mouse pointer moves to the pen tip location when touching the surface (discrete touches, no dragging/drawing) 
 * no mouse clicks registered when double touching, long pressing or dragging the pen tip on the surface.

IMO, the actual drawing/handwriting is done by registering e.g. left-mouse click while dragging.

Not sure whether this is the solution, but maybe [Left Click] actions should be attributable to "1 Finger Swipe" and/or "Drag (Long Press then Swipe)" ?

**Comment by gujjwal00** [comment]
v1.2.0 is available of F-Droid including support for stylus devices.
