### ISSUE TITLE
我现在用的小米12手机，可以打开，同事用的小米10，主界面可以打开，点进去具体链接就闪退了

### ISSUE THREAD

**Issue by HeliusHao** [gujjwal00/avnc#84]
我邮箱 14378005@qq.com

**Comment by HeliusHao** [comment]
> 很高兴知道你喜欢 AVNC👍.
> 
> 为了识别和解决问题，我需要您的帮助，因为我没有小米 10 设备。
> 
> 请在您同事的设备上按照以下步骤操作：
> 
> 1. 打开 AVNC 并单击特定链接。
> 2. 如果 AVNC 崩溃，请重新打开它。
> 3. 打开 AVNC 设置⚙
> 4. 转到“工具 => 日志”
> 5. 复制日志
> 6. 将日志粘贴到 GitHub 上
> 
> 谢谢。

The latest log file, please check the attachment, thank you
[New log.txt](https://github.com/gujjwal00/avnc/files/8857045/New.log.txt)

**Comment by gujjwal00** [comment]
Thanks for the logs @HeliusHao.

It appears that native library used by AVNC fails to load correctly:
```python
06-07 16:04:00.712  9754  9754 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-vnc.so" not found
06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1656)
06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at com.gaurav.avnc.vnc.VncClient.<clinit>(VncClient.kt:1)
06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at com.gaurav.avnc.viewmodel.VncViewModel.<init>(VncViewModel.kt:2)
```

This is somewhat surprising because it is almost impossible to happen. Only possible reason I can think of is if an APK intended for a particular architecture (e.g. x86) is installed on a different device (e.g. arm).

@HeliusHao How did your colleague install AVNC? Did they use an APK file?

**Comment by HeliusHao** [comment]
I first downloaded it from the Google store and then sent the AVNC APK file to my colleagues


Helius
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gujjwal00/avnc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 中午12:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gujjwal00/avnc] 我现在用的小米12手机，可以打开，同事用的小米10，主界面可以打开，点进去具体链接就闪退了 (Issue #84)





 
Thanks for the logs @HeliusHao.
 
It appears that native library used by AVNC fails to load correctly:
 06-07 16:04:00.712  9754  9754 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-vnc.so" not found 06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077) 06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998) 06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1656) 06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at com.gaurav.avnc.vnc.VncClient.<clinit&gt;(VncClient.kt:1) 06-07 16:04:00.712  9754  9754 E AndroidRuntime: 	at com.gaurav.avnc.viewmodel.VncViewModel.<init&gt;(VncViewModel.kt:2)
 
This is somewhat surprising because it is almost impossible to happen. Only possible reason I can think of is if an APK intended for a particular architecture (e.g. x86) is installed on a different device (e.g. arm).
 
@HeliusHao How did your colleague install AVNC? Did they use an APK file?

**Comment by gujjwal00** [comment]
Yeah, that is probably why AVNC is failing on your colleague's device.

To reduce download size (and size of installed app), I have enabled APK splitting (via app bundles). So default APK download from Play Store contains native library for a single ABI, and it can only be used on that ABI.

Ideally, your colleague should install directly from Play Store which will select correct version. Otherwise, I can provide a universal APK to you which will work correctly on every device.

**Comment by HeliusHao** [comment]
Please provide me with a universal APK file. Thank you. Can you send me an email? thinks。




Helius
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gujjwal00/avnc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gujjwal00/avnc] 我现在用的小米12手机，可以打开，同事用的小米10，主界面可以打开，点进去具体链接就闪退了 (Issue #84)





 
Yeah, that is probably why AVNC is failing on your colleague's device.
 
To reduce download size (and size of installed app), I have enabled APK splitting (via app bundles). So default APK download from Play Store contains native library for a single ABI, and it can only be used on that ABI.
 
Ideally, your colleague should install directly from Play Store which will select correct version. Otherwise, I can provide a universal APK to you which will work correctly on every device.

**Comment by gujjwal00** [comment]
APK: [avnc.zip](https://github.com/gujjwal00/avnc/files/8884049/avnc.zip)

In future I am will add APK files to GitHub Release section and you can download from there.

**Comment by HeliusHao** [comment]
Thanks a lot for your help.



---原始邮件---
发件人: "Gaurav ***@***.***&gt;
发送时间: 2022年6月11日(周六) 晚上10:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gujjwal00/avnc] 我现在用的小米12手机，可以打开，同事用的小米10，主界面可以打开，点进去具体链接就闪退了 (Issue #84)




 
APK: avnc.zip
 
In future I am will add APK files to GitHub Release section and you can download from there.

**Comment by gujjwal00** [comment]
APKs for all versions are now available on GitHub: https://github.com/gujjwal00/avnc/releases

PS: You can rate/review AVNC on Play Store. Its a new listing, so still very quiet there.
