### ISSUE TITLE
Feature request: Options to disable specific encodings?

### ISSUE THREAD

**Issue by youngshall** [gujjwal00/avnc#87]
I'm using AVNC on a android phone, connecting termux/ubuntu vnc server on the same device.
AVNC is nice and easy to use, but there is one issue: my phone's cpu performance is relative poor, while network speed is good(both vnc client and server are on the same device).
This situation limits my vnc desktop framerate. So I'm wondering, if only raw encoding is used, framerate would certainly go up. 
Since my phone's cpu performance is the bottleneck, removing the cpu-demanding encoding methods would help.
But there aren't any encoding switching options available in AVNC. Can anybody help? Or any suggestion on how to implement such a feature?

**Comment by gujjwal00** [comment]
Hi @youngshall, I am already working on image quality controls (related #69). It also includes an option for raw image quality.

Unfortunately, I haven't found the time to finish it yet. Hopefully, it will be finished in next couple of weeks.

**Comment by youngshall** [comment]
Thanks, sounds great! I'm really looking forward to that!

**Comment by gujjwal00** [comment]
Please see https://github.com/gujjwal00/avnc/issues/69#issuecomment-1292109350

**Comment by gujjwal00** [comment]
Raw encoding is now available in [v2.0.0](https://github.com/gujjwal00/avnc/releases/tag/v2.0.0).

**Comment by youngshall** [comment]
Thanks! That's really helpful to me. Can't wait to try it out.
