### ISSUE TITLE
Mouse Cursor doesn't move in View-only mode. Stays at top-left corner.

### ISSUE THREAD

**Issue by barkoder** [gujjwal00/avnc#89]
AVNC Version 1.9.1 and Version 1.9.2.

It does move and respond normally on non-View-only mode, though.

Thank you so much for this nifty piece of software!

**Comment by gujjwal00** [comment]
Thanks for reporting the issue @barkoder .
I have pushed a fix. If you want, you can test the following APK: https://github.com/gujjwal00/avnc/suites/7830623060/artifacts/331112967

Now, original motivation behind disabling cursor movement was to highlight the fact that remote cursor is actually not moved in view-only mode. But it seems to have broken 'panning' in viewer when Direct touch is off. So for now, I have simply allowed cursor movement in view-only mode, even though no event is being sent to the server. But I think ideally cursor should **not** move in view-only mode, and one-finger swipe should pan the frame even if direct touch is off.

BTW, if you don't mind me asking, how do you use view-only mode? I have always wondered if anyone uses this feature.

**Comment by barkoder** [comment]
I don't mind at all. I am currently temporarily disabled due to an injury. I am lying down on my bed. I am using an older de-googled Android phone(Android 6.0) as my primary display(using AVNC), suspended over my face using a flexible mount attached to the edge of my bed. However, I am literally beside my laptop(VNC Server), using its USB keyboard while it rests on my lap and USB mouse beside my thigh.

I *really need* to see the cursor move on my Android screen when I move my mouse. This feature, as of 1.9.2, is only available on *non*-view-only regular(input allowed) mode. So I'm forced to use the regular mode. This is a problem for the following reasons.

My phone only has an "Auto-Rotate" or "Lock Portrait" mode. Unfortunately, there's no option to "Lock Landscape".
Since my screen is directly above my face, my phone sometimes goes back to portrait on its own.
So I have to reach up to unclamp my phone from its mount and tilt it to get it to switch back to landscape so AVNC shows my 1920x1080 laptop screen fully, and then slowly clamp it back hoping that it doesn't flip back to portrait.
Sometimes, when I try to do this, I inadvertently touch my phone screen and end up forwarding unwanted inputs to my laptop.

Other times, I go to the home screen of my Android phone for different reasons and come back to AVNC and the orientation has, once again, flipped back to portrait, forcing me to carefully unclamp my phone to tilt it back to landscape, risking accidentally forwarding inputs to my laptop.

This is why I need view-only mode **with** visible mouse cursor movement. So I may use AVNC as my primary display while still using my laptop's keyboard and mouse. 
For those who don't wish to see mouse cursor movement in view-only mode, I don't see why there can't be an sub-option in view-only mode that enables or disables cursor movement? Feel free to correct me if this is not possible for some technical reason.

I'd also greatly appreciate a "Stay in landscape/portrait no matter what" option. Overriding any android defaults. So it never goes to portrait/landscape(respectively), even if I leave the app to do something else and come back later. I don't know if I should open a new issue requesting this feature or if this line in this comment suffices. Let me know.

Thanks you very much for the fix @gujjwal00 !

**Comment by gujjwal00** [comment]
Thanks for the explanation, hope you get well soon!

> I'd also greatly appreciate a "Stay in landscape/portrait no matter what" option. Overriding any android defaults. So it never goes to portrait/landscape(respectively), even if I leave the app to do something else and come back later.

This option is already available: **Settings => Viewer => Screen orientation**

PS: You can use the APK I linked above until next version is released.

**Comment by barkoder** [comment]
I can't believe that I didn't see that option for permanent landscape. Thanks.

Just tried the apk. It works great but I have two versions of AVNC on my phone now though. But it's okay, it works great! Thanks again.

**Comment by gujjwal00** [comment]
This is now available in [v2.0.0](https://github.com/gujjwal00/avnc/releases/tag/v2.0.0).
