### ISSUE TITLE
[Feature request] Allow to initiate drag and drop by double tapping without releasing after 2nd tap

### ISSUE THREAD

**Issue by DeSAiRePLYX** [gujjwal00/avnc#94]
This would allow to initiate drag and drop more quickly.
The way I would assume this can be implemented is to add a delay after tapping for the second time. (Much shorter than e.g. the delay to activate drag-n-drop in the current version. Possibly around half of the delay-time for sending a right click, but this is only a rough idea.) If the cursor is moved within this time, activate drag-n-drop until the touch is released again. If you immediately release within this delay, send a double click.

This is basically how it works on my laptop's touchpad, which seems faster and more convenient than how it's done in avnc right now.

**Comment by gujjwal00** [comment]
Hi @DeSAiRePLYX , if we can reliably detect double-tap-swipe without affecting other gestures, I will implement it. But this will probably have to wait for sometime because I am currently focused on fixing current issues and finishing next version.

**Comment by gujjwal00** [comment]
'Double tap and swipe' gesture is now implemented (https://github.com/gujjwal00/avnc/commit/781fab53373e31f929711a9fc137d9943881beb3). It will be available in next release. You can use the following APK to test it: https://github.com/gujjwal00/avnc/suites/10070038726/artifacts/490364912

**Comment by DeSAiRePLYX** [comment]
seems to be working great! thank you very much for your work :)

**Comment by gujjwal00** [comment]
[v2.1.0](https://github.com/gujjwal00/avnc/releases/tag/v2.1.0) is now available.
