### ISSUE TITLE
[Feature request] : add Fn keys along extra keys.

### ISSUE THREAD

**Issue by Anonymous2716** [gujjwal00/avnc#95]
It has CTRL TAB ALT Shift etc. I think it will be completed if there is also the F keys. And/or a window/osx/home key .

**Comment by gujjwal00** [comment]
Windows key has already been added (https://github.com/gujjwal00/avnc/commit/a487e4dd94656bf5671bf1cf38b64266a9ca4cbb), and will be available in next version.

I initially skipped Fn keys because the key strip became too long with them.

**Comment by Anonymous2716** [comment]
That's long indeed. But its a scrolling view. And that's great about the windows key.

**Comment by gujjwal00** [comment]
In that case, I will add Fn keys.
What about having two rows of virtual keys: one for default keys, and one for extra keys?

**Comment by Anonymous2716** [comment]
Yeah that might work if not too thick . and / or maybe a toggle button in settings to enable disable them?

**Comment by gujjwal00** [comment]
Well, it will have to be thick to be actually usable, otherwise miss-hits will be too frequent. Adding a pref for this is not as simple due to involvement of scroll views (there will be multiple scroll views). We will probably have to manually manage the layout based on the pref.

For now, I will just add the function key.

**Comment by Anonymous2716** [comment]
If its thick maybe making it half translucent will be better. But for now adding the keys will be great.  Thanks.

**Comment by gujjwal00** [comment]
Implemented in latest release: https://github.com/gujjwal00/avnc/releases/tag/v2.0.0 ( https://github.com/gujjwal00/avnc/commit/581572b6d090014d327491d64ec52423c15a4d0f)

**Comment by Anonymous2716** [comment]
@gujjwal00 thanks.
