### ISSUE TITLE
Meta (super) key should be a toggle

### ISSUE THREAD

**Issue by pop123123123** [gujjwal00/avnc#99]
The virtual super key added in [a487e4d](https://github.com/gujjwal00/avnc/commit/a487e4dd94656bf5671bf1cf38b64266a9ca4cbb) is a simple stroke.
That means it can't be used as a modifier (on windows super + d, super + e...), but only alone to display a start menu.
Solution : implement the meta key in the same way shift, alt and ctrl are (ToggleButton).

I would open a pr, but I don't have a way to try it out with the android toolchain as of now.

**Comment by gujjwal00** [comment]
Well, I originally implemented it as a toggle, but found the experience sub-optimal. Primary function of Ctrl/Shift/Alt is to be used in combination with other keys, so using a toggle button works well there. But for Super key, 90% of the time I just wanted to open the start menu. Using a toggle forced two taps, which I found a bit jarring in case of Super key. So I went with a simple button.

I do want the shortcuts to work though, and was hoping to come up with some sort of solution, but then I got busy with the new release.

**Comment by pop123123123** [comment]
In that case maybe a checkbox in the settings?
Or maybe a long press to toggle it, short press for a simple stroke (more work, I presume)

Nov 19, 2022 18:00:03 Gaurav Ujjwal ***@***.***>:

**Comment by Iey4iej3** [comment]
Super/Window key as a modifier is important. It is usually used, say, for the window manager there (mostly tiling wm's such as `i3wm` and `awesome`).

**Comment by gujjwal00** [comment]
I have changed it back to a toggle (https://github.com/gujjwal00/avnc/commit/24d7e760baf79f72559058b7dc0d22a2d6c2e714).
